/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * Rawfli API
 * The Rawfli API description
 * OpenAPI spec version: 1.0
 */
import {
  useInfiniteQuery,
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseInfiniteQueryResult,
  DefinedUseQueryResult,
  InfiniteData,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseInfiniteQueryOptions,
  UseInfiniteQueryResult,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  CommentResponseDtoResponse,
  CreateCommentDto,
  CreatePostDto,
  DeletedCommentResponseDtoResponse,
  DeletedPostResponseDtoResponse,
  PostListResponseDtoResponse,
  PostResponseDtoResponse,
  PostsControllerGetPopularPostsParams,
  PostsControllerGetPostsParams
} from '../../model';

import { customAxiosInstance } from '../../../mutator';




/**
 * @summary 포스트 목록 조회
 */
export const postsControllerGetPosts = (
    boardId: number,
    params?: PostsControllerGetPostsParams,
 signal?: AbortSignal
) => {
      
      
      return customAxiosInstance<PostListResponseDtoResponse>(
      {url: `/api/v1/boards/${boardId}/posts`, method: 'GET',
        params, signal
    },
      );
    }
  



export const getPostsControllerGetPostsInfiniteQueryKey = (boardId: number,
    params?: PostsControllerGetPostsParams,) => {
    return [
    'infinite', `/api/v1/boards/${boardId}/posts`, ...(params ? [params] : [])
    ] as const;
    }

export const getPostsControllerGetPostsQueryKey = (boardId: number,
    params?: PostsControllerGetPostsParams,) => {
    return [
    `/api/v1/boards/${boardId}/posts`, ...(params ? [params] : [])
    ] as const;
    }

    
export const getPostsControllerGetPostsInfiniteQueryOptions = <TData = InfiniteData<Awaited<ReturnType<typeof postsControllerGetPosts>>>, TError = unknown>(boardId: number,
    params?: PostsControllerGetPostsParams, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof postsControllerGetPosts>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getPostsControllerGetPostsInfiniteQueryKey(boardId,params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof postsControllerGetPosts>>> = ({ signal }) => postsControllerGetPosts(boardId,params, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(boardId), ...queryOptions} as UseInfiniteQueryOptions<Awaited<ReturnType<typeof postsControllerGetPosts>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type PostsControllerGetPostsInfiniteQueryResult = NonNullable<Awaited<ReturnType<typeof postsControllerGetPosts>>>
export type PostsControllerGetPostsInfiniteQueryError = unknown


export function usePostsControllerGetPostsInfinite<TData = InfiniteData<Awaited<ReturnType<typeof postsControllerGetPosts>>>, TError = unknown>(
 boardId: number,
    params: undefined |  PostsControllerGetPostsParams, options: { query:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof postsControllerGetPosts>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof postsControllerGetPosts>>,
          TError,
          Awaited<ReturnType<typeof postsControllerGetPosts>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function usePostsControllerGetPostsInfinite<TData = InfiniteData<Awaited<ReturnType<typeof postsControllerGetPosts>>>, TError = unknown>(
 boardId: number,
    params?: PostsControllerGetPostsParams, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof postsControllerGetPosts>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof postsControllerGetPosts>>,
          TError,
          Awaited<ReturnType<typeof postsControllerGetPosts>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function usePostsControllerGetPostsInfinite<TData = InfiniteData<Awaited<ReturnType<typeof postsControllerGetPosts>>>, TError = unknown>(
 boardId: number,
    params?: PostsControllerGetPostsParams, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof postsControllerGetPosts>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary 포스트 목록 조회
 */

export function usePostsControllerGetPostsInfinite<TData = InfiniteData<Awaited<ReturnType<typeof postsControllerGetPosts>>>, TError = unknown>(
 boardId: number,
    params?: PostsControllerGetPostsParams, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof postsControllerGetPosts>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getPostsControllerGetPostsInfiniteQueryOptions(boardId,params,options)

  const query = useInfiniteQuery(queryOptions, queryClient) as  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




export const getPostsControllerGetPostsQueryOptions = <TData = Awaited<ReturnType<typeof postsControllerGetPosts>>, TError = unknown>(boardId: number,
    params?: PostsControllerGetPostsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof postsControllerGetPosts>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getPostsControllerGetPostsQueryKey(boardId,params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof postsControllerGetPosts>>> = ({ signal }) => postsControllerGetPosts(boardId,params, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(boardId), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof postsControllerGetPosts>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type PostsControllerGetPostsQueryResult = NonNullable<Awaited<ReturnType<typeof postsControllerGetPosts>>>
export type PostsControllerGetPostsQueryError = unknown


export function usePostsControllerGetPosts<TData = Awaited<ReturnType<typeof postsControllerGetPosts>>, TError = unknown>(
 boardId: number,
    params: undefined |  PostsControllerGetPostsParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof postsControllerGetPosts>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof postsControllerGetPosts>>,
          TError,
          Awaited<ReturnType<typeof postsControllerGetPosts>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function usePostsControllerGetPosts<TData = Awaited<ReturnType<typeof postsControllerGetPosts>>, TError = unknown>(
 boardId: number,
    params?: PostsControllerGetPostsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof postsControllerGetPosts>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof postsControllerGetPosts>>,
          TError,
          Awaited<ReturnType<typeof postsControllerGetPosts>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function usePostsControllerGetPosts<TData = Awaited<ReturnType<typeof postsControllerGetPosts>>, TError = unknown>(
 boardId: number,
    params?: PostsControllerGetPostsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof postsControllerGetPosts>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary 포스트 목록 조회
 */

export function usePostsControllerGetPosts<TData = Awaited<ReturnType<typeof postsControllerGetPosts>>, TError = unknown>(
 boardId: number,
    params?: PostsControllerGetPostsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof postsControllerGetPosts>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getPostsControllerGetPostsQueryOptions(boardId,params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




/**
 * @summary 포스트 작성
 */
export const postsControllerCreatePost = (
    boardId: number,
    createPostDto: CreatePostDto,
 signal?: AbortSignal
) => {
      
      
      return customAxiosInstance<PostResponseDtoResponse>(
      {url: `/api/v1/boards/${boardId}/posts`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: createPostDto, signal
    },
      );
    }
  


export const getPostsControllerCreatePostMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postsControllerCreatePost>>, TError,{boardId: number;data: CreatePostDto}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof postsControllerCreatePost>>, TError,{boardId: number;data: CreatePostDto}, TContext> => {

const mutationKey = ['postsControllerCreatePost'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postsControllerCreatePost>>, {boardId: number;data: CreatePostDto}> = (props) => {
          const {boardId,data} = props ?? {};

          return  postsControllerCreatePost(boardId,data,)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type PostsControllerCreatePostMutationResult = NonNullable<Awaited<ReturnType<typeof postsControllerCreatePost>>>
    export type PostsControllerCreatePostMutationBody = CreatePostDto
    export type PostsControllerCreatePostMutationError = unknown

    /**
 * @summary 포스트 작성
 */
export const usePostsControllerCreatePost = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postsControllerCreatePost>>, TError,{boardId: number;data: CreatePostDto}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postsControllerCreatePost>>,
        TError,
        {boardId: number;data: CreatePostDto},
        TContext
      > => {
      return useMutation(getPostsControllerCreatePostMutationOptions(options), queryClient);
    }
    /**
 * @summary 인기 포스트 목록 조회
 */
export const postsControllerGetPopularPosts = (
    boardId: number,
    params?: PostsControllerGetPopularPostsParams,
 signal?: AbortSignal
) => {
      
      
      return customAxiosInstance<PostListResponseDtoResponse>(
      {url: `/api/v1/boards/${boardId}/posts/popular`, method: 'GET',
        params, signal
    },
      );
    }
  



export const getPostsControllerGetPopularPostsInfiniteQueryKey = (boardId: number,
    params?: PostsControllerGetPopularPostsParams,) => {
    return [
    'infinite', `/api/v1/boards/${boardId}/posts/popular`, ...(params ? [params] : [])
    ] as const;
    }

export const getPostsControllerGetPopularPostsQueryKey = (boardId: number,
    params?: PostsControllerGetPopularPostsParams,) => {
    return [
    `/api/v1/boards/${boardId}/posts/popular`, ...(params ? [params] : [])
    ] as const;
    }

    
export const getPostsControllerGetPopularPostsInfiniteQueryOptions = <TData = InfiniteData<Awaited<ReturnType<typeof postsControllerGetPopularPosts>>>, TError = unknown>(boardId: number,
    params?: PostsControllerGetPopularPostsParams, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof postsControllerGetPopularPosts>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getPostsControllerGetPopularPostsInfiniteQueryKey(boardId,params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof postsControllerGetPopularPosts>>> = ({ signal }) => postsControllerGetPopularPosts(boardId,params, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(boardId), ...queryOptions} as UseInfiniteQueryOptions<Awaited<ReturnType<typeof postsControllerGetPopularPosts>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type PostsControllerGetPopularPostsInfiniteQueryResult = NonNullable<Awaited<ReturnType<typeof postsControllerGetPopularPosts>>>
export type PostsControllerGetPopularPostsInfiniteQueryError = unknown


export function usePostsControllerGetPopularPostsInfinite<TData = InfiniteData<Awaited<ReturnType<typeof postsControllerGetPopularPosts>>>, TError = unknown>(
 boardId: number,
    params: undefined |  PostsControllerGetPopularPostsParams, options: { query:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof postsControllerGetPopularPosts>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof postsControllerGetPopularPosts>>,
          TError,
          Awaited<ReturnType<typeof postsControllerGetPopularPosts>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function usePostsControllerGetPopularPostsInfinite<TData = InfiniteData<Awaited<ReturnType<typeof postsControllerGetPopularPosts>>>, TError = unknown>(
 boardId: number,
    params?: PostsControllerGetPopularPostsParams, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof postsControllerGetPopularPosts>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof postsControllerGetPopularPosts>>,
          TError,
          Awaited<ReturnType<typeof postsControllerGetPopularPosts>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function usePostsControllerGetPopularPostsInfinite<TData = InfiniteData<Awaited<ReturnType<typeof postsControllerGetPopularPosts>>>, TError = unknown>(
 boardId: number,
    params?: PostsControllerGetPopularPostsParams, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof postsControllerGetPopularPosts>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary 인기 포스트 목록 조회
 */

export function usePostsControllerGetPopularPostsInfinite<TData = InfiniteData<Awaited<ReturnType<typeof postsControllerGetPopularPosts>>>, TError = unknown>(
 boardId: number,
    params?: PostsControllerGetPopularPostsParams, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof postsControllerGetPopularPosts>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getPostsControllerGetPopularPostsInfiniteQueryOptions(boardId,params,options)

  const query = useInfiniteQuery(queryOptions, queryClient) as  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




export const getPostsControllerGetPopularPostsQueryOptions = <TData = Awaited<ReturnType<typeof postsControllerGetPopularPosts>>, TError = unknown>(boardId: number,
    params?: PostsControllerGetPopularPostsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof postsControllerGetPopularPosts>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getPostsControllerGetPopularPostsQueryKey(boardId,params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof postsControllerGetPopularPosts>>> = ({ signal }) => postsControllerGetPopularPosts(boardId,params, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(boardId), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof postsControllerGetPopularPosts>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type PostsControllerGetPopularPostsQueryResult = NonNullable<Awaited<ReturnType<typeof postsControllerGetPopularPosts>>>
export type PostsControllerGetPopularPostsQueryError = unknown


export function usePostsControllerGetPopularPosts<TData = Awaited<ReturnType<typeof postsControllerGetPopularPosts>>, TError = unknown>(
 boardId: number,
    params: undefined |  PostsControllerGetPopularPostsParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof postsControllerGetPopularPosts>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof postsControllerGetPopularPosts>>,
          TError,
          Awaited<ReturnType<typeof postsControllerGetPopularPosts>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function usePostsControllerGetPopularPosts<TData = Awaited<ReturnType<typeof postsControllerGetPopularPosts>>, TError = unknown>(
 boardId: number,
    params?: PostsControllerGetPopularPostsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof postsControllerGetPopularPosts>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof postsControllerGetPopularPosts>>,
          TError,
          Awaited<ReturnType<typeof postsControllerGetPopularPosts>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function usePostsControllerGetPopularPosts<TData = Awaited<ReturnType<typeof postsControllerGetPopularPosts>>, TError = unknown>(
 boardId: number,
    params?: PostsControllerGetPopularPostsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof postsControllerGetPopularPosts>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary 인기 포스트 목록 조회
 */

export function usePostsControllerGetPopularPosts<TData = Awaited<ReturnType<typeof postsControllerGetPopularPosts>>, TError = unknown>(
 boardId: number,
    params?: PostsControllerGetPopularPostsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof postsControllerGetPopularPosts>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getPostsControllerGetPopularPostsQueryOptions(boardId,params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




/**
 * @summary 포스트 조회
 */
export const postsControllerGetPost = (
    boardId: number,
    postId: number,
 signal?: AbortSignal
) => {
      
      
      return customAxiosInstance<PostResponseDtoResponse>(
      {url: `/api/v1/boards/${boardId}/posts/${postId}`, method: 'GET', signal
    },
      );
    }
  



export const getPostsControllerGetPostInfiniteQueryKey = (boardId: number,
    postId: number,) => {
    return [
    'infinite', `/api/v1/boards/${boardId}/posts/${postId}`
    ] as const;
    }

export const getPostsControllerGetPostQueryKey = (boardId: number,
    postId: number,) => {
    return [
    `/api/v1/boards/${boardId}/posts/${postId}`
    ] as const;
    }

    
export const getPostsControllerGetPostInfiniteQueryOptions = <TData = InfiniteData<Awaited<ReturnType<typeof postsControllerGetPost>>>, TError = unknown>(boardId: number,
    postId: number, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof postsControllerGetPost>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getPostsControllerGetPostInfiniteQueryKey(boardId,postId);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof postsControllerGetPost>>> = ({ signal }) => postsControllerGetPost(boardId,postId, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(boardId && postId), ...queryOptions} as UseInfiniteQueryOptions<Awaited<ReturnType<typeof postsControllerGetPost>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type PostsControllerGetPostInfiniteQueryResult = NonNullable<Awaited<ReturnType<typeof postsControllerGetPost>>>
export type PostsControllerGetPostInfiniteQueryError = unknown


export function usePostsControllerGetPostInfinite<TData = InfiniteData<Awaited<ReturnType<typeof postsControllerGetPost>>>, TError = unknown>(
 boardId: number,
    postId: number, options: { query:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof postsControllerGetPost>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof postsControllerGetPost>>,
          TError,
          Awaited<ReturnType<typeof postsControllerGetPost>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function usePostsControllerGetPostInfinite<TData = InfiniteData<Awaited<ReturnType<typeof postsControllerGetPost>>>, TError = unknown>(
 boardId: number,
    postId: number, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof postsControllerGetPost>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof postsControllerGetPost>>,
          TError,
          Awaited<ReturnType<typeof postsControllerGetPost>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function usePostsControllerGetPostInfinite<TData = InfiniteData<Awaited<ReturnType<typeof postsControllerGetPost>>>, TError = unknown>(
 boardId: number,
    postId: number, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof postsControllerGetPost>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary 포스트 조회
 */

export function usePostsControllerGetPostInfinite<TData = InfiniteData<Awaited<ReturnType<typeof postsControllerGetPost>>>, TError = unknown>(
 boardId: number,
    postId: number, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof postsControllerGetPost>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getPostsControllerGetPostInfiniteQueryOptions(boardId,postId,options)

  const query = useInfiniteQuery(queryOptions, queryClient) as  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




export const getPostsControllerGetPostQueryOptions = <TData = Awaited<ReturnType<typeof postsControllerGetPost>>, TError = unknown>(boardId: number,
    postId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof postsControllerGetPost>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getPostsControllerGetPostQueryKey(boardId,postId);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof postsControllerGetPost>>> = ({ signal }) => postsControllerGetPost(boardId,postId, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(boardId && postId), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof postsControllerGetPost>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type PostsControllerGetPostQueryResult = NonNullable<Awaited<ReturnType<typeof postsControllerGetPost>>>
export type PostsControllerGetPostQueryError = unknown


export function usePostsControllerGetPost<TData = Awaited<ReturnType<typeof postsControllerGetPost>>, TError = unknown>(
 boardId: number,
    postId: number, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof postsControllerGetPost>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof postsControllerGetPost>>,
          TError,
          Awaited<ReturnType<typeof postsControllerGetPost>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function usePostsControllerGetPost<TData = Awaited<ReturnType<typeof postsControllerGetPost>>, TError = unknown>(
 boardId: number,
    postId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof postsControllerGetPost>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof postsControllerGetPost>>,
          TError,
          Awaited<ReturnType<typeof postsControllerGetPost>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function usePostsControllerGetPost<TData = Awaited<ReturnType<typeof postsControllerGetPost>>, TError = unknown>(
 boardId: number,
    postId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof postsControllerGetPost>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary 포스트 조회
 */

export function usePostsControllerGetPost<TData = Awaited<ReturnType<typeof postsControllerGetPost>>, TError = unknown>(
 boardId: number,
    postId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof postsControllerGetPost>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getPostsControllerGetPostQueryOptions(boardId,postId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




/**
 * @summary 포스트 삭제
 */
export const postsControllerDeletePost = (
    boardId: number,
    postId: number,
 signal?: AbortSignal
) => {
      
      
      return customAxiosInstance<DeletedPostResponseDtoResponse>(
      {url: `/api/v1/boards/${boardId}/posts/${postId}`, method: 'DELETE', signal
    },
      );
    }
  


export const getPostsControllerDeletePostMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postsControllerDeletePost>>, TError,{boardId: number;postId: number}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof postsControllerDeletePost>>, TError,{boardId: number;postId: number}, TContext> => {

const mutationKey = ['postsControllerDeletePost'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postsControllerDeletePost>>, {boardId: number;postId: number}> = (props) => {
          const {boardId,postId} = props ?? {};

          return  postsControllerDeletePost(boardId,postId,)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type PostsControllerDeletePostMutationResult = NonNullable<Awaited<ReturnType<typeof postsControllerDeletePost>>>
    
    export type PostsControllerDeletePostMutationError = unknown

    /**
 * @summary 포스트 삭제
 */
export const usePostsControllerDeletePost = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postsControllerDeletePost>>, TError,{boardId: number;postId: number}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postsControllerDeletePost>>,
        TError,
        {boardId: number;postId: number},
        TContext
      > => {
      return useMutation(getPostsControllerDeletePostMutationOptions(options), queryClient);
    }
    /**
 * @summary 작품 댓글 작성
 */
export const postsControllerCreatePhotoComment = (
    boardId: number,
    postId: number,
    photoId: string,
    createCommentDto: CreateCommentDto,
 signal?: AbortSignal
) => {
      
      
      return customAxiosInstance<CommentResponseDtoResponse>(
      {url: `/api/v1/boards/${boardId}/posts/${postId}/photos/${photoId}/comments`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: createCommentDto, signal
    },
      );
    }
  


export const getPostsControllerCreatePhotoCommentMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postsControllerCreatePhotoComment>>, TError,{boardId: number;postId: number;photoId: string;data: CreateCommentDto}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof postsControllerCreatePhotoComment>>, TError,{boardId: number;postId: number;photoId: string;data: CreateCommentDto}, TContext> => {

const mutationKey = ['postsControllerCreatePhotoComment'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postsControllerCreatePhotoComment>>, {boardId: number;postId: number;photoId: string;data: CreateCommentDto}> = (props) => {
          const {boardId,postId,photoId,data} = props ?? {};

          return  postsControllerCreatePhotoComment(boardId,postId,photoId,data,)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type PostsControllerCreatePhotoCommentMutationResult = NonNullable<Awaited<ReturnType<typeof postsControllerCreatePhotoComment>>>
    export type PostsControllerCreatePhotoCommentMutationBody = CreateCommentDto
    export type PostsControllerCreatePhotoCommentMutationError = unknown

    /**
 * @summary 작품 댓글 작성
 */
export const usePostsControllerCreatePhotoComment = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postsControllerCreatePhotoComment>>, TError,{boardId: number;postId: number;photoId: string;data: CreateCommentDto}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postsControllerCreatePhotoComment>>,
        TError,
        {boardId: number;postId: number;photoId: string;data: CreateCommentDto},
        TContext
      > => {
      return useMutation(getPostsControllerCreatePhotoCommentMutationOptions(options), queryClient);
    }
    /**
 * @summary 작품 댓글 삭제
 */
export const postsControllerDeletePhotoComment = (
    boardId: number,
    postId: number,
    photoId: string,
    commentId: number,
 signal?: AbortSignal
) => {
      
      
      return customAxiosInstance<DeletedCommentResponseDtoResponse>(
      {url: `/api/v1/boards/${boardId}/posts/${postId}/photos/${photoId}/comments/${commentId}`, method: 'DELETE', signal
    },
      );
    }
  


export const getPostsControllerDeletePhotoCommentMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postsControllerDeletePhotoComment>>, TError,{boardId: number;postId: number;photoId: string;commentId: number}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof postsControllerDeletePhotoComment>>, TError,{boardId: number;postId: number;photoId: string;commentId: number}, TContext> => {

const mutationKey = ['postsControllerDeletePhotoComment'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postsControllerDeletePhotoComment>>, {boardId: number;postId: number;photoId: string;commentId: number}> = (props) => {
          const {boardId,postId,photoId,commentId} = props ?? {};

          return  postsControllerDeletePhotoComment(boardId,postId,photoId,commentId,)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type PostsControllerDeletePhotoCommentMutationResult = NonNullable<Awaited<ReturnType<typeof postsControllerDeletePhotoComment>>>
    
    export type PostsControllerDeletePhotoCommentMutationError = unknown

    /**
 * @summary 작품 댓글 삭제
 */
export const usePostsControllerDeletePhotoComment = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postsControllerDeletePhotoComment>>, TError,{boardId: number;postId: number;photoId: string;commentId: number}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postsControllerDeletePhotoComment>>,
        TError,
        {boardId: number;postId: number;photoId: string;commentId: number},
        TContext
      > => {
      return useMutation(getPostsControllerDeletePhotoCommentMutationOptions(options), queryClient);
    }
    