/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * Rawfli API
 * The Rawfli API description
 * OpenAPI spec version: 1.0
 */
import {
  useInfiniteQuery,
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseInfiniteQueryResult,
  DefinedUseQueryResult,
  InfiniteData,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseInfiniteQueryOptions,
  UseInfiniteQueryResult,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  CommentResponseDto,
  CreateCommentDto,
  CreatePostDto,
  DeletedCommentResponseDto,
  DeletedPostResponseDto,
  LikePostResponseDto,
  PostListResponseDto,
  PostResponseDto,
  PostsControllerGetDeletedPosts200,
  PostsControllerGetPostsParams,
  PostsControllerToggleLike201
} from '../../model';

import { customAxiosInstance } from '../../../mutator';




/**
 * @summary 게시글 목록 조회
 */
export const postsControllerGetPosts = (
    boardId: number,
    params: PostsControllerGetPostsParams,
 signal?: AbortSignal
) => {
      
      
      return customAxiosInstance<PostListResponseDto>(
      {url: `/api/v1/boards/${boardId}/posts`, method: 'GET',
        params, signal
    },
      );
    }
  



export const getPostsControllerGetPostsInfiniteQueryKey = (boardId: number,
    params?: PostsControllerGetPostsParams,) => {
    return [
    'infinite', `/api/v1/boards/${boardId}/posts`, ...(params ? [params] : [])
    ] as const;
    }

export const getPostsControllerGetPostsQueryKey = (boardId: number,
    params?: PostsControllerGetPostsParams,) => {
    return [
    `/api/v1/boards/${boardId}/posts`, ...(params ? [params] : [])
    ] as const;
    }

    
export const getPostsControllerGetPostsInfiniteQueryOptions = <TData = InfiniteData<Awaited<ReturnType<typeof postsControllerGetPosts>>>, TError = unknown>(boardId: number,
    params: PostsControllerGetPostsParams, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof postsControllerGetPosts>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getPostsControllerGetPostsInfiniteQueryKey(boardId,params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof postsControllerGetPosts>>> = ({ signal }) => postsControllerGetPosts(boardId,params, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(boardId), ...queryOptions} as UseInfiniteQueryOptions<Awaited<ReturnType<typeof postsControllerGetPosts>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type PostsControllerGetPostsInfiniteQueryResult = NonNullable<Awaited<ReturnType<typeof postsControllerGetPosts>>>
export type PostsControllerGetPostsInfiniteQueryError = unknown


export function usePostsControllerGetPostsInfinite<TData = InfiniteData<Awaited<ReturnType<typeof postsControllerGetPosts>>>, TError = unknown>(
 boardId: number,
    params: PostsControllerGetPostsParams, options: { query:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof postsControllerGetPosts>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof postsControllerGetPosts>>,
          TError,
          Awaited<ReturnType<typeof postsControllerGetPosts>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function usePostsControllerGetPostsInfinite<TData = InfiniteData<Awaited<ReturnType<typeof postsControllerGetPosts>>>, TError = unknown>(
 boardId: number,
    params: PostsControllerGetPostsParams, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof postsControllerGetPosts>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof postsControllerGetPosts>>,
          TError,
          Awaited<ReturnType<typeof postsControllerGetPosts>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function usePostsControllerGetPostsInfinite<TData = InfiniteData<Awaited<ReturnType<typeof postsControllerGetPosts>>>, TError = unknown>(
 boardId: number,
    params: PostsControllerGetPostsParams, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof postsControllerGetPosts>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary 게시글 목록 조회
 */

export function usePostsControllerGetPostsInfinite<TData = InfiniteData<Awaited<ReturnType<typeof postsControllerGetPosts>>>, TError = unknown>(
 boardId: number,
    params: PostsControllerGetPostsParams, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof postsControllerGetPosts>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getPostsControllerGetPostsInfiniteQueryOptions(boardId,params,options)

  const query = useInfiniteQuery(queryOptions, queryClient) as  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




export const getPostsControllerGetPostsQueryOptions = <TData = Awaited<ReturnType<typeof postsControllerGetPosts>>, TError = unknown>(boardId: number,
    params: PostsControllerGetPostsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof postsControllerGetPosts>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getPostsControllerGetPostsQueryKey(boardId,params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof postsControllerGetPosts>>> = ({ signal }) => postsControllerGetPosts(boardId,params, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(boardId), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof postsControllerGetPosts>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type PostsControllerGetPostsQueryResult = NonNullable<Awaited<ReturnType<typeof postsControllerGetPosts>>>
export type PostsControllerGetPostsQueryError = unknown


export function usePostsControllerGetPosts<TData = Awaited<ReturnType<typeof postsControllerGetPosts>>, TError = unknown>(
 boardId: number,
    params: PostsControllerGetPostsParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof postsControllerGetPosts>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof postsControllerGetPosts>>,
          TError,
          Awaited<ReturnType<typeof postsControllerGetPosts>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function usePostsControllerGetPosts<TData = Awaited<ReturnType<typeof postsControllerGetPosts>>, TError = unknown>(
 boardId: number,
    params: PostsControllerGetPostsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof postsControllerGetPosts>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof postsControllerGetPosts>>,
          TError,
          Awaited<ReturnType<typeof postsControllerGetPosts>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function usePostsControllerGetPosts<TData = Awaited<ReturnType<typeof postsControllerGetPosts>>, TError = unknown>(
 boardId: number,
    params: PostsControllerGetPostsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof postsControllerGetPosts>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary 게시글 목록 조회
 */

export function usePostsControllerGetPosts<TData = Awaited<ReturnType<typeof postsControllerGetPosts>>, TError = unknown>(
 boardId: number,
    params: PostsControllerGetPostsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof postsControllerGetPosts>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getPostsControllerGetPostsQueryOptions(boardId,params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




/**
 * @summary 게시글 작성
 */
export const postsControllerCreatePost = (
    boardId: number,
    createPostDto: CreatePostDto,
 signal?: AbortSignal
) => {
      
      
      return customAxiosInstance<PostResponseDto>(
      {url: `/api/v1/boards/${boardId}/posts`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: createPostDto, signal
    },
      );
    }
  


export const getPostsControllerCreatePostMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postsControllerCreatePost>>, TError,{boardId: number;data: CreatePostDto}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof postsControllerCreatePost>>, TError,{boardId: number;data: CreatePostDto}, TContext> => {

const mutationKey = ['postsControllerCreatePost'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postsControllerCreatePost>>, {boardId: number;data: CreatePostDto}> = (props) => {
          const {boardId,data} = props ?? {};

          return  postsControllerCreatePost(boardId,data,)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type PostsControllerCreatePostMutationResult = NonNullable<Awaited<ReturnType<typeof postsControllerCreatePost>>>
    export type PostsControllerCreatePostMutationBody = CreatePostDto
    export type PostsControllerCreatePostMutationError = unknown

    /**
 * @summary 게시글 작성
 */
export const usePostsControllerCreatePost = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postsControllerCreatePost>>, TError,{boardId: number;data: CreatePostDto}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postsControllerCreatePost>>,
        TError,
        {boardId: number;data: CreatePostDto},
        TContext
      > => {
      return useMutation(getPostsControllerCreatePostMutationOptions(options), queryClient);
    }
    /**
 * @summary 게시글 조회
 */
export const postsControllerGetPost = (
    boardId: number,
    postId: number,
 signal?: AbortSignal
) => {
      
      
      return customAxiosInstance<PostResponseDto>(
      {url: `/api/v1/boards/${boardId}/posts/${postId}`, method: 'GET', signal
    },
      );
    }
  



export const getPostsControllerGetPostInfiniteQueryKey = (boardId: number,
    postId: number,) => {
    return [
    'infinite', `/api/v1/boards/${boardId}/posts/${postId}`
    ] as const;
    }

export const getPostsControllerGetPostQueryKey = (boardId: number,
    postId: number,) => {
    return [
    `/api/v1/boards/${boardId}/posts/${postId}`
    ] as const;
    }

    
export const getPostsControllerGetPostInfiniteQueryOptions = <TData = InfiniteData<Awaited<ReturnType<typeof postsControllerGetPost>>>, TError = unknown>(boardId: number,
    postId: number, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof postsControllerGetPost>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getPostsControllerGetPostInfiniteQueryKey(boardId,postId);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof postsControllerGetPost>>> = ({ signal }) => postsControllerGetPost(boardId,postId, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(boardId && postId), ...queryOptions} as UseInfiniteQueryOptions<Awaited<ReturnType<typeof postsControllerGetPost>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type PostsControllerGetPostInfiniteQueryResult = NonNullable<Awaited<ReturnType<typeof postsControllerGetPost>>>
export type PostsControllerGetPostInfiniteQueryError = unknown


export function usePostsControllerGetPostInfinite<TData = InfiniteData<Awaited<ReturnType<typeof postsControllerGetPost>>>, TError = unknown>(
 boardId: number,
    postId: number, options: { query:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof postsControllerGetPost>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof postsControllerGetPost>>,
          TError,
          Awaited<ReturnType<typeof postsControllerGetPost>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function usePostsControllerGetPostInfinite<TData = InfiniteData<Awaited<ReturnType<typeof postsControllerGetPost>>>, TError = unknown>(
 boardId: number,
    postId: number, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof postsControllerGetPost>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof postsControllerGetPost>>,
          TError,
          Awaited<ReturnType<typeof postsControllerGetPost>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function usePostsControllerGetPostInfinite<TData = InfiniteData<Awaited<ReturnType<typeof postsControllerGetPost>>>, TError = unknown>(
 boardId: number,
    postId: number, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof postsControllerGetPost>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary 게시글 조회
 */

export function usePostsControllerGetPostInfinite<TData = InfiniteData<Awaited<ReturnType<typeof postsControllerGetPost>>>, TError = unknown>(
 boardId: number,
    postId: number, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof postsControllerGetPost>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getPostsControllerGetPostInfiniteQueryOptions(boardId,postId,options)

  const query = useInfiniteQuery(queryOptions, queryClient) as  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




export const getPostsControllerGetPostQueryOptions = <TData = Awaited<ReturnType<typeof postsControllerGetPost>>, TError = unknown>(boardId: number,
    postId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof postsControllerGetPost>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getPostsControllerGetPostQueryKey(boardId,postId);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof postsControllerGetPost>>> = ({ signal }) => postsControllerGetPost(boardId,postId, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(boardId && postId), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof postsControllerGetPost>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type PostsControllerGetPostQueryResult = NonNullable<Awaited<ReturnType<typeof postsControllerGetPost>>>
export type PostsControllerGetPostQueryError = unknown


export function usePostsControllerGetPost<TData = Awaited<ReturnType<typeof postsControllerGetPost>>, TError = unknown>(
 boardId: number,
    postId: number, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof postsControllerGetPost>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof postsControllerGetPost>>,
          TError,
          Awaited<ReturnType<typeof postsControllerGetPost>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function usePostsControllerGetPost<TData = Awaited<ReturnType<typeof postsControllerGetPost>>, TError = unknown>(
 boardId: number,
    postId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof postsControllerGetPost>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof postsControllerGetPost>>,
          TError,
          Awaited<ReturnType<typeof postsControllerGetPost>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function usePostsControllerGetPost<TData = Awaited<ReturnType<typeof postsControllerGetPost>>, TError = unknown>(
 boardId: number,
    postId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof postsControllerGetPost>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary 게시글 조회
 */

export function usePostsControllerGetPost<TData = Awaited<ReturnType<typeof postsControllerGetPost>>, TError = unknown>(
 boardId: number,
    postId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof postsControllerGetPost>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getPostsControllerGetPostQueryOptions(boardId,postId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




/**
 * @summary 게시글 삭제
 */
export const postsControllerDeletePost = (
    boardId: number,
    postId: number,
 signal?: AbortSignal
) => {
      
      
      return customAxiosInstance<DeletedPostResponseDto>(
      {url: `/api/v1/boards/${boardId}/posts/${postId}`, method: 'DELETE', signal
    },
      );
    }
  


export const getPostsControllerDeletePostMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postsControllerDeletePost>>, TError,{boardId: number;postId: number}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof postsControllerDeletePost>>, TError,{boardId: number;postId: number}, TContext> => {

const mutationKey = ['postsControllerDeletePost'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postsControllerDeletePost>>, {boardId: number;postId: number}> = (props) => {
          const {boardId,postId} = props ?? {};

          return  postsControllerDeletePost(boardId,postId,)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type PostsControllerDeletePostMutationResult = NonNullable<Awaited<ReturnType<typeof postsControllerDeletePost>>>
    
    export type PostsControllerDeletePostMutationError = unknown

    /**
 * @summary 게시글 삭제
 */
export const usePostsControllerDeletePost = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postsControllerDeletePost>>, TError,{boardId: number;postId: number}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postsControllerDeletePost>>,
        TError,
        {boardId: number;postId: number},
        TContext
      > => {
      return useMutation(getPostsControllerDeletePostMutationOptions(options), queryClient);
    }
    /**
 * @summary 게시글 좋아요 토글
 */
export const postsControllerToggleLike = (
    boardId: number,
    postId: number,
 signal?: AbortSignal
) => {
      
      
      return customAxiosInstance<LikePostResponseDto | PostsControllerToggleLike201>(
      {url: `/api/v1/boards/${boardId}/posts/${postId}/like`, method: 'POST', signal
    },
      );
    }
  


export const getPostsControllerToggleLikeMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postsControllerToggleLike>>, TError,{boardId: number;postId: number}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof postsControllerToggleLike>>, TError,{boardId: number;postId: number}, TContext> => {

const mutationKey = ['postsControllerToggleLike'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postsControllerToggleLike>>, {boardId: number;postId: number}> = (props) => {
          const {boardId,postId} = props ?? {};

          return  postsControllerToggleLike(boardId,postId,)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type PostsControllerToggleLikeMutationResult = NonNullable<Awaited<ReturnType<typeof postsControllerToggleLike>>>
    
    export type PostsControllerToggleLikeMutationError = unknown

    /**
 * @summary 게시글 좋아요 토글
 */
export const usePostsControllerToggleLike = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postsControllerToggleLike>>, TError,{boardId: number;postId: number}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postsControllerToggleLike>>,
        TError,
        {boardId: number;postId: number},
        TContext
      > => {
      return useMutation(getPostsControllerToggleLikeMutationOptions(options), queryClient);
    }
    /**
 * @summary 댓글 작성
 */
export const postsControllerCreateComment = (
    boardId: number,
    postId: number,
    createCommentDto: CreateCommentDto,
 signal?: AbortSignal
) => {
      
      
      return customAxiosInstance<CommentResponseDto>(
      {url: `/api/v1/boards/${boardId}/posts/${postId}/comments`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: createCommentDto, signal
    },
      );
    }
  


export const getPostsControllerCreateCommentMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postsControllerCreateComment>>, TError,{boardId: number;postId: number;data: CreateCommentDto}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof postsControllerCreateComment>>, TError,{boardId: number;postId: number;data: CreateCommentDto}, TContext> => {

const mutationKey = ['postsControllerCreateComment'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postsControllerCreateComment>>, {boardId: number;postId: number;data: CreateCommentDto}> = (props) => {
          const {boardId,postId,data} = props ?? {};

          return  postsControllerCreateComment(boardId,postId,data,)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type PostsControllerCreateCommentMutationResult = NonNullable<Awaited<ReturnType<typeof postsControllerCreateComment>>>
    export type PostsControllerCreateCommentMutationBody = CreateCommentDto
    export type PostsControllerCreateCommentMutationError = unknown

    /**
 * @summary 댓글 작성
 */
export const usePostsControllerCreateComment = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postsControllerCreateComment>>, TError,{boardId: number;postId: number;data: CreateCommentDto}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postsControllerCreateComment>>,
        TError,
        {boardId: number;postId: number;data: CreateCommentDto},
        TContext
      > => {
      return useMutation(getPostsControllerCreateCommentMutationOptions(options), queryClient);
    }
    /**
 * @summary 댓글 삭제
 */
export const postsControllerDeleteComment = (
    boardId: number,
    postId: number,
    commentId: number,
 signal?: AbortSignal
) => {
      
      
      return customAxiosInstance<DeletedCommentResponseDto>(
      {url: `/api/v1/boards/${boardId}/posts/${postId}/comments/${commentId}`, method: 'DELETE', signal
    },
      );
    }
  


export const getPostsControllerDeleteCommentMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postsControllerDeleteComment>>, TError,{boardId: number;postId: number;commentId: number}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof postsControllerDeleteComment>>, TError,{boardId: number;postId: number;commentId: number}, TContext> => {

const mutationKey = ['postsControllerDeleteComment'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postsControllerDeleteComment>>, {boardId: number;postId: number;commentId: number}> = (props) => {
          const {boardId,postId,commentId} = props ?? {};

          return  postsControllerDeleteComment(boardId,postId,commentId,)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type PostsControllerDeleteCommentMutationResult = NonNullable<Awaited<ReturnType<typeof postsControllerDeleteComment>>>
    
    export type PostsControllerDeleteCommentMutationError = unknown

    /**
 * @summary 댓글 삭제
 */
export const usePostsControllerDeleteComment = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postsControllerDeleteComment>>, TError,{boardId: number;postId: number;commentId: number}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postsControllerDeleteComment>>,
        TError,
        {boardId: number;postId: number;commentId: number},
        TContext
      > => {
      return useMutation(getPostsControllerDeleteCommentMutationOptions(options), queryClient);
    }
    export const postsControllerGetDeletedPosts = (
    boardId: number,
 signal?: AbortSignal
) => {
      
      
      return customAxiosInstance<PostsControllerGetDeletedPosts200>(
      {url: `/api/v1/boards/${boardId}/posts/deleted/all`, method: 'GET', signal
    },
      );
    }
  



export const getPostsControllerGetDeletedPostsInfiniteQueryKey = (boardId: number,) => {
    return [
    'infinite', `/api/v1/boards/${boardId}/posts/deleted/all`
    ] as const;
    }

export const getPostsControllerGetDeletedPostsQueryKey = (boardId: number,) => {
    return [
    `/api/v1/boards/${boardId}/posts/deleted/all`
    ] as const;
    }

    
export const getPostsControllerGetDeletedPostsInfiniteQueryOptions = <TData = InfiniteData<Awaited<ReturnType<typeof postsControllerGetDeletedPosts>>>, TError = unknown>(boardId: number, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof postsControllerGetDeletedPosts>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getPostsControllerGetDeletedPostsInfiniteQueryKey(boardId);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof postsControllerGetDeletedPosts>>> = ({ signal }) => postsControllerGetDeletedPosts(boardId, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(boardId), ...queryOptions} as UseInfiniteQueryOptions<Awaited<ReturnType<typeof postsControllerGetDeletedPosts>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type PostsControllerGetDeletedPostsInfiniteQueryResult = NonNullable<Awaited<ReturnType<typeof postsControllerGetDeletedPosts>>>
export type PostsControllerGetDeletedPostsInfiniteQueryError = unknown


export function usePostsControllerGetDeletedPostsInfinite<TData = InfiniteData<Awaited<ReturnType<typeof postsControllerGetDeletedPosts>>>, TError = unknown>(
 boardId: number, options: { query:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof postsControllerGetDeletedPosts>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof postsControllerGetDeletedPosts>>,
          TError,
          Awaited<ReturnType<typeof postsControllerGetDeletedPosts>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function usePostsControllerGetDeletedPostsInfinite<TData = InfiniteData<Awaited<ReturnType<typeof postsControllerGetDeletedPosts>>>, TError = unknown>(
 boardId: number, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof postsControllerGetDeletedPosts>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof postsControllerGetDeletedPosts>>,
          TError,
          Awaited<ReturnType<typeof postsControllerGetDeletedPosts>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function usePostsControllerGetDeletedPostsInfinite<TData = InfiniteData<Awaited<ReturnType<typeof postsControllerGetDeletedPosts>>>, TError = unknown>(
 boardId: number, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof postsControllerGetDeletedPosts>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function usePostsControllerGetDeletedPostsInfinite<TData = InfiniteData<Awaited<ReturnType<typeof postsControllerGetDeletedPosts>>>, TError = unknown>(
 boardId: number, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof postsControllerGetDeletedPosts>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getPostsControllerGetDeletedPostsInfiniteQueryOptions(boardId,options)

  const query = useInfiniteQuery(queryOptions, queryClient) as  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




export const getPostsControllerGetDeletedPostsQueryOptions = <TData = Awaited<ReturnType<typeof postsControllerGetDeletedPosts>>, TError = unknown>(boardId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof postsControllerGetDeletedPosts>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getPostsControllerGetDeletedPostsQueryKey(boardId);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof postsControllerGetDeletedPosts>>> = ({ signal }) => postsControllerGetDeletedPosts(boardId, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(boardId), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof postsControllerGetDeletedPosts>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type PostsControllerGetDeletedPostsQueryResult = NonNullable<Awaited<ReturnType<typeof postsControllerGetDeletedPosts>>>
export type PostsControllerGetDeletedPostsQueryError = unknown


export function usePostsControllerGetDeletedPosts<TData = Awaited<ReturnType<typeof postsControllerGetDeletedPosts>>, TError = unknown>(
 boardId: number, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof postsControllerGetDeletedPosts>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof postsControllerGetDeletedPosts>>,
          TError,
          Awaited<ReturnType<typeof postsControllerGetDeletedPosts>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function usePostsControllerGetDeletedPosts<TData = Awaited<ReturnType<typeof postsControllerGetDeletedPosts>>, TError = unknown>(
 boardId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof postsControllerGetDeletedPosts>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof postsControllerGetDeletedPosts>>,
          TError,
          Awaited<ReturnType<typeof postsControllerGetDeletedPosts>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function usePostsControllerGetDeletedPosts<TData = Awaited<ReturnType<typeof postsControllerGetDeletedPosts>>, TError = unknown>(
 boardId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof postsControllerGetDeletedPosts>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function usePostsControllerGetDeletedPosts<TData = Awaited<ReturnType<typeof postsControllerGetDeletedPosts>>, TError = unknown>(
 boardId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof postsControllerGetDeletedPosts>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getPostsControllerGetDeletedPostsQueryOptions(boardId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




