/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * Rawfli API
 * The Rawfli API description
 * OpenAPI spec version: 1.0
 */
import {
  useInfiniteQuery,
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseInfiniteQueryResult,
  DefinedUseQueryResult,
  InfiniteData,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseInfiniteQueryOptions,
  UseInfiniteQueryResult,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  AwsControllerGetImages200,
  AwsControllerUploadFile201,
  AwsControllerUploadFileBody
} from '../../model';

import { customAxiosInstance } from '../../../mutator';




export const awsControllerGetImages = (
    
 signal?: AbortSignal
) => {
      
      
      return customAxiosInstance<AwsControllerGetImages200>(
      {url: `/api/v1/aws/images`, method: 'GET', signal
    },
      );
    }
  



export const getAwsControllerGetImagesInfiniteQueryKey = () => {
    return [
    'infinite', `/api/v1/aws/images`
    ] as const;
    }

export const getAwsControllerGetImagesQueryKey = () => {
    return [
    `/api/v1/aws/images`
    ] as const;
    }

    
export const getAwsControllerGetImagesInfiniteQueryOptions = <TData = InfiniteData<Awaited<ReturnType<typeof awsControllerGetImages>>>, TError = unknown>( options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof awsControllerGetImages>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getAwsControllerGetImagesInfiniteQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof awsControllerGetImages>>> = ({ signal }) => awsControllerGetImages(signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseInfiniteQueryOptions<Awaited<ReturnType<typeof awsControllerGetImages>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type AwsControllerGetImagesInfiniteQueryResult = NonNullable<Awaited<ReturnType<typeof awsControllerGetImages>>>
export type AwsControllerGetImagesInfiniteQueryError = unknown


export function useAwsControllerGetImagesInfinite<TData = InfiniteData<Awaited<ReturnType<typeof awsControllerGetImages>>>, TError = unknown>(
  options: { query:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof awsControllerGetImages>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof awsControllerGetImages>>,
          TError,
          Awaited<ReturnType<typeof awsControllerGetImages>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useAwsControllerGetImagesInfinite<TData = InfiniteData<Awaited<ReturnType<typeof awsControllerGetImages>>>, TError = unknown>(
  options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof awsControllerGetImages>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof awsControllerGetImages>>,
          TError,
          Awaited<ReturnType<typeof awsControllerGetImages>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useAwsControllerGetImagesInfinite<TData = InfiniteData<Awaited<ReturnType<typeof awsControllerGetImages>>>, TError = unknown>(
  options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof awsControllerGetImages>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useAwsControllerGetImagesInfinite<TData = InfiniteData<Awaited<ReturnType<typeof awsControllerGetImages>>>, TError = unknown>(
  options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof awsControllerGetImages>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getAwsControllerGetImagesInfiniteQueryOptions(options)

  const query = useInfiniteQuery(queryOptions, queryClient) as  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




export const getAwsControllerGetImagesQueryOptions = <TData = Awaited<ReturnType<typeof awsControllerGetImages>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof awsControllerGetImages>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getAwsControllerGetImagesQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof awsControllerGetImages>>> = ({ signal }) => awsControllerGetImages(signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof awsControllerGetImages>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type AwsControllerGetImagesQueryResult = NonNullable<Awaited<ReturnType<typeof awsControllerGetImages>>>
export type AwsControllerGetImagesQueryError = unknown


export function useAwsControllerGetImages<TData = Awaited<ReturnType<typeof awsControllerGetImages>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof awsControllerGetImages>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof awsControllerGetImages>>,
          TError,
          Awaited<ReturnType<typeof awsControllerGetImages>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useAwsControllerGetImages<TData = Awaited<ReturnType<typeof awsControllerGetImages>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof awsControllerGetImages>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof awsControllerGetImages>>,
          TError,
          Awaited<ReturnType<typeof awsControllerGetImages>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useAwsControllerGetImages<TData = Awaited<ReturnType<typeof awsControllerGetImages>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof awsControllerGetImages>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useAwsControllerGetImages<TData = Awaited<ReturnType<typeof awsControllerGetImages>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof awsControllerGetImages>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getAwsControllerGetImagesQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




/**
 * @summary 이미지 업로드
 */
export const awsControllerUploadFile = (
    awsControllerUploadFileBody: AwsControllerUploadFileBody,
 signal?: AbortSignal
) => {
      
      const formData = new FormData();
if(awsControllerUploadFileBody.image !== undefined) {
 formData.append(`image`, awsControllerUploadFileBody.image);
 }

      return customAxiosInstance<AwsControllerUploadFile201>(
      {url: `/api/v1/aws/upload`, method: 'POST',
       data: formData, signal
    },
      );
    }
  


export const getAwsControllerUploadFileMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof awsControllerUploadFile>>, TError,{data: AwsControllerUploadFileBody}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof awsControllerUploadFile>>, TError,{data: AwsControllerUploadFileBody}, TContext> => {

const mutationKey = ['awsControllerUploadFile'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof awsControllerUploadFile>>, {data: AwsControllerUploadFileBody}> = (props) => {
          const {data} = props ?? {};

          return  awsControllerUploadFile(data,)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type AwsControllerUploadFileMutationResult = NonNullable<Awaited<ReturnType<typeof awsControllerUploadFile>>>
    export type AwsControllerUploadFileMutationBody = AwsControllerUploadFileBody
    export type AwsControllerUploadFileMutationError = unknown

    /**
 * @summary 이미지 업로드
 */
export const useAwsControllerUploadFile = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof awsControllerUploadFile>>, TError,{data: AwsControllerUploadFileBody}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof awsControllerUploadFile>>,
        TError,
        {data: AwsControllerUploadFileBody},
        TContext
      > => {
      return useMutation(getAwsControllerUploadFileMutationOptions(options), queryClient);
    }
    