/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * Rawfli API
 * The Rawfli API description
 * OpenAPI spec version: 1.0
 */
import {
  useInfiniteQuery,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseInfiniteQueryResult,
  DefinedUseQueryResult,
  InfiniteData,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseInfiniteQueryOptions,
  UseInfiniteQueryResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  BoardResponseDto,
  BoardsControllerSearchInAllBoardsParams,
  BoardsControllerSearchInBoardParams,
  SearchResultsResponseDto
} from '../../model';

import { customAxiosInstance } from '../../../mutator';




/**
 * @summary 게시판 목록 조회
 */
export const boardsControllerGetBoards = (
    
 signal?: AbortSignal
) => {
      
      
      return customAxiosInstance<BoardResponseDto[]>(
      {url: `/api/v1/boards`, method: 'GET', signal
    },
      );
    }
  



export const getBoardsControllerGetBoardsInfiniteQueryKey = () => {
    return [
    'infinite', `/api/v1/boards`
    ] as const;
    }

export const getBoardsControllerGetBoardsQueryKey = () => {
    return [
    `/api/v1/boards`
    ] as const;
    }

    
export const getBoardsControllerGetBoardsInfiniteQueryOptions = <TData = InfiniteData<Awaited<ReturnType<typeof boardsControllerGetBoards>>>, TError = unknown>( options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof boardsControllerGetBoards>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getBoardsControllerGetBoardsInfiniteQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof boardsControllerGetBoards>>> = ({ signal }) => boardsControllerGetBoards(signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseInfiniteQueryOptions<Awaited<ReturnType<typeof boardsControllerGetBoards>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type BoardsControllerGetBoardsInfiniteQueryResult = NonNullable<Awaited<ReturnType<typeof boardsControllerGetBoards>>>
export type BoardsControllerGetBoardsInfiniteQueryError = unknown


export function useBoardsControllerGetBoardsInfinite<TData = InfiniteData<Awaited<ReturnType<typeof boardsControllerGetBoards>>>, TError = unknown>(
  options: { query:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof boardsControllerGetBoards>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof boardsControllerGetBoards>>,
          TError,
          Awaited<ReturnType<typeof boardsControllerGetBoards>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useBoardsControllerGetBoardsInfinite<TData = InfiniteData<Awaited<ReturnType<typeof boardsControllerGetBoards>>>, TError = unknown>(
  options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof boardsControllerGetBoards>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof boardsControllerGetBoards>>,
          TError,
          Awaited<ReturnType<typeof boardsControllerGetBoards>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useBoardsControllerGetBoardsInfinite<TData = InfiniteData<Awaited<ReturnType<typeof boardsControllerGetBoards>>>, TError = unknown>(
  options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof boardsControllerGetBoards>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary 게시판 목록 조회
 */

export function useBoardsControllerGetBoardsInfinite<TData = InfiniteData<Awaited<ReturnType<typeof boardsControllerGetBoards>>>, TError = unknown>(
  options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof boardsControllerGetBoards>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getBoardsControllerGetBoardsInfiniteQueryOptions(options)

  const query = useInfiniteQuery(queryOptions, queryClient) as  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




export const getBoardsControllerGetBoardsQueryOptions = <TData = Awaited<ReturnType<typeof boardsControllerGetBoards>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof boardsControllerGetBoards>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getBoardsControllerGetBoardsQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof boardsControllerGetBoards>>> = ({ signal }) => boardsControllerGetBoards(signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof boardsControllerGetBoards>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type BoardsControllerGetBoardsQueryResult = NonNullable<Awaited<ReturnType<typeof boardsControllerGetBoards>>>
export type BoardsControllerGetBoardsQueryError = unknown


export function useBoardsControllerGetBoards<TData = Awaited<ReturnType<typeof boardsControllerGetBoards>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof boardsControllerGetBoards>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof boardsControllerGetBoards>>,
          TError,
          Awaited<ReturnType<typeof boardsControllerGetBoards>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useBoardsControllerGetBoards<TData = Awaited<ReturnType<typeof boardsControllerGetBoards>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof boardsControllerGetBoards>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof boardsControllerGetBoards>>,
          TError,
          Awaited<ReturnType<typeof boardsControllerGetBoards>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useBoardsControllerGetBoards<TData = Awaited<ReturnType<typeof boardsControllerGetBoards>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof boardsControllerGetBoards>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary 게시판 목록 조회
 */

export function useBoardsControllerGetBoards<TData = Awaited<ReturnType<typeof boardsControllerGetBoards>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof boardsControllerGetBoards>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getBoardsControllerGetBoardsQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




/**
 * @summary 전체 게시글 검색
 */
export const boardsControllerSearchInAllBoards = (
    params: BoardsControllerSearchInAllBoardsParams,
 signal?: AbortSignal
) => {
      
      
      return customAxiosInstance<SearchResultsResponseDto>(
      {url: `/api/v1/boards/search`, method: 'GET',
        params, signal
    },
      );
    }
  



export const getBoardsControllerSearchInAllBoardsInfiniteQueryKey = (params?: BoardsControllerSearchInAllBoardsParams,) => {
    return [
    'infinite', `/api/v1/boards/search`, ...(params ? [params] : [])
    ] as const;
    }

export const getBoardsControllerSearchInAllBoardsQueryKey = (params?: BoardsControllerSearchInAllBoardsParams,) => {
    return [
    `/api/v1/boards/search`, ...(params ? [params] : [])
    ] as const;
    }

    
export const getBoardsControllerSearchInAllBoardsInfiniteQueryOptions = <TData = InfiniteData<Awaited<ReturnType<typeof boardsControllerSearchInAllBoards>>>, TError = unknown>(params: BoardsControllerSearchInAllBoardsParams, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof boardsControllerSearchInAllBoards>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getBoardsControllerSearchInAllBoardsInfiniteQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof boardsControllerSearchInAllBoards>>> = ({ signal }) => boardsControllerSearchInAllBoards(params, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseInfiniteQueryOptions<Awaited<ReturnType<typeof boardsControllerSearchInAllBoards>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type BoardsControllerSearchInAllBoardsInfiniteQueryResult = NonNullable<Awaited<ReturnType<typeof boardsControllerSearchInAllBoards>>>
export type BoardsControllerSearchInAllBoardsInfiniteQueryError = unknown


export function useBoardsControllerSearchInAllBoardsInfinite<TData = InfiniteData<Awaited<ReturnType<typeof boardsControllerSearchInAllBoards>>>, TError = unknown>(
 params: BoardsControllerSearchInAllBoardsParams, options: { query:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof boardsControllerSearchInAllBoards>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof boardsControllerSearchInAllBoards>>,
          TError,
          Awaited<ReturnType<typeof boardsControllerSearchInAllBoards>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useBoardsControllerSearchInAllBoardsInfinite<TData = InfiniteData<Awaited<ReturnType<typeof boardsControllerSearchInAllBoards>>>, TError = unknown>(
 params: BoardsControllerSearchInAllBoardsParams, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof boardsControllerSearchInAllBoards>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof boardsControllerSearchInAllBoards>>,
          TError,
          Awaited<ReturnType<typeof boardsControllerSearchInAllBoards>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useBoardsControllerSearchInAllBoardsInfinite<TData = InfiniteData<Awaited<ReturnType<typeof boardsControllerSearchInAllBoards>>>, TError = unknown>(
 params: BoardsControllerSearchInAllBoardsParams, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof boardsControllerSearchInAllBoards>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary 전체 게시글 검색
 */

export function useBoardsControllerSearchInAllBoardsInfinite<TData = InfiniteData<Awaited<ReturnType<typeof boardsControllerSearchInAllBoards>>>, TError = unknown>(
 params: BoardsControllerSearchInAllBoardsParams, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof boardsControllerSearchInAllBoards>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getBoardsControllerSearchInAllBoardsInfiniteQueryOptions(params,options)

  const query = useInfiniteQuery(queryOptions, queryClient) as  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




export const getBoardsControllerSearchInAllBoardsQueryOptions = <TData = Awaited<ReturnType<typeof boardsControllerSearchInAllBoards>>, TError = unknown>(params: BoardsControllerSearchInAllBoardsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof boardsControllerSearchInAllBoards>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getBoardsControllerSearchInAllBoardsQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof boardsControllerSearchInAllBoards>>> = ({ signal }) => boardsControllerSearchInAllBoards(params, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof boardsControllerSearchInAllBoards>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type BoardsControllerSearchInAllBoardsQueryResult = NonNullable<Awaited<ReturnType<typeof boardsControllerSearchInAllBoards>>>
export type BoardsControllerSearchInAllBoardsQueryError = unknown


export function useBoardsControllerSearchInAllBoards<TData = Awaited<ReturnType<typeof boardsControllerSearchInAllBoards>>, TError = unknown>(
 params: BoardsControllerSearchInAllBoardsParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof boardsControllerSearchInAllBoards>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof boardsControllerSearchInAllBoards>>,
          TError,
          Awaited<ReturnType<typeof boardsControllerSearchInAllBoards>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useBoardsControllerSearchInAllBoards<TData = Awaited<ReturnType<typeof boardsControllerSearchInAllBoards>>, TError = unknown>(
 params: BoardsControllerSearchInAllBoardsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof boardsControllerSearchInAllBoards>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof boardsControllerSearchInAllBoards>>,
          TError,
          Awaited<ReturnType<typeof boardsControllerSearchInAllBoards>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useBoardsControllerSearchInAllBoards<TData = Awaited<ReturnType<typeof boardsControllerSearchInAllBoards>>, TError = unknown>(
 params: BoardsControllerSearchInAllBoardsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof boardsControllerSearchInAllBoards>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary 전체 게시글 검색
 */

export function useBoardsControllerSearchInAllBoards<TData = Awaited<ReturnType<typeof boardsControllerSearchInAllBoards>>, TError = unknown>(
 params: BoardsControllerSearchInAllBoardsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof boardsControllerSearchInAllBoards>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getBoardsControllerSearchInAllBoardsQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




/**
 * @summary 게시판 조회
 */
export const boardsControllerGetBoard = (
    boardId: number,
 signal?: AbortSignal
) => {
      
      
      return customAxiosInstance<BoardResponseDto>(
      {url: `/api/v1/boards/${boardId}`, method: 'GET', signal
    },
      );
    }
  



export const getBoardsControllerGetBoardInfiniteQueryKey = (boardId: number,) => {
    return [
    'infinite', `/api/v1/boards/${boardId}`
    ] as const;
    }

export const getBoardsControllerGetBoardQueryKey = (boardId: number,) => {
    return [
    `/api/v1/boards/${boardId}`
    ] as const;
    }

    
export const getBoardsControllerGetBoardInfiniteQueryOptions = <TData = InfiniteData<Awaited<ReturnType<typeof boardsControllerGetBoard>>>, TError = unknown>(boardId: number, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof boardsControllerGetBoard>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getBoardsControllerGetBoardInfiniteQueryKey(boardId);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof boardsControllerGetBoard>>> = ({ signal }) => boardsControllerGetBoard(boardId, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(boardId), ...queryOptions} as UseInfiniteQueryOptions<Awaited<ReturnType<typeof boardsControllerGetBoard>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type BoardsControllerGetBoardInfiniteQueryResult = NonNullable<Awaited<ReturnType<typeof boardsControllerGetBoard>>>
export type BoardsControllerGetBoardInfiniteQueryError = unknown


export function useBoardsControllerGetBoardInfinite<TData = InfiniteData<Awaited<ReturnType<typeof boardsControllerGetBoard>>>, TError = unknown>(
 boardId: number, options: { query:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof boardsControllerGetBoard>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof boardsControllerGetBoard>>,
          TError,
          Awaited<ReturnType<typeof boardsControllerGetBoard>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useBoardsControllerGetBoardInfinite<TData = InfiniteData<Awaited<ReturnType<typeof boardsControllerGetBoard>>>, TError = unknown>(
 boardId: number, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof boardsControllerGetBoard>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof boardsControllerGetBoard>>,
          TError,
          Awaited<ReturnType<typeof boardsControllerGetBoard>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useBoardsControllerGetBoardInfinite<TData = InfiniteData<Awaited<ReturnType<typeof boardsControllerGetBoard>>>, TError = unknown>(
 boardId: number, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof boardsControllerGetBoard>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary 게시판 조회
 */

export function useBoardsControllerGetBoardInfinite<TData = InfiniteData<Awaited<ReturnType<typeof boardsControllerGetBoard>>>, TError = unknown>(
 boardId: number, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof boardsControllerGetBoard>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getBoardsControllerGetBoardInfiniteQueryOptions(boardId,options)

  const query = useInfiniteQuery(queryOptions, queryClient) as  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




export const getBoardsControllerGetBoardQueryOptions = <TData = Awaited<ReturnType<typeof boardsControllerGetBoard>>, TError = unknown>(boardId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof boardsControllerGetBoard>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getBoardsControllerGetBoardQueryKey(boardId);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof boardsControllerGetBoard>>> = ({ signal }) => boardsControllerGetBoard(boardId, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(boardId), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof boardsControllerGetBoard>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type BoardsControllerGetBoardQueryResult = NonNullable<Awaited<ReturnType<typeof boardsControllerGetBoard>>>
export type BoardsControllerGetBoardQueryError = unknown


export function useBoardsControllerGetBoard<TData = Awaited<ReturnType<typeof boardsControllerGetBoard>>, TError = unknown>(
 boardId: number, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof boardsControllerGetBoard>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof boardsControllerGetBoard>>,
          TError,
          Awaited<ReturnType<typeof boardsControllerGetBoard>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useBoardsControllerGetBoard<TData = Awaited<ReturnType<typeof boardsControllerGetBoard>>, TError = unknown>(
 boardId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof boardsControllerGetBoard>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof boardsControllerGetBoard>>,
          TError,
          Awaited<ReturnType<typeof boardsControllerGetBoard>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useBoardsControllerGetBoard<TData = Awaited<ReturnType<typeof boardsControllerGetBoard>>, TError = unknown>(
 boardId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof boardsControllerGetBoard>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary 게시판 조회
 */

export function useBoardsControllerGetBoard<TData = Awaited<ReturnType<typeof boardsControllerGetBoard>>, TError = unknown>(
 boardId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof boardsControllerGetBoard>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getBoardsControllerGetBoardQueryOptions(boardId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




/**
 * @summary 게시판 내 게시글 검색
 */
export const boardsControllerSearchInBoard = (
    boardId: number,
    params: BoardsControllerSearchInBoardParams,
 signal?: AbortSignal
) => {
      
      
      return customAxiosInstance<SearchResultsResponseDto>(
      {url: `/api/v1/boards/${boardId}/search`, method: 'GET',
        params, signal
    },
      );
    }
  



export const getBoardsControllerSearchInBoardInfiniteQueryKey = (boardId: number,
    params?: BoardsControllerSearchInBoardParams,) => {
    return [
    'infinite', `/api/v1/boards/${boardId}/search`, ...(params ? [params] : [])
    ] as const;
    }

export const getBoardsControllerSearchInBoardQueryKey = (boardId: number,
    params?: BoardsControllerSearchInBoardParams,) => {
    return [
    `/api/v1/boards/${boardId}/search`, ...(params ? [params] : [])
    ] as const;
    }

    
export const getBoardsControllerSearchInBoardInfiniteQueryOptions = <TData = InfiniteData<Awaited<ReturnType<typeof boardsControllerSearchInBoard>>>, TError = unknown>(boardId: number,
    params: BoardsControllerSearchInBoardParams, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof boardsControllerSearchInBoard>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getBoardsControllerSearchInBoardInfiniteQueryKey(boardId,params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof boardsControllerSearchInBoard>>> = ({ signal }) => boardsControllerSearchInBoard(boardId,params, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(boardId), ...queryOptions} as UseInfiniteQueryOptions<Awaited<ReturnType<typeof boardsControllerSearchInBoard>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type BoardsControllerSearchInBoardInfiniteQueryResult = NonNullable<Awaited<ReturnType<typeof boardsControllerSearchInBoard>>>
export type BoardsControllerSearchInBoardInfiniteQueryError = unknown


export function useBoardsControllerSearchInBoardInfinite<TData = InfiniteData<Awaited<ReturnType<typeof boardsControllerSearchInBoard>>>, TError = unknown>(
 boardId: number,
    params: BoardsControllerSearchInBoardParams, options: { query:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof boardsControllerSearchInBoard>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof boardsControllerSearchInBoard>>,
          TError,
          Awaited<ReturnType<typeof boardsControllerSearchInBoard>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useBoardsControllerSearchInBoardInfinite<TData = InfiniteData<Awaited<ReturnType<typeof boardsControllerSearchInBoard>>>, TError = unknown>(
 boardId: number,
    params: BoardsControllerSearchInBoardParams, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof boardsControllerSearchInBoard>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof boardsControllerSearchInBoard>>,
          TError,
          Awaited<ReturnType<typeof boardsControllerSearchInBoard>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useBoardsControllerSearchInBoardInfinite<TData = InfiniteData<Awaited<ReturnType<typeof boardsControllerSearchInBoard>>>, TError = unknown>(
 boardId: number,
    params: BoardsControllerSearchInBoardParams, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof boardsControllerSearchInBoard>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary 게시판 내 게시글 검색
 */

export function useBoardsControllerSearchInBoardInfinite<TData = InfiniteData<Awaited<ReturnType<typeof boardsControllerSearchInBoard>>>, TError = unknown>(
 boardId: number,
    params: BoardsControllerSearchInBoardParams, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof boardsControllerSearchInBoard>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getBoardsControllerSearchInBoardInfiniteQueryOptions(boardId,params,options)

  const query = useInfiniteQuery(queryOptions, queryClient) as  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




export const getBoardsControllerSearchInBoardQueryOptions = <TData = Awaited<ReturnType<typeof boardsControllerSearchInBoard>>, TError = unknown>(boardId: number,
    params: BoardsControllerSearchInBoardParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof boardsControllerSearchInBoard>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getBoardsControllerSearchInBoardQueryKey(boardId,params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof boardsControllerSearchInBoard>>> = ({ signal }) => boardsControllerSearchInBoard(boardId,params, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(boardId), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof boardsControllerSearchInBoard>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type BoardsControllerSearchInBoardQueryResult = NonNullable<Awaited<ReturnType<typeof boardsControllerSearchInBoard>>>
export type BoardsControllerSearchInBoardQueryError = unknown


export function useBoardsControllerSearchInBoard<TData = Awaited<ReturnType<typeof boardsControllerSearchInBoard>>, TError = unknown>(
 boardId: number,
    params: BoardsControllerSearchInBoardParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof boardsControllerSearchInBoard>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof boardsControllerSearchInBoard>>,
          TError,
          Awaited<ReturnType<typeof boardsControllerSearchInBoard>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useBoardsControllerSearchInBoard<TData = Awaited<ReturnType<typeof boardsControllerSearchInBoard>>, TError = unknown>(
 boardId: number,
    params: BoardsControllerSearchInBoardParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof boardsControllerSearchInBoard>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof boardsControllerSearchInBoard>>,
          TError,
          Awaited<ReturnType<typeof boardsControllerSearchInBoard>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useBoardsControllerSearchInBoard<TData = Awaited<ReturnType<typeof boardsControllerSearchInBoard>>, TError = unknown>(
 boardId: number,
    params: BoardsControllerSearchInBoardParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof boardsControllerSearchInBoard>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary 게시판 내 게시글 검색
 */

export function useBoardsControllerSearchInBoard<TData = Awaited<ReturnType<typeof boardsControllerSearchInBoard>>, TError = unknown>(
 boardId: number,
    params: BoardsControllerSearchInBoardParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof boardsControllerSearchInBoard>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getBoardsControllerSearchInBoardQueryOptions(boardId,params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




