/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * Rawfli API
 * The Rawfli API description
 * OpenAPI spec version: 1.0
 */
import {
  useInfiniteQuery,
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseInfiniteQueryResult,
  DefinedUseQueryResult,
  InfiniteData,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseInfiniteQueryOptions,
  UseInfiniteQueryResult,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  MeResponseDtoResponse,
  UpdatePasswordDto,
  UpdateProfileDto
} from '../../model';

import { customAxiosInstance } from '../../../mutator';




/**
 * @summary 내 정보 조회
 */
export const meControllerGetMe = (
    
 signal?: AbortSignal
) => {
      
      
      return customAxiosInstance<MeResponseDtoResponse>(
      {url: `/api/v1/me`, method: 'GET', signal
    },
      );
    }
  



export const getMeControllerGetMeInfiniteQueryKey = () => {
    return [
    'infinite', `/api/v1/me`
    ] as const;
    }

export const getMeControllerGetMeQueryKey = () => {
    return [
    `/api/v1/me`
    ] as const;
    }

    
export const getMeControllerGetMeInfiniteQueryOptions = <TData = InfiniteData<Awaited<ReturnType<typeof meControllerGetMe>>>, TError = unknown>( options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof meControllerGetMe>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getMeControllerGetMeInfiniteQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof meControllerGetMe>>> = ({ signal }) => meControllerGetMe(signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseInfiniteQueryOptions<Awaited<ReturnType<typeof meControllerGetMe>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type MeControllerGetMeInfiniteQueryResult = NonNullable<Awaited<ReturnType<typeof meControllerGetMe>>>
export type MeControllerGetMeInfiniteQueryError = unknown


export function useMeControllerGetMeInfinite<TData = InfiniteData<Awaited<ReturnType<typeof meControllerGetMe>>>, TError = unknown>(
  options: { query:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof meControllerGetMe>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof meControllerGetMe>>,
          TError,
          Awaited<ReturnType<typeof meControllerGetMe>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useMeControllerGetMeInfinite<TData = InfiniteData<Awaited<ReturnType<typeof meControllerGetMe>>>, TError = unknown>(
  options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof meControllerGetMe>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof meControllerGetMe>>,
          TError,
          Awaited<ReturnType<typeof meControllerGetMe>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useMeControllerGetMeInfinite<TData = InfiniteData<Awaited<ReturnType<typeof meControllerGetMe>>>, TError = unknown>(
  options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof meControllerGetMe>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary 내 정보 조회
 */

export function useMeControllerGetMeInfinite<TData = InfiniteData<Awaited<ReturnType<typeof meControllerGetMe>>>, TError = unknown>(
  options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof meControllerGetMe>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getMeControllerGetMeInfiniteQueryOptions(options)

  const query = useInfiniteQuery(queryOptions, queryClient) as  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




export const getMeControllerGetMeQueryOptions = <TData = Awaited<ReturnType<typeof meControllerGetMe>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof meControllerGetMe>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getMeControllerGetMeQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof meControllerGetMe>>> = ({ signal }) => meControllerGetMe(signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof meControllerGetMe>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type MeControllerGetMeQueryResult = NonNullable<Awaited<ReturnType<typeof meControllerGetMe>>>
export type MeControllerGetMeQueryError = unknown


export function useMeControllerGetMe<TData = Awaited<ReturnType<typeof meControllerGetMe>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof meControllerGetMe>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof meControllerGetMe>>,
          TError,
          Awaited<ReturnType<typeof meControllerGetMe>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useMeControllerGetMe<TData = Awaited<ReturnType<typeof meControllerGetMe>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof meControllerGetMe>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof meControllerGetMe>>,
          TError,
          Awaited<ReturnType<typeof meControllerGetMe>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useMeControllerGetMe<TData = Awaited<ReturnType<typeof meControllerGetMe>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof meControllerGetMe>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary 내 정보 조회
 */

export function useMeControllerGetMe<TData = Awaited<ReturnType<typeof meControllerGetMe>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof meControllerGetMe>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getMeControllerGetMeQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




/**
 * @summary 프로필 수정
 */
export const meControllerUpdateProfile = (
    updateProfileDto: UpdateProfileDto,
 signal?: AbortSignal
) => {
      
      
      return customAxiosInstance<MeResponseDtoResponse>(
      {url: `/api/v1/me/profile`, method: 'PATCH',
      headers: {'Content-Type': 'application/json', },
      data: updateProfileDto, signal
    },
      );
    }
  


export const getMeControllerUpdateProfileMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof meControllerUpdateProfile>>, TError,{data: UpdateProfileDto}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof meControllerUpdateProfile>>, TError,{data: UpdateProfileDto}, TContext> => {

const mutationKey = ['meControllerUpdateProfile'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof meControllerUpdateProfile>>, {data: UpdateProfileDto}> = (props) => {
          const {data} = props ?? {};

          return  meControllerUpdateProfile(data,)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type MeControllerUpdateProfileMutationResult = NonNullable<Awaited<ReturnType<typeof meControllerUpdateProfile>>>
    export type MeControllerUpdateProfileMutationBody = UpdateProfileDto
    export type MeControllerUpdateProfileMutationError = unknown

    /**
 * @summary 프로필 수정
 */
export const useMeControllerUpdateProfile = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof meControllerUpdateProfile>>, TError,{data: UpdateProfileDto}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof meControllerUpdateProfile>>,
        TError,
        {data: UpdateProfileDto},
        TContext
      > => {
      return useMutation(getMeControllerUpdateProfileMutationOptions(options), queryClient);
    }
    /**
 * @summary 비밀번호 변경
 */
export const meControllerUpdatePassword = (
    updatePasswordDto: UpdatePasswordDto,
 signal?: AbortSignal
) => {
      
      
      return customAxiosInstance<void>(
      {url: `/api/v1/me/password`, method: 'PATCH',
      headers: {'Content-Type': 'application/json', },
      data: updatePasswordDto, signal
    },
      );
    }
  


export const getMeControllerUpdatePasswordMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof meControllerUpdatePassword>>, TError,{data: UpdatePasswordDto}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof meControllerUpdatePassword>>, TError,{data: UpdatePasswordDto}, TContext> => {

const mutationKey = ['meControllerUpdatePassword'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof meControllerUpdatePassword>>, {data: UpdatePasswordDto}> = (props) => {
          const {data} = props ?? {};

          return  meControllerUpdatePassword(data,)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type MeControllerUpdatePasswordMutationResult = NonNullable<Awaited<ReturnType<typeof meControllerUpdatePassword>>>
    export type MeControllerUpdatePasswordMutationBody = UpdatePasswordDto
    export type MeControllerUpdatePasswordMutationError = unknown

    /**
 * @summary 비밀번호 변경
 */
export const useMeControllerUpdatePassword = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof meControllerUpdatePassword>>, TError,{data: UpdatePasswordDto}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof meControllerUpdatePassword>>,
        TError,
        {data: UpdatePasswordDto},
        TContext
      > => {
      return useMutation(getMeControllerUpdatePasswordMutationOptions(options), queryClient);
    }
    