/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * Rawfli API
 * The Rawfli API description
 * OpenAPI spec version: 1.0
 */
import {
  useInfiniteQuery,
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseInfiniteQueryResult,
  DefinedUseQueryResult,
  InfiniteData,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseInfiniteQueryOptions,
  UseInfiniteQueryResult,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  ArticleControllerGetArticlesParams,
  ArticleControllerGetPopularArticlesParams,
  ArticleControllerToggleLike201,
  ArticleListResponseDto,
  ArticleResponseDto,
  CommentResponseDto,
  CreateArticleDto,
  CreateCommentDto,
  DeletedArticleResponseDto,
  DeletedCommentResponseDto,
  LikeArticleResponseDto
} from '../../model';

import { customAxiosInstance } from '../../../mutator';




/**
 * @summary 게시글 목록 조회
 */
export const articleControllerGetArticles = (
    boardId: number,
    params?: ArticleControllerGetArticlesParams,
 signal?: AbortSignal
) => {
      
      
      return customAxiosInstance<ArticleListResponseDto>(
      {url: `/api/v1/boards/${boardId}/articles`, method: 'GET',
        params, signal
    },
      );
    }
  



export const getArticleControllerGetArticlesInfiniteQueryKey = (boardId: number,
    params?: ArticleControllerGetArticlesParams,) => {
    return [
    'infinite', `/api/v1/boards/${boardId}/articles`, ...(params ? [params] : [])
    ] as const;
    }

export const getArticleControllerGetArticlesQueryKey = (boardId: number,
    params?: ArticleControllerGetArticlesParams,) => {
    return [
    `/api/v1/boards/${boardId}/articles`, ...(params ? [params] : [])
    ] as const;
    }

    
export const getArticleControllerGetArticlesInfiniteQueryOptions = <TData = InfiniteData<Awaited<ReturnType<typeof articleControllerGetArticles>>>, TError = unknown>(boardId: number,
    params?: ArticleControllerGetArticlesParams, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof articleControllerGetArticles>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getArticleControllerGetArticlesInfiniteQueryKey(boardId,params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof articleControllerGetArticles>>> = ({ signal }) => articleControllerGetArticles(boardId,params, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(boardId), ...queryOptions} as UseInfiniteQueryOptions<Awaited<ReturnType<typeof articleControllerGetArticles>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ArticleControllerGetArticlesInfiniteQueryResult = NonNullable<Awaited<ReturnType<typeof articleControllerGetArticles>>>
export type ArticleControllerGetArticlesInfiniteQueryError = unknown


export function useArticleControllerGetArticlesInfinite<TData = InfiniteData<Awaited<ReturnType<typeof articleControllerGetArticles>>>, TError = unknown>(
 boardId: number,
    params: undefined |  ArticleControllerGetArticlesParams, options: { query:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof articleControllerGetArticles>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof articleControllerGetArticles>>,
          TError,
          Awaited<ReturnType<typeof articleControllerGetArticles>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useArticleControllerGetArticlesInfinite<TData = InfiniteData<Awaited<ReturnType<typeof articleControllerGetArticles>>>, TError = unknown>(
 boardId: number,
    params?: ArticleControllerGetArticlesParams, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof articleControllerGetArticles>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof articleControllerGetArticles>>,
          TError,
          Awaited<ReturnType<typeof articleControllerGetArticles>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useArticleControllerGetArticlesInfinite<TData = InfiniteData<Awaited<ReturnType<typeof articleControllerGetArticles>>>, TError = unknown>(
 boardId: number,
    params?: ArticleControllerGetArticlesParams, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof articleControllerGetArticles>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary 게시글 목록 조회
 */

export function useArticleControllerGetArticlesInfinite<TData = InfiniteData<Awaited<ReturnType<typeof articleControllerGetArticles>>>, TError = unknown>(
 boardId: number,
    params?: ArticleControllerGetArticlesParams, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof articleControllerGetArticles>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getArticleControllerGetArticlesInfiniteQueryOptions(boardId,params,options)

  const query = useInfiniteQuery(queryOptions, queryClient) as  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




export const getArticleControllerGetArticlesQueryOptions = <TData = Awaited<ReturnType<typeof articleControllerGetArticles>>, TError = unknown>(boardId: number,
    params?: ArticleControllerGetArticlesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof articleControllerGetArticles>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getArticleControllerGetArticlesQueryKey(boardId,params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof articleControllerGetArticles>>> = ({ signal }) => articleControllerGetArticles(boardId,params, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(boardId), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof articleControllerGetArticles>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ArticleControllerGetArticlesQueryResult = NonNullable<Awaited<ReturnType<typeof articleControllerGetArticles>>>
export type ArticleControllerGetArticlesQueryError = unknown


export function useArticleControllerGetArticles<TData = Awaited<ReturnType<typeof articleControllerGetArticles>>, TError = unknown>(
 boardId: number,
    params: undefined |  ArticleControllerGetArticlesParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof articleControllerGetArticles>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof articleControllerGetArticles>>,
          TError,
          Awaited<ReturnType<typeof articleControllerGetArticles>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useArticleControllerGetArticles<TData = Awaited<ReturnType<typeof articleControllerGetArticles>>, TError = unknown>(
 boardId: number,
    params?: ArticleControllerGetArticlesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof articleControllerGetArticles>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof articleControllerGetArticles>>,
          TError,
          Awaited<ReturnType<typeof articleControllerGetArticles>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useArticleControllerGetArticles<TData = Awaited<ReturnType<typeof articleControllerGetArticles>>, TError = unknown>(
 boardId: number,
    params?: ArticleControllerGetArticlesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof articleControllerGetArticles>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary 게시글 목록 조회
 */

export function useArticleControllerGetArticles<TData = Awaited<ReturnType<typeof articleControllerGetArticles>>, TError = unknown>(
 boardId: number,
    params?: ArticleControllerGetArticlesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof articleControllerGetArticles>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getArticleControllerGetArticlesQueryOptions(boardId,params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




/**
 * @summary 게시글 작성
 */
export const articleControllerCreateArticle = (
    boardId: number,
    createArticleDto: CreateArticleDto,
 signal?: AbortSignal
) => {
      
      
      return customAxiosInstance<ArticleResponseDto>(
      {url: `/api/v1/boards/${boardId}/articles`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: createArticleDto, signal
    },
      );
    }
  


export const getArticleControllerCreateArticleMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof articleControllerCreateArticle>>, TError,{boardId: number;data: CreateArticleDto}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof articleControllerCreateArticle>>, TError,{boardId: number;data: CreateArticleDto}, TContext> => {

const mutationKey = ['articleControllerCreateArticle'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof articleControllerCreateArticle>>, {boardId: number;data: CreateArticleDto}> = (props) => {
          const {boardId,data} = props ?? {};

          return  articleControllerCreateArticle(boardId,data,)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type ArticleControllerCreateArticleMutationResult = NonNullable<Awaited<ReturnType<typeof articleControllerCreateArticle>>>
    export type ArticleControllerCreateArticleMutationBody = CreateArticleDto
    export type ArticleControllerCreateArticleMutationError = unknown

    /**
 * @summary 게시글 작성
 */
export const useArticleControllerCreateArticle = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof articleControllerCreateArticle>>, TError,{boardId: number;data: CreateArticleDto}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof articleControllerCreateArticle>>,
        TError,
        {boardId: number;data: CreateArticleDto},
        TContext
      > => {
      return useMutation(getArticleControllerCreateArticleMutationOptions(options), queryClient);
    }
    /**
 * @summary 인기 게시글 목록 조회
 */
export const articleControllerGetPopularArticles = (
    boardId: number,
    params?: ArticleControllerGetPopularArticlesParams,
 signal?: AbortSignal
) => {
      
      
      return customAxiosInstance<ArticleListResponseDto>(
      {url: `/api/v1/boards/${boardId}/articles/popular`, method: 'GET',
        params, signal
    },
      );
    }
  



export const getArticleControllerGetPopularArticlesInfiniteQueryKey = (boardId: number,
    params?: ArticleControllerGetPopularArticlesParams,) => {
    return [
    'infinite', `/api/v1/boards/${boardId}/articles/popular`, ...(params ? [params] : [])
    ] as const;
    }

export const getArticleControllerGetPopularArticlesQueryKey = (boardId: number,
    params?: ArticleControllerGetPopularArticlesParams,) => {
    return [
    `/api/v1/boards/${boardId}/articles/popular`, ...(params ? [params] : [])
    ] as const;
    }

    
export const getArticleControllerGetPopularArticlesInfiniteQueryOptions = <TData = InfiniteData<Awaited<ReturnType<typeof articleControllerGetPopularArticles>>>, TError = unknown>(boardId: number,
    params?: ArticleControllerGetPopularArticlesParams, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof articleControllerGetPopularArticles>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getArticleControllerGetPopularArticlesInfiniteQueryKey(boardId,params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof articleControllerGetPopularArticles>>> = ({ signal }) => articleControllerGetPopularArticles(boardId,params, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(boardId), ...queryOptions} as UseInfiniteQueryOptions<Awaited<ReturnType<typeof articleControllerGetPopularArticles>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ArticleControllerGetPopularArticlesInfiniteQueryResult = NonNullable<Awaited<ReturnType<typeof articleControllerGetPopularArticles>>>
export type ArticleControllerGetPopularArticlesInfiniteQueryError = unknown


export function useArticleControllerGetPopularArticlesInfinite<TData = InfiniteData<Awaited<ReturnType<typeof articleControllerGetPopularArticles>>>, TError = unknown>(
 boardId: number,
    params: undefined |  ArticleControllerGetPopularArticlesParams, options: { query:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof articleControllerGetPopularArticles>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof articleControllerGetPopularArticles>>,
          TError,
          Awaited<ReturnType<typeof articleControllerGetPopularArticles>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useArticleControllerGetPopularArticlesInfinite<TData = InfiniteData<Awaited<ReturnType<typeof articleControllerGetPopularArticles>>>, TError = unknown>(
 boardId: number,
    params?: ArticleControllerGetPopularArticlesParams, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof articleControllerGetPopularArticles>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof articleControllerGetPopularArticles>>,
          TError,
          Awaited<ReturnType<typeof articleControllerGetPopularArticles>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useArticleControllerGetPopularArticlesInfinite<TData = InfiniteData<Awaited<ReturnType<typeof articleControllerGetPopularArticles>>>, TError = unknown>(
 boardId: number,
    params?: ArticleControllerGetPopularArticlesParams, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof articleControllerGetPopularArticles>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary 인기 게시글 목록 조회
 */

export function useArticleControllerGetPopularArticlesInfinite<TData = InfiniteData<Awaited<ReturnType<typeof articleControllerGetPopularArticles>>>, TError = unknown>(
 boardId: number,
    params?: ArticleControllerGetPopularArticlesParams, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof articleControllerGetPopularArticles>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getArticleControllerGetPopularArticlesInfiniteQueryOptions(boardId,params,options)

  const query = useInfiniteQuery(queryOptions, queryClient) as  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




export const getArticleControllerGetPopularArticlesQueryOptions = <TData = Awaited<ReturnType<typeof articleControllerGetPopularArticles>>, TError = unknown>(boardId: number,
    params?: ArticleControllerGetPopularArticlesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof articleControllerGetPopularArticles>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getArticleControllerGetPopularArticlesQueryKey(boardId,params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof articleControllerGetPopularArticles>>> = ({ signal }) => articleControllerGetPopularArticles(boardId,params, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(boardId), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof articleControllerGetPopularArticles>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ArticleControllerGetPopularArticlesQueryResult = NonNullable<Awaited<ReturnType<typeof articleControllerGetPopularArticles>>>
export type ArticleControllerGetPopularArticlesQueryError = unknown


export function useArticleControllerGetPopularArticles<TData = Awaited<ReturnType<typeof articleControllerGetPopularArticles>>, TError = unknown>(
 boardId: number,
    params: undefined |  ArticleControllerGetPopularArticlesParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof articleControllerGetPopularArticles>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof articleControllerGetPopularArticles>>,
          TError,
          Awaited<ReturnType<typeof articleControllerGetPopularArticles>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useArticleControllerGetPopularArticles<TData = Awaited<ReturnType<typeof articleControllerGetPopularArticles>>, TError = unknown>(
 boardId: number,
    params?: ArticleControllerGetPopularArticlesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof articleControllerGetPopularArticles>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof articleControllerGetPopularArticles>>,
          TError,
          Awaited<ReturnType<typeof articleControllerGetPopularArticles>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useArticleControllerGetPopularArticles<TData = Awaited<ReturnType<typeof articleControllerGetPopularArticles>>, TError = unknown>(
 boardId: number,
    params?: ArticleControllerGetPopularArticlesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof articleControllerGetPopularArticles>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary 인기 게시글 목록 조회
 */

export function useArticleControllerGetPopularArticles<TData = Awaited<ReturnType<typeof articleControllerGetPopularArticles>>, TError = unknown>(
 boardId: number,
    params?: ArticleControllerGetPopularArticlesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof articleControllerGetPopularArticles>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getArticleControllerGetPopularArticlesQueryOptions(boardId,params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




/**
 * @summary 게시글 조회
 */
export const articleControllerGetArticle = (
    boardId: number,
    articleId: number,
 signal?: AbortSignal
) => {
      
      
      return customAxiosInstance<ArticleResponseDto>(
      {url: `/api/v1/boards/${boardId}/articles/${articleId}`, method: 'GET', signal
    },
      );
    }
  



export const getArticleControllerGetArticleInfiniteQueryKey = (boardId: number,
    articleId: number,) => {
    return [
    'infinite', `/api/v1/boards/${boardId}/articles/${articleId}`
    ] as const;
    }

export const getArticleControllerGetArticleQueryKey = (boardId: number,
    articleId: number,) => {
    return [
    `/api/v1/boards/${boardId}/articles/${articleId}`
    ] as const;
    }

    
export const getArticleControllerGetArticleInfiniteQueryOptions = <TData = InfiniteData<Awaited<ReturnType<typeof articleControllerGetArticle>>>, TError = unknown>(boardId: number,
    articleId: number, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof articleControllerGetArticle>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getArticleControllerGetArticleInfiniteQueryKey(boardId,articleId);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof articleControllerGetArticle>>> = ({ signal }) => articleControllerGetArticle(boardId,articleId, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(boardId && articleId), ...queryOptions} as UseInfiniteQueryOptions<Awaited<ReturnType<typeof articleControllerGetArticle>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ArticleControllerGetArticleInfiniteQueryResult = NonNullable<Awaited<ReturnType<typeof articleControllerGetArticle>>>
export type ArticleControllerGetArticleInfiniteQueryError = unknown


export function useArticleControllerGetArticleInfinite<TData = InfiniteData<Awaited<ReturnType<typeof articleControllerGetArticle>>>, TError = unknown>(
 boardId: number,
    articleId: number, options: { query:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof articleControllerGetArticle>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof articleControllerGetArticle>>,
          TError,
          Awaited<ReturnType<typeof articleControllerGetArticle>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useArticleControllerGetArticleInfinite<TData = InfiniteData<Awaited<ReturnType<typeof articleControllerGetArticle>>>, TError = unknown>(
 boardId: number,
    articleId: number, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof articleControllerGetArticle>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof articleControllerGetArticle>>,
          TError,
          Awaited<ReturnType<typeof articleControllerGetArticle>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useArticleControllerGetArticleInfinite<TData = InfiniteData<Awaited<ReturnType<typeof articleControllerGetArticle>>>, TError = unknown>(
 boardId: number,
    articleId: number, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof articleControllerGetArticle>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary 게시글 조회
 */

export function useArticleControllerGetArticleInfinite<TData = InfiniteData<Awaited<ReturnType<typeof articleControllerGetArticle>>>, TError = unknown>(
 boardId: number,
    articleId: number, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof articleControllerGetArticle>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getArticleControllerGetArticleInfiniteQueryOptions(boardId,articleId,options)

  const query = useInfiniteQuery(queryOptions, queryClient) as  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




export const getArticleControllerGetArticleQueryOptions = <TData = Awaited<ReturnType<typeof articleControllerGetArticle>>, TError = unknown>(boardId: number,
    articleId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof articleControllerGetArticle>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getArticleControllerGetArticleQueryKey(boardId,articleId);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof articleControllerGetArticle>>> = ({ signal }) => articleControllerGetArticle(boardId,articleId, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(boardId && articleId), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof articleControllerGetArticle>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ArticleControllerGetArticleQueryResult = NonNullable<Awaited<ReturnType<typeof articleControllerGetArticle>>>
export type ArticleControllerGetArticleQueryError = unknown


export function useArticleControllerGetArticle<TData = Awaited<ReturnType<typeof articleControllerGetArticle>>, TError = unknown>(
 boardId: number,
    articleId: number, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof articleControllerGetArticle>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof articleControllerGetArticle>>,
          TError,
          Awaited<ReturnType<typeof articleControllerGetArticle>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useArticleControllerGetArticle<TData = Awaited<ReturnType<typeof articleControllerGetArticle>>, TError = unknown>(
 boardId: number,
    articleId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof articleControllerGetArticle>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof articleControllerGetArticle>>,
          TError,
          Awaited<ReturnType<typeof articleControllerGetArticle>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useArticleControllerGetArticle<TData = Awaited<ReturnType<typeof articleControllerGetArticle>>, TError = unknown>(
 boardId: number,
    articleId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof articleControllerGetArticle>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary 게시글 조회
 */

export function useArticleControllerGetArticle<TData = Awaited<ReturnType<typeof articleControllerGetArticle>>, TError = unknown>(
 boardId: number,
    articleId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof articleControllerGetArticle>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getArticleControllerGetArticleQueryOptions(boardId,articleId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




/**
 * @summary 게시글 삭제
 */
export const articleControllerDeleteArticle = (
    boardId: number,
    articleId: number,
 signal?: AbortSignal
) => {
      
      
      return customAxiosInstance<DeletedArticleResponseDto>(
      {url: `/api/v1/boards/${boardId}/articles/${articleId}`, method: 'DELETE', signal
    },
      );
    }
  


export const getArticleControllerDeleteArticleMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof articleControllerDeleteArticle>>, TError,{boardId: number;articleId: number}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof articleControllerDeleteArticle>>, TError,{boardId: number;articleId: number}, TContext> => {

const mutationKey = ['articleControllerDeleteArticle'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof articleControllerDeleteArticle>>, {boardId: number;articleId: number}> = (props) => {
          const {boardId,articleId} = props ?? {};

          return  articleControllerDeleteArticle(boardId,articleId,)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type ArticleControllerDeleteArticleMutationResult = NonNullable<Awaited<ReturnType<typeof articleControllerDeleteArticle>>>
    
    export type ArticleControllerDeleteArticleMutationError = unknown

    /**
 * @summary 게시글 삭제
 */
export const useArticleControllerDeleteArticle = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof articleControllerDeleteArticle>>, TError,{boardId: number;articleId: number}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof articleControllerDeleteArticle>>,
        TError,
        {boardId: number;articleId: number},
        TContext
      > => {
      return useMutation(getArticleControllerDeleteArticleMutationOptions(options), queryClient);
    }
    /**
 * @summary 게시글 좋아요 토글
 */
export const articleControllerToggleLike = (
    boardId: number,
    articleId: number,
 signal?: AbortSignal
) => {
      
      
      return customAxiosInstance<LikeArticleResponseDto | ArticleControllerToggleLike201>(
      {url: `/api/v1/boards/${boardId}/articles/${articleId}/like`, method: 'POST', signal
    },
      );
    }
  


export const getArticleControllerToggleLikeMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof articleControllerToggleLike>>, TError,{boardId: number;articleId: number}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof articleControllerToggleLike>>, TError,{boardId: number;articleId: number}, TContext> => {

const mutationKey = ['articleControllerToggleLike'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof articleControllerToggleLike>>, {boardId: number;articleId: number}> = (props) => {
          const {boardId,articleId} = props ?? {};

          return  articleControllerToggleLike(boardId,articleId,)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type ArticleControllerToggleLikeMutationResult = NonNullable<Awaited<ReturnType<typeof articleControllerToggleLike>>>
    
    export type ArticleControllerToggleLikeMutationError = unknown

    /**
 * @summary 게시글 좋아요 토글
 */
export const useArticleControllerToggleLike = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof articleControllerToggleLike>>, TError,{boardId: number;articleId: number}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof articleControllerToggleLike>>,
        TError,
        {boardId: number;articleId: number},
        TContext
      > => {
      return useMutation(getArticleControllerToggleLikeMutationOptions(options), queryClient);
    }
    /**
 * @summary 댓글 작성
 */
export const articleControllerCreateComment = (
    boardId: number,
    articleId: number,
    createCommentDto: CreateCommentDto,
 signal?: AbortSignal
) => {
      
      
      return customAxiosInstance<CommentResponseDto>(
      {url: `/api/v1/boards/${boardId}/articles/${articleId}/comments`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: createCommentDto, signal
    },
      );
    }
  


export const getArticleControllerCreateCommentMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof articleControllerCreateComment>>, TError,{boardId: number;articleId: number;data: CreateCommentDto}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof articleControllerCreateComment>>, TError,{boardId: number;articleId: number;data: CreateCommentDto}, TContext> => {

const mutationKey = ['articleControllerCreateComment'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof articleControllerCreateComment>>, {boardId: number;articleId: number;data: CreateCommentDto}> = (props) => {
          const {boardId,articleId,data} = props ?? {};

          return  articleControllerCreateComment(boardId,articleId,data,)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type ArticleControllerCreateCommentMutationResult = NonNullable<Awaited<ReturnType<typeof articleControllerCreateComment>>>
    export type ArticleControllerCreateCommentMutationBody = CreateCommentDto
    export type ArticleControllerCreateCommentMutationError = unknown

    /**
 * @summary 댓글 작성
 */
export const useArticleControllerCreateComment = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof articleControllerCreateComment>>, TError,{boardId: number;articleId: number;data: CreateCommentDto}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof articleControllerCreateComment>>,
        TError,
        {boardId: number;articleId: number;data: CreateCommentDto},
        TContext
      > => {
      return useMutation(getArticleControllerCreateCommentMutationOptions(options), queryClient);
    }
    /**
 * @summary 댓글 삭제
 */
export const articleControllerDeleteComment = (
    boardId: number,
    articleId: number,
    commentId: number,
 signal?: AbortSignal
) => {
      
      
      return customAxiosInstance<DeletedCommentResponseDto>(
      {url: `/api/v1/boards/${boardId}/articles/${articleId}/comments/${commentId}`, method: 'DELETE', signal
    },
      );
    }
  


export const getArticleControllerDeleteCommentMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof articleControllerDeleteComment>>, TError,{boardId: number;articleId: number;commentId: number}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof articleControllerDeleteComment>>, TError,{boardId: number;articleId: number;commentId: number}, TContext> => {

const mutationKey = ['articleControllerDeleteComment'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof articleControllerDeleteComment>>, {boardId: number;articleId: number;commentId: number}> = (props) => {
          const {boardId,articleId,commentId} = props ?? {};

          return  articleControllerDeleteComment(boardId,articleId,commentId,)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type ArticleControllerDeleteCommentMutationResult = NonNullable<Awaited<ReturnType<typeof articleControllerDeleteComment>>>
    
    export type ArticleControllerDeleteCommentMutationError = unknown

    /**
 * @summary 댓글 삭제
 */
export const useArticleControllerDeleteComment = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof articleControllerDeleteComment>>, TError,{boardId: number;articleId: number;commentId: number}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof articleControllerDeleteComment>>,
        TError,
        {boardId: number;articleId: number;commentId: number},
        TContext
      > => {
      return useMutation(getArticleControllerDeleteCommentMutationOptions(options), queryClient);
    }
    