/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * Rawfli API
 * The Rawfli API description
 * OpenAPI spec version: 1.0
 */
import {
  useInfiniteQuery,
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseInfiniteQueryResult,
  DefinedUseQueryResult,
  InfiniteData,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseInfiniteQueryOptions,
  UseInfiniteQueryResult,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  LensListResponseDtoResponse,
  LensResponseDtoResponse,
  LensesControllerGetLensesParams,
  LensesControllerGetUnverifiedLensesParams,
  LensesControllerMergeLenses201,
  MergeEquipmentDto
} from '../../model';

import { customAxiosInstance } from '../../../mutator';




/**
 * @summary 렌즈 목록 조회
 */
export const lensesControllerGetLenses = (
    params: LensesControllerGetLensesParams,
 signal?: AbortSignal
) => {
      
      
      return customAxiosInstance<LensListResponseDtoResponse>(
      {url: `/api/v1/lenses`, method: 'GET',
        params, signal
    },
      );
    }
  



export const getLensesControllerGetLensesInfiniteQueryKey = (params?: LensesControllerGetLensesParams,) => {
    return [
    'infinite', `/api/v1/lenses`, ...(params ? [params] : [])
    ] as const;
    }

export const getLensesControllerGetLensesQueryKey = (params?: LensesControllerGetLensesParams,) => {
    return [
    `/api/v1/lenses`, ...(params ? [params] : [])
    ] as const;
    }

    
export const getLensesControllerGetLensesInfiniteQueryOptions = <TData = InfiniteData<Awaited<ReturnType<typeof lensesControllerGetLenses>>>, TError = unknown>(params: LensesControllerGetLensesParams, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof lensesControllerGetLenses>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getLensesControllerGetLensesInfiniteQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof lensesControllerGetLenses>>> = ({ signal }) => lensesControllerGetLenses(params, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseInfiniteQueryOptions<Awaited<ReturnType<typeof lensesControllerGetLenses>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type LensesControllerGetLensesInfiniteQueryResult = NonNullable<Awaited<ReturnType<typeof lensesControllerGetLenses>>>
export type LensesControllerGetLensesInfiniteQueryError = unknown


export function useLensesControllerGetLensesInfinite<TData = InfiniteData<Awaited<ReturnType<typeof lensesControllerGetLenses>>>, TError = unknown>(
 params: LensesControllerGetLensesParams, options: { query:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof lensesControllerGetLenses>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof lensesControllerGetLenses>>,
          TError,
          Awaited<ReturnType<typeof lensesControllerGetLenses>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useLensesControllerGetLensesInfinite<TData = InfiniteData<Awaited<ReturnType<typeof lensesControllerGetLenses>>>, TError = unknown>(
 params: LensesControllerGetLensesParams, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof lensesControllerGetLenses>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof lensesControllerGetLenses>>,
          TError,
          Awaited<ReturnType<typeof lensesControllerGetLenses>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useLensesControllerGetLensesInfinite<TData = InfiniteData<Awaited<ReturnType<typeof lensesControllerGetLenses>>>, TError = unknown>(
 params: LensesControllerGetLensesParams, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof lensesControllerGetLenses>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary 렌즈 목록 조회
 */

export function useLensesControllerGetLensesInfinite<TData = InfiniteData<Awaited<ReturnType<typeof lensesControllerGetLenses>>>, TError = unknown>(
 params: LensesControllerGetLensesParams, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof lensesControllerGetLenses>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getLensesControllerGetLensesInfiniteQueryOptions(params,options)

  const query = useInfiniteQuery(queryOptions, queryClient) as  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




export const getLensesControllerGetLensesQueryOptions = <TData = Awaited<ReturnType<typeof lensesControllerGetLenses>>, TError = unknown>(params: LensesControllerGetLensesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof lensesControllerGetLenses>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getLensesControllerGetLensesQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof lensesControllerGetLenses>>> = ({ signal }) => lensesControllerGetLenses(params, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof lensesControllerGetLenses>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type LensesControllerGetLensesQueryResult = NonNullable<Awaited<ReturnType<typeof lensesControllerGetLenses>>>
export type LensesControllerGetLensesQueryError = unknown


export function useLensesControllerGetLenses<TData = Awaited<ReturnType<typeof lensesControllerGetLenses>>, TError = unknown>(
 params: LensesControllerGetLensesParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof lensesControllerGetLenses>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof lensesControllerGetLenses>>,
          TError,
          Awaited<ReturnType<typeof lensesControllerGetLenses>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useLensesControllerGetLenses<TData = Awaited<ReturnType<typeof lensesControllerGetLenses>>, TError = unknown>(
 params: LensesControllerGetLensesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof lensesControllerGetLenses>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof lensesControllerGetLenses>>,
          TError,
          Awaited<ReturnType<typeof lensesControllerGetLenses>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useLensesControllerGetLenses<TData = Awaited<ReturnType<typeof lensesControllerGetLenses>>, TError = unknown>(
 params: LensesControllerGetLensesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof lensesControllerGetLenses>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary 렌즈 목록 조회
 */

export function useLensesControllerGetLenses<TData = Awaited<ReturnType<typeof lensesControllerGetLenses>>, TError = unknown>(
 params: LensesControllerGetLensesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof lensesControllerGetLenses>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getLensesControllerGetLensesQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




/**
 * @summary 미검증 렌즈 목록 조회
 */
export const lensesControllerGetUnverifiedLenses = (
    params: LensesControllerGetUnverifiedLensesParams,
 signal?: AbortSignal
) => {
      
      
      return customAxiosInstance<LensListResponseDtoResponse>(
      {url: `/api/v1/lenses/unverified`, method: 'GET',
        params, signal
    },
      );
    }
  



export const getLensesControllerGetUnverifiedLensesInfiniteQueryKey = (params?: LensesControllerGetUnverifiedLensesParams,) => {
    return [
    'infinite', `/api/v1/lenses/unverified`, ...(params ? [params] : [])
    ] as const;
    }

export const getLensesControllerGetUnverifiedLensesQueryKey = (params?: LensesControllerGetUnverifiedLensesParams,) => {
    return [
    `/api/v1/lenses/unverified`, ...(params ? [params] : [])
    ] as const;
    }

    
export const getLensesControllerGetUnverifiedLensesInfiniteQueryOptions = <TData = InfiniteData<Awaited<ReturnType<typeof lensesControllerGetUnverifiedLenses>>>, TError = unknown>(params: LensesControllerGetUnverifiedLensesParams, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof lensesControllerGetUnverifiedLenses>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getLensesControllerGetUnverifiedLensesInfiniteQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof lensesControllerGetUnverifiedLenses>>> = ({ signal }) => lensesControllerGetUnverifiedLenses(params, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseInfiniteQueryOptions<Awaited<ReturnType<typeof lensesControllerGetUnverifiedLenses>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type LensesControllerGetUnverifiedLensesInfiniteQueryResult = NonNullable<Awaited<ReturnType<typeof lensesControllerGetUnverifiedLenses>>>
export type LensesControllerGetUnverifiedLensesInfiniteQueryError = unknown


export function useLensesControllerGetUnverifiedLensesInfinite<TData = InfiniteData<Awaited<ReturnType<typeof lensesControllerGetUnverifiedLenses>>>, TError = unknown>(
 params: LensesControllerGetUnverifiedLensesParams, options: { query:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof lensesControllerGetUnverifiedLenses>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof lensesControllerGetUnverifiedLenses>>,
          TError,
          Awaited<ReturnType<typeof lensesControllerGetUnverifiedLenses>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useLensesControllerGetUnverifiedLensesInfinite<TData = InfiniteData<Awaited<ReturnType<typeof lensesControllerGetUnverifiedLenses>>>, TError = unknown>(
 params: LensesControllerGetUnverifiedLensesParams, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof lensesControllerGetUnverifiedLenses>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof lensesControllerGetUnverifiedLenses>>,
          TError,
          Awaited<ReturnType<typeof lensesControllerGetUnverifiedLenses>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useLensesControllerGetUnverifiedLensesInfinite<TData = InfiniteData<Awaited<ReturnType<typeof lensesControllerGetUnverifiedLenses>>>, TError = unknown>(
 params: LensesControllerGetUnverifiedLensesParams, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof lensesControllerGetUnverifiedLenses>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary 미검증 렌즈 목록 조회
 */

export function useLensesControllerGetUnverifiedLensesInfinite<TData = InfiniteData<Awaited<ReturnType<typeof lensesControllerGetUnverifiedLenses>>>, TError = unknown>(
 params: LensesControllerGetUnverifiedLensesParams, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof lensesControllerGetUnverifiedLenses>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getLensesControllerGetUnverifiedLensesInfiniteQueryOptions(params,options)

  const query = useInfiniteQuery(queryOptions, queryClient) as  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




export const getLensesControllerGetUnverifiedLensesQueryOptions = <TData = Awaited<ReturnType<typeof lensesControllerGetUnverifiedLenses>>, TError = unknown>(params: LensesControllerGetUnverifiedLensesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof lensesControllerGetUnverifiedLenses>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getLensesControllerGetUnverifiedLensesQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof lensesControllerGetUnverifiedLenses>>> = ({ signal }) => lensesControllerGetUnverifiedLenses(params, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof lensesControllerGetUnverifiedLenses>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type LensesControllerGetUnverifiedLensesQueryResult = NonNullable<Awaited<ReturnType<typeof lensesControllerGetUnverifiedLenses>>>
export type LensesControllerGetUnverifiedLensesQueryError = unknown


export function useLensesControllerGetUnverifiedLenses<TData = Awaited<ReturnType<typeof lensesControllerGetUnverifiedLenses>>, TError = unknown>(
 params: LensesControllerGetUnverifiedLensesParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof lensesControllerGetUnverifiedLenses>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof lensesControllerGetUnverifiedLenses>>,
          TError,
          Awaited<ReturnType<typeof lensesControllerGetUnverifiedLenses>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useLensesControllerGetUnverifiedLenses<TData = Awaited<ReturnType<typeof lensesControllerGetUnverifiedLenses>>, TError = unknown>(
 params: LensesControllerGetUnverifiedLensesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof lensesControllerGetUnverifiedLenses>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof lensesControllerGetUnverifiedLenses>>,
          TError,
          Awaited<ReturnType<typeof lensesControllerGetUnverifiedLenses>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useLensesControllerGetUnverifiedLenses<TData = Awaited<ReturnType<typeof lensesControllerGetUnverifiedLenses>>, TError = unknown>(
 params: LensesControllerGetUnverifiedLensesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof lensesControllerGetUnverifiedLenses>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary 미검증 렌즈 목록 조회
 */

export function useLensesControllerGetUnverifiedLenses<TData = Awaited<ReturnType<typeof lensesControllerGetUnverifiedLenses>>, TError = unknown>(
 params: LensesControllerGetUnverifiedLensesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof lensesControllerGetUnverifiedLenses>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getLensesControllerGetUnverifiedLensesQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




/**
 * @summary 렌즈 병합 (관리자)
 */
export const lensesControllerMergeLenses = (
    mergeEquipmentDto: MergeEquipmentDto,
 signal?: AbortSignal
) => {
      
      
      return customAxiosInstance<LensResponseDtoResponse | LensesControllerMergeLenses201>(
      {url: `/api/v1/lenses/merge`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: mergeEquipmentDto, signal
    },
      );
    }
  


export const getLensesControllerMergeLensesMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof lensesControllerMergeLenses>>, TError,{data: MergeEquipmentDto}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof lensesControllerMergeLenses>>, TError,{data: MergeEquipmentDto}, TContext> => {

const mutationKey = ['lensesControllerMergeLenses'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof lensesControllerMergeLenses>>, {data: MergeEquipmentDto}> = (props) => {
          const {data} = props ?? {};

          return  lensesControllerMergeLenses(data,)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type LensesControllerMergeLensesMutationResult = NonNullable<Awaited<ReturnType<typeof lensesControllerMergeLenses>>>
    export type LensesControllerMergeLensesMutationBody = MergeEquipmentDto
    export type LensesControllerMergeLensesMutationError = unknown

    /**
 * @summary 렌즈 병합 (관리자)
 */
export const useLensesControllerMergeLenses = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof lensesControllerMergeLenses>>, TError,{data: MergeEquipmentDto}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof lensesControllerMergeLenses>>,
        TError,
        {data: MergeEquipmentDto},
        TContext
      > => {
      return useMutation(getLensesControllerMergeLensesMutationOptions(options), queryClient);
    }
    