/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * Rawfli API
 * The Rawfli API description
 * OpenAPI spec version: 1.0
 */
import {
  useInfiniteQuery,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseInfiniteQueryResult,
  DefinedUseQueryResult,
  InfiniteData,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseInfiniteQueryOptions,
  UseInfiniteQueryResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  LensListResponseDtoResponse,
  LensesControllerGetLensesParams
} from '../../model';

import { customAxiosInstance } from '../../../mutator';




/**
 * @summary 렌즈 목록 조회
 */
export const lensesControllerGetLenses = (
    params: LensesControllerGetLensesParams,
 signal?: AbortSignal
) => {
      
      
      return customAxiosInstance<LensListResponseDtoResponse>(
      {url: `/api/v1/lenses`, method: 'GET',
        params, signal
    },
      );
    }
  



export const getLensesControllerGetLensesInfiniteQueryKey = (params?: LensesControllerGetLensesParams,) => {
    return [
    'infinite', `/api/v1/lenses`, ...(params ? [params] : [])
    ] as const;
    }

export const getLensesControllerGetLensesQueryKey = (params?: LensesControllerGetLensesParams,) => {
    return [
    `/api/v1/lenses`, ...(params ? [params] : [])
    ] as const;
    }

    
export const getLensesControllerGetLensesInfiniteQueryOptions = <TData = InfiniteData<Awaited<ReturnType<typeof lensesControllerGetLenses>>>, TError = unknown>(params: LensesControllerGetLensesParams, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof lensesControllerGetLenses>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getLensesControllerGetLensesInfiniteQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof lensesControllerGetLenses>>> = ({ signal }) => lensesControllerGetLenses(params, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseInfiniteQueryOptions<Awaited<ReturnType<typeof lensesControllerGetLenses>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type LensesControllerGetLensesInfiniteQueryResult = NonNullable<Awaited<ReturnType<typeof lensesControllerGetLenses>>>
export type LensesControllerGetLensesInfiniteQueryError = unknown


export function useLensesControllerGetLensesInfinite<TData = InfiniteData<Awaited<ReturnType<typeof lensesControllerGetLenses>>>, TError = unknown>(
 params: LensesControllerGetLensesParams, options: { query:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof lensesControllerGetLenses>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof lensesControllerGetLenses>>,
          TError,
          Awaited<ReturnType<typeof lensesControllerGetLenses>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useLensesControllerGetLensesInfinite<TData = InfiniteData<Awaited<ReturnType<typeof lensesControllerGetLenses>>>, TError = unknown>(
 params: LensesControllerGetLensesParams, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof lensesControllerGetLenses>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof lensesControllerGetLenses>>,
          TError,
          Awaited<ReturnType<typeof lensesControllerGetLenses>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useLensesControllerGetLensesInfinite<TData = InfiniteData<Awaited<ReturnType<typeof lensesControllerGetLenses>>>, TError = unknown>(
 params: LensesControllerGetLensesParams, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof lensesControllerGetLenses>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary 렌즈 목록 조회
 */

export function useLensesControllerGetLensesInfinite<TData = InfiniteData<Awaited<ReturnType<typeof lensesControllerGetLenses>>>, TError = unknown>(
 params: LensesControllerGetLensesParams, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof lensesControllerGetLenses>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getLensesControllerGetLensesInfiniteQueryOptions(params,options)

  const query = useInfiniteQuery(queryOptions, queryClient) as  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




export const getLensesControllerGetLensesQueryOptions = <TData = Awaited<ReturnType<typeof lensesControllerGetLenses>>, TError = unknown>(params: LensesControllerGetLensesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof lensesControllerGetLenses>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getLensesControllerGetLensesQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof lensesControllerGetLenses>>> = ({ signal }) => lensesControllerGetLenses(params, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof lensesControllerGetLenses>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type LensesControllerGetLensesQueryResult = NonNullable<Awaited<ReturnType<typeof lensesControllerGetLenses>>>
export type LensesControllerGetLensesQueryError = unknown


export function useLensesControllerGetLenses<TData = Awaited<ReturnType<typeof lensesControllerGetLenses>>, TError = unknown>(
 params: LensesControllerGetLensesParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof lensesControllerGetLenses>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof lensesControllerGetLenses>>,
          TError,
          Awaited<ReturnType<typeof lensesControllerGetLenses>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useLensesControllerGetLenses<TData = Awaited<ReturnType<typeof lensesControllerGetLenses>>, TError = unknown>(
 params: LensesControllerGetLensesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof lensesControllerGetLenses>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof lensesControllerGetLenses>>,
          TError,
          Awaited<ReturnType<typeof lensesControllerGetLenses>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useLensesControllerGetLenses<TData = Awaited<ReturnType<typeof lensesControllerGetLenses>>, TError = unknown>(
 params: LensesControllerGetLensesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof lensesControllerGetLenses>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary 렌즈 목록 조회
 */

export function useLensesControllerGetLenses<TData = Awaited<ReturnType<typeof lensesControllerGetLenses>>, TError = unknown>(
 params: LensesControllerGetLensesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof lensesControllerGetLenses>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getLensesControllerGetLensesQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




