/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * Rawfli API
 * The Rawfli API description
 * OpenAPI spec version: 1.0
 */
import {
  useInfiniteQuery,
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseInfiniteQueryResult,
  DefinedUseQueryResult,
  InfiniteData,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseInfiniteQueryOptions,
  UseInfiniteQueryResult,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  AuthControllerLogin201,
  AuthControllerSignUp201,
  AwsControllerGetImages200,
  AwsControllerUploadFile201,
  BoardsControllerGetBoard200,
  BoardsControllerGetBoards200,
  BoardsControllerSearchInAllBoards200,
  BoardsControllerSearchInAllBoardsParams,
  BoardsControllerSearchInBoard200,
  BoardsControllerSearchInBoardParams,
  CreateCommentDto,
  CreatePostDto,
  CreateUserDto,
  LoginUserDto,
  PostsControllerCreateComment201,
  PostsControllerCreatePost201,
  PostsControllerDeleteComment200,
  PostsControllerDeletePost200,
  PostsControllerGetDeletedPosts200,
  PostsControllerGetPost200,
  PostsControllerGetPosts200,
  PostsControllerGetPostsParams,
  PostsControllerToggleLike201
} from '../../model';

import { customAxiosInstance } from '../../../mutator';




export const authControllerSignUp = (
    createUserDto: CreateUserDto,
 signal?: AbortSignal
) => {
      
      
      return customAxiosInstance<AuthControllerSignUp201>(
      {url: `/api/v1/auth/signup`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: createUserDto, signal
    },
      );
    }
  


export const getAuthControllerSignUpMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof authControllerSignUp>>, TError,{data: CreateUserDto}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof authControllerSignUp>>, TError,{data: CreateUserDto}, TContext> => {

const mutationKey = ['authControllerSignUp'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof authControllerSignUp>>, {data: CreateUserDto}> = (props) => {
          const {data} = props ?? {};

          return  authControllerSignUp(data,)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type AuthControllerSignUpMutationResult = NonNullable<Awaited<ReturnType<typeof authControllerSignUp>>>
    export type AuthControllerSignUpMutationBody = CreateUserDto
    export type AuthControllerSignUpMutationError = unknown

    export const useAuthControllerSignUp = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof authControllerSignUp>>, TError,{data: CreateUserDto}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof authControllerSignUp>>,
        TError,
        {data: CreateUserDto},
        TContext
      > => {
      return useMutation(getAuthControllerSignUpMutationOptions(options), queryClient);
    }
    export const authControllerLogin = (
    loginUserDto: LoginUserDto,
 signal?: AbortSignal
) => {
      
      
      return customAxiosInstance<AuthControllerLogin201>(
      {url: `/api/v1/auth/login`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: loginUserDto, signal
    },
      );
    }
  


export const getAuthControllerLoginMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof authControllerLogin>>, TError,{data: LoginUserDto}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof authControllerLogin>>, TError,{data: LoginUserDto}, TContext> => {

const mutationKey = ['authControllerLogin'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof authControllerLogin>>, {data: LoginUserDto}> = (props) => {
          const {data} = props ?? {};

          return  authControllerLogin(data,)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type AuthControllerLoginMutationResult = NonNullable<Awaited<ReturnType<typeof authControllerLogin>>>
    export type AuthControllerLoginMutationBody = LoginUserDto
    export type AuthControllerLoginMutationError = unknown

    export const useAuthControllerLogin = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof authControllerLogin>>, TError,{data: LoginUserDto}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof authControllerLogin>>,
        TError,
        {data: LoginUserDto},
        TContext
      > => {
      return useMutation(getAuthControllerLoginMutationOptions(options), queryClient);
    }
    export const awsControllerGetImages = (
    
 signal?: AbortSignal
) => {
      
      
      return customAxiosInstance<AwsControllerGetImages200>(
      {url: `/api/v1/aws/images`, method: 'GET', signal
    },
      );
    }
  



export const getAwsControllerGetImagesInfiniteQueryKey = () => {
    return [
    'infinite', `/api/v1/aws/images`
    ] as const;
    }

export const getAwsControllerGetImagesQueryKey = () => {
    return [
    `/api/v1/aws/images`
    ] as const;
    }

    
export const getAwsControllerGetImagesInfiniteQueryOptions = <TData = InfiniteData<Awaited<ReturnType<typeof awsControllerGetImages>>>, TError = unknown>( options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof awsControllerGetImages>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getAwsControllerGetImagesInfiniteQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof awsControllerGetImages>>> = ({ signal }) => awsControllerGetImages(signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseInfiniteQueryOptions<Awaited<ReturnType<typeof awsControllerGetImages>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type AwsControllerGetImagesInfiniteQueryResult = NonNullable<Awaited<ReturnType<typeof awsControllerGetImages>>>
export type AwsControllerGetImagesInfiniteQueryError = unknown


export function useAwsControllerGetImagesInfinite<TData = InfiniteData<Awaited<ReturnType<typeof awsControllerGetImages>>>, TError = unknown>(
  options: { query:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof awsControllerGetImages>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof awsControllerGetImages>>,
          TError,
          Awaited<ReturnType<typeof awsControllerGetImages>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useAwsControllerGetImagesInfinite<TData = InfiniteData<Awaited<ReturnType<typeof awsControllerGetImages>>>, TError = unknown>(
  options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof awsControllerGetImages>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof awsControllerGetImages>>,
          TError,
          Awaited<ReturnType<typeof awsControllerGetImages>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useAwsControllerGetImagesInfinite<TData = InfiniteData<Awaited<ReturnType<typeof awsControllerGetImages>>>, TError = unknown>(
  options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof awsControllerGetImages>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useAwsControllerGetImagesInfinite<TData = InfiniteData<Awaited<ReturnType<typeof awsControllerGetImages>>>, TError = unknown>(
  options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof awsControllerGetImages>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getAwsControllerGetImagesInfiniteQueryOptions(options)

  const query = useInfiniteQuery(queryOptions, queryClient) as  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




export const getAwsControllerGetImagesQueryOptions = <TData = Awaited<ReturnType<typeof awsControllerGetImages>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof awsControllerGetImages>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getAwsControllerGetImagesQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof awsControllerGetImages>>> = ({ signal }) => awsControllerGetImages(signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof awsControllerGetImages>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type AwsControllerGetImagesQueryResult = NonNullable<Awaited<ReturnType<typeof awsControllerGetImages>>>
export type AwsControllerGetImagesQueryError = unknown


export function useAwsControllerGetImages<TData = Awaited<ReturnType<typeof awsControllerGetImages>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof awsControllerGetImages>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof awsControllerGetImages>>,
          TError,
          Awaited<ReturnType<typeof awsControllerGetImages>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useAwsControllerGetImages<TData = Awaited<ReturnType<typeof awsControllerGetImages>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof awsControllerGetImages>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof awsControllerGetImages>>,
          TError,
          Awaited<ReturnType<typeof awsControllerGetImages>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useAwsControllerGetImages<TData = Awaited<ReturnType<typeof awsControllerGetImages>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof awsControllerGetImages>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useAwsControllerGetImages<TData = Awaited<ReturnType<typeof awsControllerGetImages>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof awsControllerGetImages>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getAwsControllerGetImagesQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




export const awsControllerUploadFile = (
    
 signal?: AbortSignal
) => {
      
      
      return customAxiosInstance<AwsControllerUploadFile201>(
      {url: `/api/v1/aws/upload`, method: 'POST', signal
    },
      );
    }
  


export const getAwsControllerUploadFileMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof awsControllerUploadFile>>, TError,void, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof awsControllerUploadFile>>, TError,void, TContext> => {

const mutationKey = ['awsControllerUploadFile'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof awsControllerUploadFile>>, void> = () => {
          

          return  awsControllerUploadFile()
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type AwsControllerUploadFileMutationResult = NonNullable<Awaited<ReturnType<typeof awsControllerUploadFile>>>
    
    export type AwsControllerUploadFileMutationError = unknown

    export const useAwsControllerUploadFile = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof awsControllerUploadFile>>, TError,void, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof awsControllerUploadFile>>,
        TError,
        void,
        TContext
      > => {
      return useMutation(getAwsControllerUploadFileMutationOptions(options), queryClient);
    }
    export const boardsControllerGetBoards = (
    
 signal?: AbortSignal
) => {
      
      
      return customAxiosInstance<BoardsControllerGetBoards200>(
      {url: `/api/v1/boards`, method: 'GET', signal
    },
      );
    }
  



export const getBoardsControllerGetBoardsInfiniteQueryKey = () => {
    return [
    'infinite', `/api/v1/boards`
    ] as const;
    }

export const getBoardsControllerGetBoardsQueryKey = () => {
    return [
    `/api/v1/boards`
    ] as const;
    }

    
export const getBoardsControllerGetBoardsInfiniteQueryOptions = <TData = InfiniteData<Awaited<ReturnType<typeof boardsControllerGetBoards>>>, TError = unknown>( options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof boardsControllerGetBoards>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getBoardsControllerGetBoardsInfiniteQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof boardsControllerGetBoards>>> = ({ signal }) => boardsControllerGetBoards(signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseInfiniteQueryOptions<Awaited<ReturnType<typeof boardsControllerGetBoards>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type BoardsControllerGetBoardsInfiniteQueryResult = NonNullable<Awaited<ReturnType<typeof boardsControllerGetBoards>>>
export type BoardsControllerGetBoardsInfiniteQueryError = unknown


export function useBoardsControllerGetBoardsInfinite<TData = InfiniteData<Awaited<ReturnType<typeof boardsControllerGetBoards>>>, TError = unknown>(
  options: { query:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof boardsControllerGetBoards>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof boardsControllerGetBoards>>,
          TError,
          Awaited<ReturnType<typeof boardsControllerGetBoards>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useBoardsControllerGetBoardsInfinite<TData = InfiniteData<Awaited<ReturnType<typeof boardsControllerGetBoards>>>, TError = unknown>(
  options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof boardsControllerGetBoards>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof boardsControllerGetBoards>>,
          TError,
          Awaited<ReturnType<typeof boardsControllerGetBoards>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useBoardsControllerGetBoardsInfinite<TData = InfiniteData<Awaited<ReturnType<typeof boardsControllerGetBoards>>>, TError = unknown>(
  options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof boardsControllerGetBoards>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useBoardsControllerGetBoardsInfinite<TData = InfiniteData<Awaited<ReturnType<typeof boardsControllerGetBoards>>>, TError = unknown>(
  options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof boardsControllerGetBoards>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getBoardsControllerGetBoardsInfiniteQueryOptions(options)

  const query = useInfiniteQuery(queryOptions, queryClient) as  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




export const getBoardsControllerGetBoardsQueryOptions = <TData = Awaited<ReturnType<typeof boardsControllerGetBoards>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof boardsControllerGetBoards>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getBoardsControllerGetBoardsQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof boardsControllerGetBoards>>> = ({ signal }) => boardsControllerGetBoards(signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof boardsControllerGetBoards>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type BoardsControllerGetBoardsQueryResult = NonNullable<Awaited<ReturnType<typeof boardsControllerGetBoards>>>
export type BoardsControllerGetBoardsQueryError = unknown


export function useBoardsControllerGetBoards<TData = Awaited<ReturnType<typeof boardsControllerGetBoards>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof boardsControllerGetBoards>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof boardsControllerGetBoards>>,
          TError,
          Awaited<ReturnType<typeof boardsControllerGetBoards>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useBoardsControllerGetBoards<TData = Awaited<ReturnType<typeof boardsControllerGetBoards>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof boardsControllerGetBoards>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof boardsControllerGetBoards>>,
          TError,
          Awaited<ReturnType<typeof boardsControllerGetBoards>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useBoardsControllerGetBoards<TData = Awaited<ReturnType<typeof boardsControllerGetBoards>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof boardsControllerGetBoards>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useBoardsControllerGetBoards<TData = Awaited<ReturnType<typeof boardsControllerGetBoards>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof boardsControllerGetBoards>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getBoardsControllerGetBoardsQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




export const boardsControllerSearchInAllBoards = (
    params: BoardsControllerSearchInAllBoardsParams,
 signal?: AbortSignal
) => {
      
      
      return customAxiosInstance<BoardsControllerSearchInAllBoards200>(
      {url: `/api/v1/boards/search`, method: 'GET',
        params, signal
    },
      );
    }
  



export const getBoardsControllerSearchInAllBoardsInfiniteQueryKey = (params?: BoardsControllerSearchInAllBoardsParams,) => {
    return [
    'infinite', `/api/v1/boards/search`, ...(params ? [params] : [])
    ] as const;
    }

export const getBoardsControllerSearchInAllBoardsQueryKey = (params?: BoardsControllerSearchInAllBoardsParams,) => {
    return [
    `/api/v1/boards/search`, ...(params ? [params] : [])
    ] as const;
    }

    
export const getBoardsControllerSearchInAllBoardsInfiniteQueryOptions = <TData = InfiniteData<Awaited<ReturnType<typeof boardsControllerSearchInAllBoards>>>, TError = unknown>(params: BoardsControllerSearchInAllBoardsParams, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof boardsControllerSearchInAllBoards>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getBoardsControllerSearchInAllBoardsInfiniteQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof boardsControllerSearchInAllBoards>>> = ({ signal }) => boardsControllerSearchInAllBoards(params, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseInfiniteQueryOptions<Awaited<ReturnType<typeof boardsControllerSearchInAllBoards>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type BoardsControllerSearchInAllBoardsInfiniteQueryResult = NonNullable<Awaited<ReturnType<typeof boardsControllerSearchInAllBoards>>>
export type BoardsControllerSearchInAllBoardsInfiniteQueryError = unknown


export function useBoardsControllerSearchInAllBoardsInfinite<TData = InfiniteData<Awaited<ReturnType<typeof boardsControllerSearchInAllBoards>>>, TError = unknown>(
 params: BoardsControllerSearchInAllBoardsParams, options: { query:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof boardsControllerSearchInAllBoards>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof boardsControllerSearchInAllBoards>>,
          TError,
          Awaited<ReturnType<typeof boardsControllerSearchInAllBoards>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useBoardsControllerSearchInAllBoardsInfinite<TData = InfiniteData<Awaited<ReturnType<typeof boardsControllerSearchInAllBoards>>>, TError = unknown>(
 params: BoardsControllerSearchInAllBoardsParams, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof boardsControllerSearchInAllBoards>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof boardsControllerSearchInAllBoards>>,
          TError,
          Awaited<ReturnType<typeof boardsControllerSearchInAllBoards>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useBoardsControllerSearchInAllBoardsInfinite<TData = InfiniteData<Awaited<ReturnType<typeof boardsControllerSearchInAllBoards>>>, TError = unknown>(
 params: BoardsControllerSearchInAllBoardsParams, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof boardsControllerSearchInAllBoards>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useBoardsControllerSearchInAllBoardsInfinite<TData = InfiniteData<Awaited<ReturnType<typeof boardsControllerSearchInAllBoards>>>, TError = unknown>(
 params: BoardsControllerSearchInAllBoardsParams, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof boardsControllerSearchInAllBoards>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getBoardsControllerSearchInAllBoardsInfiniteQueryOptions(params,options)

  const query = useInfiniteQuery(queryOptions, queryClient) as  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




export const getBoardsControllerSearchInAllBoardsQueryOptions = <TData = Awaited<ReturnType<typeof boardsControllerSearchInAllBoards>>, TError = unknown>(params: BoardsControllerSearchInAllBoardsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof boardsControllerSearchInAllBoards>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getBoardsControllerSearchInAllBoardsQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof boardsControllerSearchInAllBoards>>> = ({ signal }) => boardsControllerSearchInAllBoards(params, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof boardsControllerSearchInAllBoards>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type BoardsControllerSearchInAllBoardsQueryResult = NonNullable<Awaited<ReturnType<typeof boardsControllerSearchInAllBoards>>>
export type BoardsControllerSearchInAllBoardsQueryError = unknown


export function useBoardsControllerSearchInAllBoards<TData = Awaited<ReturnType<typeof boardsControllerSearchInAllBoards>>, TError = unknown>(
 params: BoardsControllerSearchInAllBoardsParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof boardsControllerSearchInAllBoards>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof boardsControllerSearchInAllBoards>>,
          TError,
          Awaited<ReturnType<typeof boardsControllerSearchInAllBoards>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useBoardsControllerSearchInAllBoards<TData = Awaited<ReturnType<typeof boardsControllerSearchInAllBoards>>, TError = unknown>(
 params: BoardsControllerSearchInAllBoardsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof boardsControllerSearchInAllBoards>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof boardsControllerSearchInAllBoards>>,
          TError,
          Awaited<ReturnType<typeof boardsControllerSearchInAllBoards>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useBoardsControllerSearchInAllBoards<TData = Awaited<ReturnType<typeof boardsControllerSearchInAllBoards>>, TError = unknown>(
 params: BoardsControllerSearchInAllBoardsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof boardsControllerSearchInAllBoards>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useBoardsControllerSearchInAllBoards<TData = Awaited<ReturnType<typeof boardsControllerSearchInAllBoards>>, TError = unknown>(
 params: BoardsControllerSearchInAllBoardsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof boardsControllerSearchInAllBoards>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getBoardsControllerSearchInAllBoardsQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




export const boardsControllerGetBoard = (
    boardId: number,
 signal?: AbortSignal
) => {
      
      
      return customAxiosInstance<BoardsControllerGetBoard200>(
      {url: `/api/v1/boards/${boardId}`, method: 'GET', signal
    },
      );
    }
  



export const getBoardsControllerGetBoardInfiniteQueryKey = (boardId: number,) => {
    return [
    'infinite', `/api/v1/boards/${boardId}`
    ] as const;
    }

export const getBoardsControllerGetBoardQueryKey = (boardId: number,) => {
    return [
    `/api/v1/boards/${boardId}`
    ] as const;
    }

    
export const getBoardsControllerGetBoardInfiniteQueryOptions = <TData = InfiniteData<Awaited<ReturnType<typeof boardsControllerGetBoard>>>, TError = unknown>(boardId: number, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof boardsControllerGetBoard>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getBoardsControllerGetBoardInfiniteQueryKey(boardId);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof boardsControllerGetBoard>>> = ({ signal }) => boardsControllerGetBoard(boardId, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(boardId), ...queryOptions} as UseInfiniteQueryOptions<Awaited<ReturnType<typeof boardsControllerGetBoard>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type BoardsControllerGetBoardInfiniteQueryResult = NonNullable<Awaited<ReturnType<typeof boardsControllerGetBoard>>>
export type BoardsControllerGetBoardInfiniteQueryError = unknown


export function useBoardsControllerGetBoardInfinite<TData = InfiniteData<Awaited<ReturnType<typeof boardsControllerGetBoard>>>, TError = unknown>(
 boardId: number, options: { query:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof boardsControllerGetBoard>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof boardsControllerGetBoard>>,
          TError,
          Awaited<ReturnType<typeof boardsControllerGetBoard>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useBoardsControllerGetBoardInfinite<TData = InfiniteData<Awaited<ReturnType<typeof boardsControllerGetBoard>>>, TError = unknown>(
 boardId: number, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof boardsControllerGetBoard>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof boardsControllerGetBoard>>,
          TError,
          Awaited<ReturnType<typeof boardsControllerGetBoard>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useBoardsControllerGetBoardInfinite<TData = InfiniteData<Awaited<ReturnType<typeof boardsControllerGetBoard>>>, TError = unknown>(
 boardId: number, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof boardsControllerGetBoard>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useBoardsControllerGetBoardInfinite<TData = InfiniteData<Awaited<ReturnType<typeof boardsControllerGetBoard>>>, TError = unknown>(
 boardId: number, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof boardsControllerGetBoard>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getBoardsControllerGetBoardInfiniteQueryOptions(boardId,options)

  const query = useInfiniteQuery(queryOptions, queryClient) as  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




export const getBoardsControllerGetBoardQueryOptions = <TData = Awaited<ReturnType<typeof boardsControllerGetBoard>>, TError = unknown>(boardId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof boardsControllerGetBoard>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getBoardsControllerGetBoardQueryKey(boardId);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof boardsControllerGetBoard>>> = ({ signal }) => boardsControllerGetBoard(boardId, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(boardId), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof boardsControllerGetBoard>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type BoardsControllerGetBoardQueryResult = NonNullable<Awaited<ReturnType<typeof boardsControllerGetBoard>>>
export type BoardsControllerGetBoardQueryError = unknown


export function useBoardsControllerGetBoard<TData = Awaited<ReturnType<typeof boardsControllerGetBoard>>, TError = unknown>(
 boardId: number, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof boardsControllerGetBoard>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof boardsControllerGetBoard>>,
          TError,
          Awaited<ReturnType<typeof boardsControllerGetBoard>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useBoardsControllerGetBoard<TData = Awaited<ReturnType<typeof boardsControllerGetBoard>>, TError = unknown>(
 boardId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof boardsControllerGetBoard>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof boardsControllerGetBoard>>,
          TError,
          Awaited<ReturnType<typeof boardsControllerGetBoard>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useBoardsControllerGetBoard<TData = Awaited<ReturnType<typeof boardsControllerGetBoard>>, TError = unknown>(
 boardId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof boardsControllerGetBoard>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useBoardsControllerGetBoard<TData = Awaited<ReturnType<typeof boardsControllerGetBoard>>, TError = unknown>(
 boardId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof boardsControllerGetBoard>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getBoardsControllerGetBoardQueryOptions(boardId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




export const boardsControllerSearchInBoard = (
    boardId: number,
    params: BoardsControllerSearchInBoardParams,
 signal?: AbortSignal
) => {
      
      
      return customAxiosInstance<BoardsControllerSearchInBoard200>(
      {url: `/api/v1/boards/${boardId}/search`, method: 'GET',
        params, signal
    },
      );
    }
  



export const getBoardsControllerSearchInBoardInfiniteQueryKey = (boardId: number,
    params?: BoardsControllerSearchInBoardParams,) => {
    return [
    'infinite', `/api/v1/boards/${boardId}/search`, ...(params ? [params] : [])
    ] as const;
    }

export const getBoardsControllerSearchInBoardQueryKey = (boardId: number,
    params?: BoardsControllerSearchInBoardParams,) => {
    return [
    `/api/v1/boards/${boardId}/search`, ...(params ? [params] : [])
    ] as const;
    }

    
export const getBoardsControllerSearchInBoardInfiniteQueryOptions = <TData = InfiniteData<Awaited<ReturnType<typeof boardsControllerSearchInBoard>>>, TError = unknown>(boardId: number,
    params: BoardsControllerSearchInBoardParams, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof boardsControllerSearchInBoard>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getBoardsControllerSearchInBoardInfiniteQueryKey(boardId,params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof boardsControllerSearchInBoard>>> = ({ signal }) => boardsControllerSearchInBoard(boardId,params, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(boardId), ...queryOptions} as UseInfiniteQueryOptions<Awaited<ReturnType<typeof boardsControllerSearchInBoard>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type BoardsControllerSearchInBoardInfiniteQueryResult = NonNullable<Awaited<ReturnType<typeof boardsControllerSearchInBoard>>>
export type BoardsControllerSearchInBoardInfiniteQueryError = unknown


export function useBoardsControllerSearchInBoardInfinite<TData = InfiniteData<Awaited<ReturnType<typeof boardsControllerSearchInBoard>>>, TError = unknown>(
 boardId: number,
    params: BoardsControllerSearchInBoardParams, options: { query:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof boardsControllerSearchInBoard>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof boardsControllerSearchInBoard>>,
          TError,
          Awaited<ReturnType<typeof boardsControllerSearchInBoard>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useBoardsControllerSearchInBoardInfinite<TData = InfiniteData<Awaited<ReturnType<typeof boardsControllerSearchInBoard>>>, TError = unknown>(
 boardId: number,
    params: BoardsControllerSearchInBoardParams, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof boardsControllerSearchInBoard>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof boardsControllerSearchInBoard>>,
          TError,
          Awaited<ReturnType<typeof boardsControllerSearchInBoard>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useBoardsControllerSearchInBoardInfinite<TData = InfiniteData<Awaited<ReturnType<typeof boardsControllerSearchInBoard>>>, TError = unknown>(
 boardId: number,
    params: BoardsControllerSearchInBoardParams, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof boardsControllerSearchInBoard>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useBoardsControllerSearchInBoardInfinite<TData = InfiniteData<Awaited<ReturnType<typeof boardsControllerSearchInBoard>>>, TError = unknown>(
 boardId: number,
    params: BoardsControllerSearchInBoardParams, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof boardsControllerSearchInBoard>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getBoardsControllerSearchInBoardInfiniteQueryOptions(boardId,params,options)

  const query = useInfiniteQuery(queryOptions, queryClient) as  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




export const getBoardsControllerSearchInBoardQueryOptions = <TData = Awaited<ReturnType<typeof boardsControllerSearchInBoard>>, TError = unknown>(boardId: number,
    params: BoardsControllerSearchInBoardParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof boardsControllerSearchInBoard>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getBoardsControllerSearchInBoardQueryKey(boardId,params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof boardsControllerSearchInBoard>>> = ({ signal }) => boardsControllerSearchInBoard(boardId,params, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(boardId), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof boardsControllerSearchInBoard>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type BoardsControllerSearchInBoardQueryResult = NonNullable<Awaited<ReturnType<typeof boardsControllerSearchInBoard>>>
export type BoardsControllerSearchInBoardQueryError = unknown


export function useBoardsControllerSearchInBoard<TData = Awaited<ReturnType<typeof boardsControllerSearchInBoard>>, TError = unknown>(
 boardId: number,
    params: BoardsControllerSearchInBoardParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof boardsControllerSearchInBoard>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof boardsControllerSearchInBoard>>,
          TError,
          Awaited<ReturnType<typeof boardsControllerSearchInBoard>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useBoardsControllerSearchInBoard<TData = Awaited<ReturnType<typeof boardsControllerSearchInBoard>>, TError = unknown>(
 boardId: number,
    params: BoardsControllerSearchInBoardParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof boardsControllerSearchInBoard>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof boardsControllerSearchInBoard>>,
          TError,
          Awaited<ReturnType<typeof boardsControllerSearchInBoard>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useBoardsControllerSearchInBoard<TData = Awaited<ReturnType<typeof boardsControllerSearchInBoard>>, TError = unknown>(
 boardId: number,
    params: BoardsControllerSearchInBoardParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof boardsControllerSearchInBoard>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useBoardsControllerSearchInBoard<TData = Awaited<ReturnType<typeof boardsControllerSearchInBoard>>, TError = unknown>(
 boardId: number,
    params: BoardsControllerSearchInBoardParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof boardsControllerSearchInBoard>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getBoardsControllerSearchInBoardQueryOptions(boardId,params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




export const postsControllerGetPosts = (
    boardId: number,
    params: PostsControllerGetPostsParams,
 signal?: AbortSignal
) => {
      
      
      return customAxiosInstance<PostsControllerGetPosts200>(
      {url: `/api/v1/boards/${boardId}/posts`, method: 'GET',
        params, signal
    },
      );
    }
  



export const getPostsControllerGetPostsInfiniteQueryKey = (boardId: number,
    params?: PostsControllerGetPostsParams,) => {
    return [
    'infinite', `/api/v1/boards/${boardId}/posts`, ...(params ? [params] : [])
    ] as const;
    }

export const getPostsControllerGetPostsQueryKey = (boardId: number,
    params?: PostsControllerGetPostsParams,) => {
    return [
    `/api/v1/boards/${boardId}/posts`, ...(params ? [params] : [])
    ] as const;
    }

    
export const getPostsControllerGetPostsInfiniteQueryOptions = <TData = InfiniteData<Awaited<ReturnType<typeof postsControllerGetPosts>>>, TError = unknown>(boardId: number,
    params: PostsControllerGetPostsParams, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof postsControllerGetPosts>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getPostsControllerGetPostsInfiniteQueryKey(boardId,params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof postsControllerGetPosts>>> = ({ signal }) => postsControllerGetPosts(boardId,params, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(boardId), ...queryOptions} as UseInfiniteQueryOptions<Awaited<ReturnType<typeof postsControllerGetPosts>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type PostsControllerGetPostsInfiniteQueryResult = NonNullable<Awaited<ReturnType<typeof postsControllerGetPosts>>>
export type PostsControllerGetPostsInfiniteQueryError = unknown


export function usePostsControllerGetPostsInfinite<TData = InfiniteData<Awaited<ReturnType<typeof postsControllerGetPosts>>>, TError = unknown>(
 boardId: number,
    params: PostsControllerGetPostsParams, options: { query:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof postsControllerGetPosts>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof postsControllerGetPosts>>,
          TError,
          Awaited<ReturnType<typeof postsControllerGetPosts>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function usePostsControllerGetPostsInfinite<TData = InfiniteData<Awaited<ReturnType<typeof postsControllerGetPosts>>>, TError = unknown>(
 boardId: number,
    params: PostsControllerGetPostsParams, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof postsControllerGetPosts>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof postsControllerGetPosts>>,
          TError,
          Awaited<ReturnType<typeof postsControllerGetPosts>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function usePostsControllerGetPostsInfinite<TData = InfiniteData<Awaited<ReturnType<typeof postsControllerGetPosts>>>, TError = unknown>(
 boardId: number,
    params: PostsControllerGetPostsParams, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof postsControllerGetPosts>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function usePostsControllerGetPostsInfinite<TData = InfiniteData<Awaited<ReturnType<typeof postsControllerGetPosts>>>, TError = unknown>(
 boardId: number,
    params: PostsControllerGetPostsParams, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof postsControllerGetPosts>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getPostsControllerGetPostsInfiniteQueryOptions(boardId,params,options)

  const query = useInfiniteQuery(queryOptions, queryClient) as  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




export const getPostsControllerGetPostsQueryOptions = <TData = Awaited<ReturnType<typeof postsControllerGetPosts>>, TError = unknown>(boardId: number,
    params: PostsControllerGetPostsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof postsControllerGetPosts>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getPostsControllerGetPostsQueryKey(boardId,params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof postsControllerGetPosts>>> = ({ signal }) => postsControllerGetPosts(boardId,params, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(boardId), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof postsControllerGetPosts>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type PostsControllerGetPostsQueryResult = NonNullable<Awaited<ReturnType<typeof postsControllerGetPosts>>>
export type PostsControllerGetPostsQueryError = unknown


export function usePostsControllerGetPosts<TData = Awaited<ReturnType<typeof postsControllerGetPosts>>, TError = unknown>(
 boardId: number,
    params: PostsControllerGetPostsParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof postsControllerGetPosts>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof postsControllerGetPosts>>,
          TError,
          Awaited<ReturnType<typeof postsControllerGetPosts>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function usePostsControllerGetPosts<TData = Awaited<ReturnType<typeof postsControllerGetPosts>>, TError = unknown>(
 boardId: number,
    params: PostsControllerGetPostsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof postsControllerGetPosts>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof postsControllerGetPosts>>,
          TError,
          Awaited<ReturnType<typeof postsControllerGetPosts>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function usePostsControllerGetPosts<TData = Awaited<ReturnType<typeof postsControllerGetPosts>>, TError = unknown>(
 boardId: number,
    params: PostsControllerGetPostsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof postsControllerGetPosts>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function usePostsControllerGetPosts<TData = Awaited<ReturnType<typeof postsControllerGetPosts>>, TError = unknown>(
 boardId: number,
    params: PostsControllerGetPostsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof postsControllerGetPosts>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getPostsControllerGetPostsQueryOptions(boardId,params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




export const postsControllerCreatePost = (
    boardId: number,
    createPostDto: CreatePostDto,
 signal?: AbortSignal
) => {
      
      
      return customAxiosInstance<PostsControllerCreatePost201>(
      {url: `/api/v1/boards/${boardId}/posts`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: createPostDto, signal
    },
      );
    }
  


export const getPostsControllerCreatePostMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postsControllerCreatePost>>, TError,{boardId: number;data: CreatePostDto}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof postsControllerCreatePost>>, TError,{boardId: number;data: CreatePostDto}, TContext> => {

const mutationKey = ['postsControllerCreatePost'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postsControllerCreatePost>>, {boardId: number;data: CreatePostDto}> = (props) => {
          const {boardId,data} = props ?? {};

          return  postsControllerCreatePost(boardId,data,)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type PostsControllerCreatePostMutationResult = NonNullable<Awaited<ReturnType<typeof postsControllerCreatePost>>>
    export type PostsControllerCreatePostMutationBody = CreatePostDto
    export type PostsControllerCreatePostMutationError = unknown

    export const usePostsControllerCreatePost = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postsControllerCreatePost>>, TError,{boardId: number;data: CreatePostDto}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postsControllerCreatePost>>,
        TError,
        {boardId: number;data: CreatePostDto},
        TContext
      > => {
      return useMutation(getPostsControllerCreatePostMutationOptions(options), queryClient);
    }
    export const postsControllerGetPost = (
    boardId: number,
    postId: number,
 signal?: AbortSignal
) => {
      
      
      return customAxiosInstance<PostsControllerGetPost200>(
      {url: `/api/v1/boards/${boardId}/posts/${postId}`, method: 'GET', signal
    },
      );
    }
  



export const getPostsControllerGetPostInfiniteQueryKey = (boardId: number,
    postId: number,) => {
    return [
    'infinite', `/api/v1/boards/${boardId}/posts/${postId}`
    ] as const;
    }

export const getPostsControllerGetPostQueryKey = (boardId: number,
    postId: number,) => {
    return [
    `/api/v1/boards/${boardId}/posts/${postId}`
    ] as const;
    }

    
export const getPostsControllerGetPostInfiniteQueryOptions = <TData = InfiniteData<Awaited<ReturnType<typeof postsControllerGetPost>>>, TError = unknown>(boardId: number,
    postId: number, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof postsControllerGetPost>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getPostsControllerGetPostInfiniteQueryKey(boardId,postId);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof postsControllerGetPost>>> = ({ signal }) => postsControllerGetPost(boardId,postId, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(boardId && postId), ...queryOptions} as UseInfiniteQueryOptions<Awaited<ReturnType<typeof postsControllerGetPost>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type PostsControllerGetPostInfiniteQueryResult = NonNullable<Awaited<ReturnType<typeof postsControllerGetPost>>>
export type PostsControllerGetPostInfiniteQueryError = unknown


export function usePostsControllerGetPostInfinite<TData = InfiniteData<Awaited<ReturnType<typeof postsControllerGetPost>>>, TError = unknown>(
 boardId: number,
    postId: number, options: { query:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof postsControllerGetPost>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof postsControllerGetPost>>,
          TError,
          Awaited<ReturnType<typeof postsControllerGetPost>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function usePostsControllerGetPostInfinite<TData = InfiniteData<Awaited<ReturnType<typeof postsControllerGetPost>>>, TError = unknown>(
 boardId: number,
    postId: number, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof postsControllerGetPost>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof postsControllerGetPost>>,
          TError,
          Awaited<ReturnType<typeof postsControllerGetPost>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function usePostsControllerGetPostInfinite<TData = InfiniteData<Awaited<ReturnType<typeof postsControllerGetPost>>>, TError = unknown>(
 boardId: number,
    postId: number, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof postsControllerGetPost>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function usePostsControllerGetPostInfinite<TData = InfiniteData<Awaited<ReturnType<typeof postsControllerGetPost>>>, TError = unknown>(
 boardId: number,
    postId: number, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof postsControllerGetPost>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getPostsControllerGetPostInfiniteQueryOptions(boardId,postId,options)

  const query = useInfiniteQuery(queryOptions, queryClient) as  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




export const getPostsControllerGetPostQueryOptions = <TData = Awaited<ReturnType<typeof postsControllerGetPost>>, TError = unknown>(boardId: number,
    postId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof postsControllerGetPost>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getPostsControllerGetPostQueryKey(boardId,postId);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof postsControllerGetPost>>> = ({ signal }) => postsControllerGetPost(boardId,postId, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(boardId && postId), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof postsControllerGetPost>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type PostsControllerGetPostQueryResult = NonNullable<Awaited<ReturnType<typeof postsControllerGetPost>>>
export type PostsControllerGetPostQueryError = unknown


export function usePostsControllerGetPost<TData = Awaited<ReturnType<typeof postsControllerGetPost>>, TError = unknown>(
 boardId: number,
    postId: number, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof postsControllerGetPost>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof postsControllerGetPost>>,
          TError,
          Awaited<ReturnType<typeof postsControllerGetPost>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function usePostsControllerGetPost<TData = Awaited<ReturnType<typeof postsControllerGetPost>>, TError = unknown>(
 boardId: number,
    postId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof postsControllerGetPost>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof postsControllerGetPost>>,
          TError,
          Awaited<ReturnType<typeof postsControllerGetPost>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function usePostsControllerGetPost<TData = Awaited<ReturnType<typeof postsControllerGetPost>>, TError = unknown>(
 boardId: number,
    postId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof postsControllerGetPost>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function usePostsControllerGetPost<TData = Awaited<ReturnType<typeof postsControllerGetPost>>, TError = unknown>(
 boardId: number,
    postId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof postsControllerGetPost>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getPostsControllerGetPostQueryOptions(boardId,postId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




export const postsControllerDeletePost = (
    boardId: number,
    postId: number,
 signal?: AbortSignal
) => {
      
      
      return customAxiosInstance<PostsControllerDeletePost200>(
      {url: `/api/v1/boards/${boardId}/posts/${postId}`, method: 'DELETE', signal
    },
      );
    }
  


export const getPostsControllerDeletePostMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postsControllerDeletePost>>, TError,{boardId: number;postId: number}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof postsControllerDeletePost>>, TError,{boardId: number;postId: number}, TContext> => {

const mutationKey = ['postsControllerDeletePost'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postsControllerDeletePost>>, {boardId: number;postId: number}> = (props) => {
          const {boardId,postId} = props ?? {};

          return  postsControllerDeletePost(boardId,postId,)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type PostsControllerDeletePostMutationResult = NonNullable<Awaited<ReturnType<typeof postsControllerDeletePost>>>
    
    export type PostsControllerDeletePostMutationError = unknown

    export const usePostsControllerDeletePost = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postsControllerDeletePost>>, TError,{boardId: number;postId: number}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postsControllerDeletePost>>,
        TError,
        {boardId: number;postId: number},
        TContext
      > => {
      return useMutation(getPostsControllerDeletePostMutationOptions(options), queryClient);
    }
    export const postsControllerToggleLike = (
    boardId: number,
    postId: number,
 signal?: AbortSignal
) => {
      
      
      return customAxiosInstance<PostsControllerToggleLike201>(
      {url: `/api/v1/boards/${boardId}/posts/${postId}/like`, method: 'POST', signal
    },
      );
    }
  


export const getPostsControllerToggleLikeMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postsControllerToggleLike>>, TError,{boardId: number;postId: number}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof postsControllerToggleLike>>, TError,{boardId: number;postId: number}, TContext> => {

const mutationKey = ['postsControllerToggleLike'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postsControllerToggleLike>>, {boardId: number;postId: number}> = (props) => {
          const {boardId,postId} = props ?? {};

          return  postsControllerToggleLike(boardId,postId,)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type PostsControllerToggleLikeMutationResult = NonNullable<Awaited<ReturnType<typeof postsControllerToggleLike>>>
    
    export type PostsControllerToggleLikeMutationError = unknown

    export const usePostsControllerToggleLike = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postsControllerToggleLike>>, TError,{boardId: number;postId: number}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postsControllerToggleLike>>,
        TError,
        {boardId: number;postId: number},
        TContext
      > => {
      return useMutation(getPostsControllerToggleLikeMutationOptions(options), queryClient);
    }
    export const postsControllerCreateComment = (
    boardId: number,
    postId: number,
    createCommentDto: CreateCommentDto,
 signal?: AbortSignal
) => {
      
      
      return customAxiosInstance<PostsControllerCreateComment201>(
      {url: `/api/v1/boards/${boardId}/posts/${postId}/comments`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: createCommentDto, signal
    },
      );
    }
  


export const getPostsControllerCreateCommentMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postsControllerCreateComment>>, TError,{boardId: number;postId: number;data: CreateCommentDto}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof postsControllerCreateComment>>, TError,{boardId: number;postId: number;data: CreateCommentDto}, TContext> => {

const mutationKey = ['postsControllerCreateComment'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postsControllerCreateComment>>, {boardId: number;postId: number;data: CreateCommentDto}> = (props) => {
          const {boardId,postId,data} = props ?? {};

          return  postsControllerCreateComment(boardId,postId,data,)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type PostsControllerCreateCommentMutationResult = NonNullable<Awaited<ReturnType<typeof postsControllerCreateComment>>>
    export type PostsControllerCreateCommentMutationBody = CreateCommentDto
    export type PostsControllerCreateCommentMutationError = unknown

    export const usePostsControllerCreateComment = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postsControllerCreateComment>>, TError,{boardId: number;postId: number;data: CreateCommentDto}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postsControllerCreateComment>>,
        TError,
        {boardId: number;postId: number;data: CreateCommentDto},
        TContext
      > => {
      return useMutation(getPostsControllerCreateCommentMutationOptions(options), queryClient);
    }
    export const postsControllerDeleteComment = (
    boardId: number,
    postId: number,
    commentId: number,
 signal?: AbortSignal
) => {
      
      
      return customAxiosInstance<PostsControllerDeleteComment200>(
      {url: `/api/v1/boards/${boardId}/posts/${postId}/comments/${commentId}`, method: 'DELETE', signal
    },
      );
    }
  


export const getPostsControllerDeleteCommentMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postsControllerDeleteComment>>, TError,{boardId: number;postId: number;commentId: number}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof postsControllerDeleteComment>>, TError,{boardId: number;postId: number;commentId: number}, TContext> => {

const mutationKey = ['postsControllerDeleteComment'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postsControllerDeleteComment>>, {boardId: number;postId: number;commentId: number}> = (props) => {
          const {boardId,postId,commentId} = props ?? {};

          return  postsControllerDeleteComment(boardId,postId,commentId,)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type PostsControllerDeleteCommentMutationResult = NonNullable<Awaited<ReturnType<typeof postsControllerDeleteComment>>>
    
    export type PostsControllerDeleteCommentMutationError = unknown

    export const usePostsControllerDeleteComment = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postsControllerDeleteComment>>, TError,{boardId: number;postId: number;commentId: number}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postsControllerDeleteComment>>,
        TError,
        {boardId: number;postId: number;commentId: number},
        TContext
      > => {
      return useMutation(getPostsControllerDeleteCommentMutationOptions(options), queryClient);
    }
    export const postsControllerGetDeletedPosts = (
    boardId: number,
 signal?: AbortSignal
) => {
      
      
      return customAxiosInstance<PostsControllerGetDeletedPosts200>(
      {url: `/api/v1/boards/${boardId}/posts/deleted/all`, method: 'GET', signal
    },
      );
    }
  



export const getPostsControllerGetDeletedPostsInfiniteQueryKey = (boardId: number,) => {
    return [
    'infinite', `/api/v1/boards/${boardId}/posts/deleted/all`
    ] as const;
    }

export const getPostsControllerGetDeletedPostsQueryKey = (boardId: number,) => {
    return [
    `/api/v1/boards/${boardId}/posts/deleted/all`
    ] as const;
    }

    
export const getPostsControllerGetDeletedPostsInfiniteQueryOptions = <TData = InfiniteData<Awaited<ReturnType<typeof postsControllerGetDeletedPosts>>>, TError = unknown>(boardId: number, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof postsControllerGetDeletedPosts>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getPostsControllerGetDeletedPostsInfiniteQueryKey(boardId);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof postsControllerGetDeletedPosts>>> = ({ signal }) => postsControllerGetDeletedPosts(boardId, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(boardId), ...queryOptions} as UseInfiniteQueryOptions<Awaited<ReturnType<typeof postsControllerGetDeletedPosts>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type PostsControllerGetDeletedPostsInfiniteQueryResult = NonNullable<Awaited<ReturnType<typeof postsControllerGetDeletedPosts>>>
export type PostsControllerGetDeletedPostsInfiniteQueryError = unknown


export function usePostsControllerGetDeletedPostsInfinite<TData = InfiniteData<Awaited<ReturnType<typeof postsControllerGetDeletedPosts>>>, TError = unknown>(
 boardId: number, options: { query:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof postsControllerGetDeletedPosts>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof postsControllerGetDeletedPosts>>,
          TError,
          Awaited<ReturnType<typeof postsControllerGetDeletedPosts>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function usePostsControllerGetDeletedPostsInfinite<TData = InfiniteData<Awaited<ReturnType<typeof postsControllerGetDeletedPosts>>>, TError = unknown>(
 boardId: number, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof postsControllerGetDeletedPosts>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof postsControllerGetDeletedPosts>>,
          TError,
          Awaited<ReturnType<typeof postsControllerGetDeletedPosts>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function usePostsControllerGetDeletedPostsInfinite<TData = InfiniteData<Awaited<ReturnType<typeof postsControllerGetDeletedPosts>>>, TError = unknown>(
 boardId: number, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof postsControllerGetDeletedPosts>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function usePostsControllerGetDeletedPostsInfinite<TData = InfiniteData<Awaited<ReturnType<typeof postsControllerGetDeletedPosts>>>, TError = unknown>(
 boardId: number, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof postsControllerGetDeletedPosts>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getPostsControllerGetDeletedPostsInfiniteQueryOptions(boardId,options)

  const query = useInfiniteQuery(queryOptions, queryClient) as  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




export const getPostsControllerGetDeletedPostsQueryOptions = <TData = Awaited<ReturnType<typeof postsControllerGetDeletedPosts>>, TError = unknown>(boardId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof postsControllerGetDeletedPosts>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getPostsControllerGetDeletedPostsQueryKey(boardId);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof postsControllerGetDeletedPosts>>> = ({ signal }) => postsControllerGetDeletedPosts(boardId, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(boardId), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof postsControllerGetDeletedPosts>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type PostsControllerGetDeletedPostsQueryResult = NonNullable<Awaited<ReturnType<typeof postsControllerGetDeletedPosts>>>
export type PostsControllerGetDeletedPostsQueryError = unknown


export function usePostsControllerGetDeletedPosts<TData = Awaited<ReturnType<typeof postsControllerGetDeletedPosts>>, TError = unknown>(
 boardId: number, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof postsControllerGetDeletedPosts>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof postsControllerGetDeletedPosts>>,
          TError,
          Awaited<ReturnType<typeof postsControllerGetDeletedPosts>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function usePostsControllerGetDeletedPosts<TData = Awaited<ReturnType<typeof postsControllerGetDeletedPosts>>, TError = unknown>(
 boardId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof postsControllerGetDeletedPosts>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof postsControllerGetDeletedPosts>>,
          TError,
          Awaited<ReturnType<typeof postsControllerGetDeletedPosts>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function usePostsControllerGetDeletedPosts<TData = Awaited<ReturnType<typeof postsControllerGetDeletedPosts>>, TError = unknown>(
 boardId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof postsControllerGetDeletedPosts>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function usePostsControllerGetDeletedPosts<TData = Awaited<ReturnType<typeof postsControllerGetDeletedPosts>>, TError = unknown>(
 boardId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof postsControllerGetDeletedPosts>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getPostsControllerGetDeletedPostsQueryOptions(boardId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




