/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * Rawfli API
 * The Rawfli API description
 * OpenAPI spec version: 1.0
 */
import {
  useInfiniteQuery,
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseInfiniteQueryResult,
  DefinedUseQueryResult,
  InfiniteData,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseInfiniteQueryOptions,
  UseInfiniteQueryResult,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  AdminControllerGetDeletedCommentsParams,
  AdminControllerGetDeletedPostsParams,
  AdminControllerGetImagesParams,
  AdminControllerGetUnverifiedCamerasParams,
  AdminControllerGetUnverifiedLensesParams,
  AdminControllerMergeCameras201,
  AdminControllerMergeLenses201,
  AdminDeletedCommentListResponseDtoResponse,
  AdminDeletedPostListResponseDtoResponse,
  AdminImageListResponseDtoResponse,
  AdminInfoDtoResponse,
  AdminTokenDtoResponse,
  CameraListResponseDtoResponse,
  CameraResponseDtoResponse,
  CreateAdminDto,
  LensListResponseDtoResponse,
  LensResponseDtoResponse,
  LoginAdminDto,
  MergeEquipmentDto
} from '../../model';

import { customAxiosInstance } from '../../../mutator';




/**
 * @summary 관리자 계정 생성
 */
export const adminControllerCreateAdmin = (
    createAdminDto: CreateAdminDto,
 signal?: AbortSignal
) => {
      
      
      return customAxiosInstance<AdminInfoDtoResponse>(
      {url: `/api/v1/admin/signup`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: createAdminDto, signal
    },
      );
    }
  


export const getAdminControllerCreateAdminMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof adminControllerCreateAdmin>>, TError,{data: CreateAdminDto}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof adminControllerCreateAdmin>>, TError,{data: CreateAdminDto}, TContext> => {

const mutationKey = ['adminControllerCreateAdmin'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof adminControllerCreateAdmin>>, {data: CreateAdminDto}> = (props) => {
          const {data} = props ?? {};

          return  adminControllerCreateAdmin(data,)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type AdminControllerCreateAdminMutationResult = NonNullable<Awaited<ReturnType<typeof adminControllerCreateAdmin>>>
    export type AdminControllerCreateAdminMutationBody = CreateAdminDto
    export type AdminControllerCreateAdminMutationError = unknown

    /**
 * @summary 관리자 계정 생성
 */
export const useAdminControllerCreateAdmin = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof adminControllerCreateAdmin>>, TError,{data: CreateAdminDto}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof adminControllerCreateAdmin>>,
        TError,
        {data: CreateAdminDto},
        TContext
      > => {
      return useMutation(getAdminControllerCreateAdminMutationOptions(options), queryClient);
    }
    /**
 * @summary 관리자 로그인
 */
export const adminControllerLogin = (
    loginAdminDto: LoginAdminDto,
 signal?: AbortSignal
) => {
      
      
      return customAxiosInstance<AdminTokenDtoResponse>(
      {url: `/api/v1/admin/login`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: loginAdminDto, signal
    },
      );
    }
  


export const getAdminControllerLoginMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof adminControllerLogin>>, TError,{data: LoginAdminDto}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof adminControllerLogin>>, TError,{data: LoginAdminDto}, TContext> => {

const mutationKey = ['adminControllerLogin'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof adminControllerLogin>>, {data: LoginAdminDto}> = (props) => {
          const {data} = props ?? {};

          return  adminControllerLogin(data,)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type AdminControllerLoginMutationResult = NonNullable<Awaited<ReturnType<typeof adminControllerLogin>>>
    export type AdminControllerLoginMutationBody = LoginAdminDto
    export type AdminControllerLoginMutationError = unknown

    /**
 * @summary 관리자 로그인
 */
export const useAdminControllerLogin = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof adminControllerLogin>>, TError,{data: LoginAdminDto}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof adminControllerLogin>>,
        TError,
        {data: LoginAdminDto},
        TContext
      > => {
      return useMutation(getAdminControllerLoginMutationOptions(options), queryClient);
    }
    /**
 * @summary 미검증 카메라 목록 조회
 */
export const adminControllerGetUnverifiedCameras = (
    params: AdminControllerGetUnverifiedCamerasParams,
 signal?: AbortSignal
) => {
      
      
      return customAxiosInstance<CameraListResponseDtoResponse>(
      {url: `/api/v1/admin/cameras/unverified`, method: 'GET',
        params, signal
    },
      );
    }
  



export const getAdminControllerGetUnverifiedCamerasInfiniteQueryKey = (params?: AdminControllerGetUnverifiedCamerasParams,) => {
    return [
    'infinite', `/api/v1/admin/cameras/unverified`, ...(params ? [params] : [])
    ] as const;
    }

export const getAdminControllerGetUnverifiedCamerasQueryKey = (params?: AdminControllerGetUnverifiedCamerasParams,) => {
    return [
    `/api/v1/admin/cameras/unverified`, ...(params ? [params] : [])
    ] as const;
    }

    
export const getAdminControllerGetUnverifiedCamerasInfiniteQueryOptions = <TData = InfiniteData<Awaited<ReturnType<typeof adminControllerGetUnverifiedCameras>>>, TError = unknown>(params: AdminControllerGetUnverifiedCamerasParams, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof adminControllerGetUnverifiedCameras>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getAdminControllerGetUnverifiedCamerasInfiniteQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof adminControllerGetUnverifiedCameras>>> = ({ signal }) => adminControllerGetUnverifiedCameras(params, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseInfiniteQueryOptions<Awaited<ReturnType<typeof adminControllerGetUnverifiedCameras>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type AdminControllerGetUnverifiedCamerasInfiniteQueryResult = NonNullable<Awaited<ReturnType<typeof adminControllerGetUnverifiedCameras>>>
export type AdminControllerGetUnverifiedCamerasInfiniteQueryError = unknown


export function useAdminControllerGetUnverifiedCamerasInfinite<TData = InfiniteData<Awaited<ReturnType<typeof adminControllerGetUnverifiedCameras>>>, TError = unknown>(
 params: AdminControllerGetUnverifiedCamerasParams, options: { query:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof adminControllerGetUnverifiedCameras>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof adminControllerGetUnverifiedCameras>>,
          TError,
          Awaited<ReturnType<typeof adminControllerGetUnverifiedCameras>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useAdminControllerGetUnverifiedCamerasInfinite<TData = InfiniteData<Awaited<ReturnType<typeof adminControllerGetUnverifiedCameras>>>, TError = unknown>(
 params: AdminControllerGetUnverifiedCamerasParams, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof adminControllerGetUnverifiedCameras>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof adminControllerGetUnverifiedCameras>>,
          TError,
          Awaited<ReturnType<typeof adminControllerGetUnverifiedCameras>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useAdminControllerGetUnverifiedCamerasInfinite<TData = InfiniteData<Awaited<ReturnType<typeof adminControllerGetUnverifiedCameras>>>, TError = unknown>(
 params: AdminControllerGetUnverifiedCamerasParams, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof adminControllerGetUnverifiedCameras>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary 미검증 카메라 목록 조회
 */

export function useAdminControllerGetUnverifiedCamerasInfinite<TData = InfiniteData<Awaited<ReturnType<typeof adminControllerGetUnverifiedCameras>>>, TError = unknown>(
 params: AdminControllerGetUnverifiedCamerasParams, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof adminControllerGetUnverifiedCameras>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getAdminControllerGetUnverifiedCamerasInfiniteQueryOptions(params,options)

  const query = useInfiniteQuery(queryOptions, queryClient) as  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




export const getAdminControllerGetUnverifiedCamerasQueryOptions = <TData = Awaited<ReturnType<typeof adminControllerGetUnverifiedCameras>>, TError = unknown>(params: AdminControllerGetUnverifiedCamerasParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof adminControllerGetUnverifiedCameras>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getAdminControllerGetUnverifiedCamerasQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof adminControllerGetUnverifiedCameras>>> = ({ signal }) => adminControllerGetUnverifiedCameras(params, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof adminControllerGetUnverifiedCameras>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type AdminControllerGetUnverifiedCamerasQueryResult = NonNullable<Awaited<ReturnType<typeof adminControllerGetUnverifiedCameras>>>
export type AdminControllerGetUnverifiedCamerasQueryError = unknown


export function useAdminControllerGetUnverifiedCameras<TData = Awaited<ReturnType<typeof adminControllerGetUnverifiedCameras>>, TError = unknown>(
 params: AdminControllerGetUnverifiedCamerasParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof adminControllerGetUnverifiedCameras>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof adminControllerGetUnverifiedCameras>>,
          TError,
          Awaited<ReturnType<typeof adminControllerGetUnverifiedCameras>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useAdminControllerGetUnverifiedCameras<TData = Awaited<ReturnType<typeof adminControllerGetUnverifiedCameras>>, TError = unknown>(
 params: AdminControllerGetUnverifiedCamerasParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof adminControllerGetUnverifiedCameras>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof adminControllerGetUnverifiedCameras>>,
          TError,
          Awaited<ReturnType<typeof adminControllerGetUnverifiedCameras>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useAdminControllerGetUnverifiedCameras<TData = Awaited<ReturnType<typeof adminControllerGetUnverifiedCameras>>, TError = unknown>(
 params: AdminControllerGetUnverifiedCamerasParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof adminControllerGetUnverifiedCameras>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary 미검증 카메라 목록 조회
 */

export function useAdminControllerGetUnverifiedCameras<TData = Awaited<ReturnType<typeof adminControllerGetUnverifiedCameras>>, TError = unknown>(
 params: AdminControllerGetUnverifiedCamerasParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof adminControllerGetUnverifiedCameras>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getAdminControllerGetUnverifiedCamerasQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




/**
 * @summary 카메라 병합
 */
export const adminControllerMergeCameras = (
    mergeEquipmentDto: MergeEquipmentDto,
 signal?: AbortSignal
) => {
      
      
      return customAxiosInstance<CameraResponseDtoResponse | AdminControllerMergeCameras201>(
      {url: `/api/v1/admin/cameras/merge`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: mergeEquipmentDto, signal
    },
      );
    }
  


export const getAdminControllerMergeCamerasMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof adminControllerMergeCameras>>, TError,{data: MergeEquipmentDto}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof adminControllerMergeCameras>>, TError,{data: MergeEquipmentDto}, TContext> => {

const mutationKey = ['adminControllerMergeCameras'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof adminControllerMergeCameras>>, {data: MergeEquipmentDto}> = (props) => {
          const {data} = props ?? {};

          return  adminControllerMergeCameras(data,)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type AdminControllerMergeCamerasMutationResult = NonNullable<Awaited<ReturnType<typeof adminControllerMergeCameras>>>
    export type AdminControllerMergeCamerasMutationBody = MergeEquipmentDto
    export type AdminControllerMergeCamerasMutationError = unknown

    /**
 * @summary 카메라 병합
 */
export const useAdminControllerMergeCameras = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof adminControllerMergeCameras>>, TError,{data: MergeEquipmentDto}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof adminControllerMergeCameras>>,
        TError,
        {data: MergeEquipmentDto},
        TContext
      > => {
      return useMutation(getAdminControllerMergeCamerasMutationOptions(options), queryClient);
    }
    /**
 * @summary 미검증 렌즈 목록 조회
 */
export const adminControllerGetUnverifiedLenses = (
    params: AdminControllerGetUnverifiedLensesParams,
 signal?: AbortSignal
) => {
      
      
      return customAxiosInstance<LensListResponseDtoResponse>(
      {url: `/api/v1/admin/lenses/unverified`, method: 'GET',
        params, signal
    },
      );
    }
  



export const getAdminControllerGetUnverifiedLensesInfiniteQueryKey = (params?: AdminControllerGetUnverifiedLensesParams,) => {
    return [
    'infinite', `/api/v1/admin/lenses/unverified`, ...(params ? [params] : [])
    ] as const;
    }

export const getAdminControllerGetUnverifiedLensesQueryKey = (params?: AdminControllerGetUnverifiedLensesParams,) => {
    return [
    `/api/v1/admin/lenses/unverified`, ...(params ? [params] : [])
    ] as const;
    }

    
export const getAdminControllerGetUnverifiedLensesInfiniteQueryOptions = <TData = InfiniteData<Awaited<ReturnType<typeof adminControllerGetUnverifiedLenses>>>, TError = unknown>(params: AdminControllerGetUnverifiedLensesParams, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof adminControllerGetUnverifiedLenses>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getAdminControllerGetUnverifiedLensesInfiniteQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof adminControllerGetUnverifiedLenses>>> = ({ signal }) => adminControllerGetUnverifiedLenses(params, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseInfiniteQueryOptions<Awaited<ReturnType<typeof adminControllerGetUnverifiedLenses>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type AdminControllerGetUnverifiedLensesInfiniteQueryResult = NonNullable<Awaited<ReturnType<typeof adminControllerGetUnverifiedLenses>>>
export type AdminControllerGetUnverifiedLensesInfiniteQueryError = unknown


export function useAdminControllerGetUnverifiedLensesInfinite<TData = InfiniteData<Awaited<ReturnType<typeof adminControllerGetUnverifiedLenses>>>, TError = unknown>(
 params: AdminControllerGetUnverifiedLensesParams, options: { query:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof adminControllerGetUnverifiedLenses>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof adminControllerGetUnverifiedLenses>>,
          TError,
          Awaited<ReturnType<typeof adminControllerGetUnverifiedLenses>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useAdminControllerGetUnverifiedLensesInfinite<TData = InfiniteData<Awaited<ReturnType<typeof adminControllerGetUnverifiedLenses>>>, TError = unknown>(
 params: AdminControllerGetUnverifiedLensesParams, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof adminControllerGetUnverifiedLenses>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof adminControllerGetUnverifiedLenses>>,
          TError,
          Awaited<ReturnType<typeof adminControllerGetUnverifiedLenses>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useAdminControllerGetUnverifiedLensesInfinite<TData = InfiniteData<Awaited<ReturnType<typeof adminControllerGetUnverifiedLenses>>>, TError = unknown>(
 params: AdminControllerGetUnverifiedLensesParams, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof adminControllerGetUnverifiedLenses>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary 미검증 렌즈 목록 조회
 */

export function useAdminControllerGetUnverifiedLensesInfinite<TData = InfiniteData<Awaited<ReturnType<typeof adminControllerGetUnverifiedLenses>>>, TError = unknown>(
 params: AdminControllerGetUnverifiedLensesParams, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof adminControllerGetUnverifiedLenses>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getAdminControllerGetUnverifiedLensesInfiniteQueryOptions(params,options)

  const query = useInfiniteQuery(queryOptions, queryClient) as  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




export const getAdminControllerGetUnverifiedLensesQueryOptions = <TData = Awaited<ReturnType<typeof adminControllerGetUnverifiedLenses>>, TError = unknown>(params: AdminControllerGetUnverifiedLensesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof adminControllerGetUnverifiedLenses>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getAdminControllerGetUnverifiedLensesQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof adminControllerGetUnverifiedLenses>>> = ({ signal }) => adminControllerGetUnverifiedLenses(params, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof adminControllerGetUnverifiedLenses>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type AdminControllerGetUnverifiedLensesQueryResult = NonNullable<Awaited<ReturnType<typeof adminControllerGetUnverifiedLenses>>>
export type AdminControllerGetUnverifiedLensesQueryError = unknown


export function useAdminControllerGetUnverifiedLenses<TData = Awaited<ReturnType<typeof adminControllerGetUnverifiedLenses>>, TError = unknown>(
 params: AdminControllerGetUnverifiedLensesParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof adminControllerGetUnverifiedLenses>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof adminControllerGetUnverifiedLenses>>,
          TError,
          Awaited<ReturnType<typeof adminControllerGetUnverifiedLenses>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useAdminControllerGetUnverifiedLenses<TData = Awaited<ReturnType<typeof adminControllerGetUnverifiedLenses>>, TError = unknown>(
 params: AdminControllerGetUnverifiedLensesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof adminControllerGetUnverifiedLenses>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof adminControllerGetUnverifiedLenses>>,
          TError,
          Awaited<ReturnType<typeof adminControllerGetUnverifiedLenses>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useAdminControllerGetUnverifiedLenses<TData = Awaited<ReturnType<typeof adminControllerGetUnverifiedLenses>>, TError = unknown>(
 params: AdminControllerGetUnverifiedLensesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof adminControllerGetUnverifiedLenses>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary 미검증 렌즈 목록 조회
 */

export function useAdminControllerGetUnverifiedLenses<TData = Awaited<ReturnType<typeof adminControllerGetUnverifiedLenses>>, TError = unknown>(
 params: AdminControllerGetUnverifiedLensesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof adminControllerGetUnverifiedLenses>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getAdminControllerGetUnverifiedLensesQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




/**
 * @summary 렌즈 병합
 */
export const adminControllerMergeLenses = (
    mergeEquipmentDto: MergeEquipmentDto,
 signal?: AbortSignal
) => {
      
      
      return customAxiosInstance<LensResponseDtoResponse | AdminControllerMergeLenses201>(
      {url: `/api/v1/admin/lenses/merge`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: mergeEquipmentDto, signal
    },
      );
    }
  


export const getAdminControllerMergeLensesMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof adminControllerMergeLenses>>, TError,{data: MergeEquipmentDto}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof adminControllerMergeLenses>>, TError,{data: MergeEquipmentDto}, TContext> => {

const mutationKey = ['adminControllerMergeLenses'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof adminControllerMergeLenses>>, {data: MergeEquipmentDto}> = (props) => {
          const {data} = props ?? {};

          return  adminControllerMergeLenses(data,)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type AdminControllerMergeLensesMutationResult = NonNullable<Awaited<ReturnType<typeof adminControllerMergeLenses>>>
    export type AdminControllerMergeLensesMutationBody = MergeEquipmentDto
    export type AdminControllerMergeLensesMutationError = unknown

    /**
 * @summary 렌즈 병합
 */
export const useAdminControllerMergeLenses = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof adminControllerMergeLenses>>, TError,{data: MergeEquipmentDto}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof adminControllerMergeLenses>>,
        TError,
        {data: MergeEquipmentDto},
        TContext
      > => {
      return useMutation(getAdminControllerMergeLensesMutationOptions(options), queryClient);
    }
    /**
 * @summary 업로드 이미지 목록 조회
 */
export const adminControllerGetImages = (
    params: AdminControllerGetImagesParams,
 signal?: AbortSignal
) => {
      
      
      return customAxiosInstance<AdminImageListResponseDtoResponse>(
      {url: `/api/v1/admin/images`, method: 'GET',
        params, signal
    },
      );
    }
  



export const getAdminControllerGetImagesInfiniteQueryKey = (params?: AdminControllerGetImagesParams,) => {
    return [
    'infinite', `/api/v1/admin/images`, ...(params ? [params] : [])
    ] as const;
    }

export const getAdminControllerGetImagesQueryKey = (params?: AdminControllerGetImagesParams,) => {
    return [
    `/api/v1/admin/images`, ...(params ? [params] : [])
    ] as const;
    }

    
export const getAdminControllerGetImagesInfiniteQueryOptions = <TData = InfiniteData<Awaited<ReturnType<typeof adminControllerGetImages>>>, TError = unknown>(params: AdminControllerGetImagesParams, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof adminControllerGetImages>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getAdminControllerGetImagesInfiniteQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof adminControllerGetImages>>> = ({ signal }) => adminControllerGetImages(params, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseInfiniteQueryOptions<Awaited<ReturnType<typeof adminControllerGetImages>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type AdminControllerGetImagesInfiniteQueryResult = NonNullable<Awaited<ReturnType<typeof adminControllerGetImages>>>
export type AdminControllerGetImagesInfiniteQueryError = unknown


export function useAdminControllerGetImagesInfinite<TData = InfiniteData<Awaited<ReturnType<typeof adminControllerGetImages>>>, TError = unknown>(
 params: AdminControllerGetImagesParams, options: { query:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof adminControllerGetImages>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof adminControllerGetImages>>,
          TError,
          Awaited<ReturnType<typeof adminControllerGetImages>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useAdminControllerGetImagesInfinite<TData = InfiniteData<Awaited<ReturnType<typeof adminControllerGetImages>>>, TError = unknown>(
 params: AdminControllerGetImagesParams, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof adminControllerGetImages>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof adminControllerGetImages>>,
          TError,
          Awaited<ReturnType<typeof adminControllerGetImages>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useAdminControllerGetImagesInfinite<TData = InfiniteData<Awaited<ReturnType<typeof adminControllerGetImages>>>, TError = unknown>(
 params: AdminControllerGetImagesParams, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof adminControllerGetImages>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary 업로드 이미지 목록 조회
 */

export function useAdminControllerGetImagesInfinite<TData = InfiniteData<Awaited<ReturnType<typeof adminControllerGetImages>>>, TError = unknown>(
 params: AdminControllerGetImagesParams, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof adminControllerGetImages>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getAdminControllerGetImagesInfiniteQueryOptions(params,options)

  const query = useInfiniteQuery(queryOptions, queryClient) as  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




export const getAdminControllerGetImagesQueryOptions = <TData = Awaited<ReturnType<typeof adminControllerGetImages>>, TError = unknown>(params: AdminControllerGetImagesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof adminControllerGetImages>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getAdminControllerGetImagesQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof adminControllerGetImages>>> = ({ signal }) => adminControllerGetImages(params, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof adminControllerGetImages>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type AdminControllerGetImagesQueryResult = NonNullable<Awaited<ReturnType<typeof adminControllerGetImages>>>
export type AdminControllerGetImagesQueryError = unknown


export function useAdminControllerGetImages<TData = Awaited<ReturnType<typeof adminControllerGetImages>>, TError = unknown>(
 params: AdminControllerGetImagesParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof adminControllerGetImages>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof adminControllerGetImages>>,
          TError,
          Awaited<ReturnType<typeof adminControllerGetImages>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useAdminControllerGetImages<TData = Awaited<ReturnType<typeof adminControllerGetImages>>, TError = unknown>(
 params: AdminControllerGetImagesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof adminControllerGetImages>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof adminControllerGetImages>>,
          TError,
          Awaited<ReturnType<typeof adminControllerGetImages>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useAdminControllerGetImages<TData = Awaited<ReturnType<typeof adminControllerGetImages>>, TError = unknown>(
 params: AdminControllerGetImagesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof adminControllerGetImages>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary 업로드 이미지 목록 조회
 */

export function useAdminControllerGetImages<TData = Awaited<ReturnType<typeof adminControllerGetImages>>, TError = unknown>(
 params: AdminControllerGetImagesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof adminControllerGetImages>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getAdminControllerGetImagesQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




/**
 * @summary 삭제된 게시글 목록 조회
 */
export const adminControllerGetDeletedPosts = (
    params: AdminControllerGetDeletedPostsParams,
 signal?: AbortSignal
) => {
      
      
      return customAxiosInstance<AdminDeletedPostListResponseDtoResponse>(
      {url: `/api/v1/admin/deleted-posts`, method: 'GET',
        params, signal
    },
      );
    }
  



export const getAdminControllerGetDeletedPostsInfiniteQueryKey = (params?: AdminControllerGetDeletedPostsParams,) => {
    return [
    'infinite', `/api/v1/admin/deleted-posts`, ...(params ? [params] : [])
    ] as const;
    }

export const getAdminControllerGetDeletedPostsQueryKey = (params?: AdminControllerGetDeletedPostsParams,) => {
    return [
    `/api/v1/admin/deleted-posts`, ...(params ? [params] : [])
    ] as const;
    }

    
export const getAdminControllerGetDeletedPostsInfiniteQueryOptions = <TData = InfiniteData<Awaited<ReturnType<typeof adminControllerGetDeletedPosts>>>, TError = unknown>(params: AdminControllerGetDeletedPostsParams, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof adminControllerGetDeletedPosts>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getAdminControllerGetDeletedPostsInfiniteQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof adminControllerGetDeletedPosts>>> = ({ signal }) => adminControllerGetDeletedPosts(params, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseInfiniteQueryOptions<Awaited<ReturnType<typeof adminControllerGetDeletedPosts>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type AdminControllerGetDeletedPostsInfiniteQueryResult = NonNullable<Awaited<ReturnType<typeof adminControllerGetDeletedPosts>>>
export type AdminControllerGetDeletedPostsInfiniteQueryError = unknown


export function useAdminControllerGetDeletedPostsInfinite<TData = InfiniteData<Awaited<ReturnType<typeof adminControllerGetDeletedPosts>>>, TError = unknown>(
 params: AdminControllerGetDeletedPostsParams, options: { query:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof adminControllerGetDeletedPosts>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof adminControllerGetDeletedPosts>>,
          TError,
          Awaited<ReturnType<typeof adminControllerGetDeletedPosts>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useAdminControllerGetDeletedPostsInfinite<TData = InfiniteData<Awaited<ReturnType<typeof adminControllerGetDeletedPosts>>>, TError = unknown>(
 params: AdminControllerGetDeletedPostsParams, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof adminControllerGetDeletedPosts>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof adminControllerGetDeletedPosts>>,
          TError,
          Awaited<ReturnType<typeof adminControllerGetDeletedPosts>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useAdminControllerGetDeletedPostsInfinite<TData = InfiniteData<Awaited<ReturnType<typeof adminControllerGetDeletedPosts>>>, TError = unknown>(
 params: AdminControllerGetDeletedPostsParams, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof adminControllerGetDeletedPosts>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary 삭제된 게시글 목록 조회
 */

export function useAdminControllerGetDeletedPostsInfinite<TData = InfiniteData<Awaited<ReturnType<typeof adminControllerGetDeletedPosts>>>, TError = unknown>(
 params: AdminControllerGetDeletedPostsParams, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof adminControllerGetDeletedPosts>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getAdminControllerGetDeletedPostsInfiniteQueryOptions(params,options)

  const query = useInfiniteQuery(queryOptions, queryClient) as  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




export const getAdminControllerGetDeletedPostsQueryOptions = <TData = Awaited<ReturnType<typeof adminControllerGetDeletedPosts>>, TError = unknown>(params: AdminControllerGetDeletedPostsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof adminControllerGetDeletedPosts>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getAdminControllerGetDeletedPostsQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof adminControllerGetDeletedPosts>>> = ({ signal }) => adminControllerGetDeletedPosts(params, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof adminControllerGetDeletedPosts>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type AdminControllerGetDeletedPostsQueryResult = NonNullable<Awaited<ReturnType<typeof adminControllerGetDeletedPosts>>>
export type AdminControllerGetDeletedPostsQueryError = unknown


export function useAdminControllerGetDeletedPosts<TData = Awaited<ReturnType<typeof adminControllerGetDeletedPosts>>, TError = unknown>(
 params: AdminControllerGetDeletedPostsParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof adminControllerGetDeletedPosts>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof adminControllerGetDeletedPosts>>,
          TError,
          Awaited<ReturnType<typeof adminControllerGetDeletedPosts>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useAdminControllerGetDeletedPosts<TData = Awaited<ReturnType<typeof adminControllerGetDeletedPosts>>, TError = unknown>(
 params: AdminControllerGetDeletedPostsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof adminControllerGetDeletedPosts>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof adminControllerGetDeletedPosts>>,
          TError,
          Awaited<ReturnType<typeof adminControllerGetDeletedPosts>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useAdminControllerGetDeletedPosts<TData = Awaited<ReturnType<typeof adminControllerGetDeletedPosts>>, TError = unknown>(
 params: AdminControllerGetDeletedPostsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof adminControllerGetDeletedPosts>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary 삭제된 게시글 목록 조회
 */

export function useAdminControllerGetDeletedPosts<TData = Awaited<ReturnType<typeof adminControllerGetDeletedPosts>>, TError = unknown>(
 params: AdminControllerGetDeletedPostsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof adminControllerGetDeletedPosts>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getAdminControllerGetDeletedPostsQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




/**
 * @summary 삭제된 댓글 목록 조회
 */
export const adminControllerGetDeletedComments = (
    params: AdminControllerGetDeletedCommentsParams,
 signal?: AbortSignal
) => {
      
      
      return customAxiosInstance<AdminDeletedCommentListResponseDtoResponse>(
      {url: `/api/v1/admin/deleted-comments`, method: 'GET',
        params, signal
    },
      );
    }
  



export const getAdminControllerGetDeletedCommentsInfiniteQueryKey = (params?: AdminControllerGetDeletedCommentsParams,) => {
    return [
    'infinite', `/api/v1/admin/deleted-comments`, ...(params ? [params] : [])
    ] as const;
    }

export const getAdminControllerGetDeletedCommentsQueryKey = (params?: AdminControllerGetDeletedCommentsParams,) => {
    return [
    `/api/v1/admin/deleted-comments`, ...(params ? [params] : [])
    ] as const;
    }

    
export const getAdminControllerGetDeletedCommentsInfiniteQueryOptions = <TData = InfiniteData<Awaited<ReturnType<typeof adminControllerGetDeletedComments>>>, TError = unknown>(params: AdminControllerGetDeletedCommentsParams, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof adminControllerGetDeletedComments>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getAdminControllerGetDeletedCommentsInfiniteQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof adminControllerGetDeletedComments>>> = ({ signal }) => adminControllerGetDeletedComments(params, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseInfiniteQueryOptions<Awaited<ReturnType<typeof adminControllerGetDeletedComments>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type AdminControllerGetDeletedCommentsInfiniteQueryResult = NonNullable<Awaited<ReturnType<typeof adminControllerGetDeletedComments>>>
export type AdminControllerGetDeletedCommentsInfiniteQueryError = unknown


export function useAdminControllerGetDeletedCommentsInfinite<TData = InfiniteData<Awaited<ReturnType<typeof adminControllerGetDeletedComments>>>, TError = unknown>(
 params: AdminControllerGetDeletedCommentsParams, options: { query:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof adminControllerGetDeletedComments>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof adminControllerGetDeletedComments>>,
          TError,
          Awaited<ReturnType<typeof adminControllerGetDeletedComments>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useAdminControllerGetDeletedCommentsInfinite<TData = InfiniteData<Awaited<ReturnType<typeof adminControllerGetDeletedComments>>>, TError = unknown>(
 params: AdminControllerGetDeletedCommentsParams, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof adminControllerGetDeletedComments>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof adminControllerGetDeletedComments>>,
          TError,
          Awaited<ReturnType<typeof adminControllerGetDeletedComments>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useAdminControllerGetDeletedCommentsInfinite<TData = InfiniteData<Awaited<ReturnType<typeof adminControllerGetDeletedComments>>>, TError = unknown>(
 params: AdminControllerGetDeletedCommentsParams, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof adminControllerGetDeletedComments>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary 삭제된 댓글 목록 조회
 */

export function useAdminControllerGetDeletedCommentsInfinite<TData = InfiniteData<Awaited<ReturnType<typeof adminControllerGetDeletedComments>>>, TError = unknown>(
 params: AdminControllerGetDeletedCommentsParams, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof adminControllerGetDeletedComments>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getAdminControllerGetDeletedCommentsInfiniteQueryOptions(params,options)

  const query = useInfiniteQuery(queryOptions, queryClient) as  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




export const getAdminControllerGetDeletedCommentsQueryOptions = <TData = Awaited<ReturnType<typeof adminControllerGetDeletedComments>>, TError = unknown>(params: AdminControllerGetDeletedCommentsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof adminControllerGetDeletedComments>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getAdminControllerGetDeletedCommentsQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof adminControllerGetDeletedComments>>> = ({ signal }) => adminControllerGetDeletedComments(params, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof adminControllerGetDeletedComments>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type AdminControllerGetDeletedCommentsQueryResult = NonNullable<Awaited<ReturnType<typeof adminControllerGetDeletedComments>>>
export type AdminControllerGetDeletedCommentsQueryError = unknown


export function useAdminControllerGetDeletedComments<TData = Awaited<ReturnType<typeof adminControllerGetDeletedComments>>, TError = unknown>(
 params: AdminControllerGetDeletedCommentsParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof adminControllerGetDeletedComments>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof adminControllerGetDeletedComments>>,
          TError,
          Awaited<ReturnType<typeof adminControllerGetDeletedComments>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useAdminControllerGetDeletedComments<TData = Awaited<ReturnType<typeof adminControllerGetDeletedComments>>, TError = unknown>(
 params: AdminControllerGetDeletedCommentsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof adminControllerGetDeletedComments>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof adminControllerGetDeletedComments>>,
          TError,
          Awaited<ReturnType<typeof adminControllerGetDeletedComments>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useAdminControllerGetDeletedComments<TData = Awaited<ReturnType<typeof adminControllerGetDeletedComments>>, TError = unknown>(
 params: AdminControllerGetDeletedCommentsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof adminControllerGetDeletedComments>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary 삭제된 댓글 목록 조회
 */

export function useAdminControllerGetDeletedComments<TData = Awaited<ReturnType<typeof adminControllerGetDeletedComments>>, TError = unknown>(
 params: AdminControllerGetDeletedCommentsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof adminControllerGetDeletedComments>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getAdminControllerGetDeletedCommentsQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




