/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * Rawfli API
 * The Rawfli API description
 * OpenAPI spec version: 1.0
 */
import type { AdminImageResponseDtoExifData } from './adminImageResponseDtoExifData';

export interface AdminImageResponseDto {
  id: string;
  key: string;
  /** @nullable */
  exifData?: AdminImageResponseDtoExifData;
  uploaderId: number;
  uploaderUsername: string;
  createdAt: string;
}
