/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * Rawfli API
 * The Rawfli API description
 * OpenAPI spec version: 1.0
 */
import type { AdminDeletedArticleListResponseDto } from './adminDeletedArticleListResponseDto';

export interface AdminDeletedArticleListResponseDtoResponse {
  result: boolean;
  code: number;
  data: AdminDeletedArticleListResponseDto;
}
