/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * Rawfli API
 * The Rawfli API description
 * OpenAPI spec version: 1.0
 */
import type { ArticleListResponseDto } from './articleListResponseDto';

export interface ArticleListResponseDtoResponse {
  result: boolean;
  code: number;
  data: ArticleListResponseDto;
}
