/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * Rawfli API
 * The Rawfli API description
 * OpenAPI spec version: 1.0
 */
import type { AttachedImageDto } from './attachedImageDto';
import type { CommentResponseDto } from './commentResponseDto';
import type { ReferencedPhotoDto } from './referencedPhotoDto';
import type { UserResponseDto } from './userResponseDto';

export interface ArticleResponseDto {
  id: number;
  title: string;
  content: string;
  author: UserResponseDto;
  views: number;
  likesCount: number;
  comments: CommentResponseDto[];
  referencedPhotos: ReferencedPhotoDto[];
  attachedImages: AttachedImageDto[];
  createdAt: string;
  updatedAt: string;
}
