/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * Rawfli API
 * The Rawfli API description
 * OpenAPI spec version: 1.0
 */
import type { Article } from './article';
import type { BoardType } from './boardType';
import type { Post } from './post';

export interface Board {
  id: number;
  type: BoardType;
  name: string;
  description: string;
  articles: Article[];
  posts: Post[];
  maxPostId: number;
}
