/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * Rawfli API
 * The Rawfli API description
 * OpenAPI spec version: 1.0
 */
import type { BoardsControllerSearchInBoardSearchIn } from './boardsControllerSearchInBoardSearchIn';

export type BoardsControllerSearchInBoardParams = {
keyword: string;
searchIn?: BoardsControllerSearchInBoardSearchIn;
/**
 * @minimum 1
 */
page?: number;
/**
 * @minimum 1
 */
limit?: number;
};
