/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * Rawfli API
 * The Rawfli API description
 * OpenAPI spec version: 1.0
 */
import type { BoardResponseDto } from './boardResponseDto';

export interface BoardResponseDtoResponse {
  result: boolean;
  code: number;
  data: BoardResponseDto;
}
