/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * Rawfli API
 * The Rawfli API description
 * OpenAPI spec version: 1.0
 */
import type { CameraAliasResponseDto } from './cameraAliasResponseDto';

export interface CameraResponseDto {
  id: number;
  /** @nullable */
  brand: string | null;
  modelName: string;
  isVerified: boolean;
  aliases: CameraAliasResponseDto[];
}
