/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * Rawfli API
 * The Rawfli API description
 * OpenAPI spec version: 1.0
 */
import type { Article } from './article';
import type { Comment as __Comment } from './comment';
import type { User } from './user';

export interface Comment {
  article: Article;
  author: User;
  content: string;
  replies: Comment[];
  parent?: __Comment;
}
