/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * Rawfli API
 * The Rawfli API description
 * OpenAPI spec version: 1.0
 */

export interface CreatePostPhotoDto {
  imageId: string;
  description?: string;
  /** @minimum 0 */
  iso?: number;
  /** @minimum 0 */
  aperture?: number;
  shutterSpeed?: string;
  /** @minimum 0 */
  focalLength?: number;
  cameraModel?: string;
  cameraBrand?: string;
  lensModel?: string;
  lensBrand?: string;
}
