/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * Rawfli API
 * The Rawfli API description
 * OpenAPI spec version: 1.0
 */

export interface CreateUserDto {
  email: string;
  /** @pattern /^[a-zA-Z0-9가-힣]+$/ */
  username: string;
  /** @minLength 6 */
  password: string;
}
