/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * Rawfli API
 * The Rawfli API description
 * OpenAPI spec version: 1.0
 */

export interface DeletedCommentResponseDto {
  id: number;
  originalCommentId: number;
  postId: number;
  /** @nullable */
  boardId: number | null;
  authorId: number;
  content: string;
  originalCreatedAt: string;
  deletedAt: string;
}
