/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * Rawfli API
 * The Rawfli API description
 * OpenAPI spec version: 1.0
 */
import type { Photo } from './photo';
import type { User } from './user';

export interface Image {
  id: string;
  key: string;
  uploader: User;
  photos: Photo[];
}
