/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * Rawfli API
 * The Rawfli API description
 * OpenAPI spec version: 1.0
 */
import type { LensAlias } from './lensAlias';

export interface Lens {
  /** @nullable */
  brand: string | null;
  modelName: string;
  isVerified: boolean;
  aliases: LensAlias[];
}
