/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * Rawfli API
 * The Rawfli API description
 * OpenAPI spec version: 1.0
 */

export interface MyImageItemResponseDto {
  /** @nullable */
  cameraMake?: string | null;
  /** @nullable */
  cameraModel?: string | null;
  /** @nullable */
  lensMake?: string | null;
  /** @nullable */
  lensModel?: string | null;
  /** @nullable */
  iso?: number | null;
  /** @nullable */
  aperture?: number | null;
  /** @nullable */
  shutterSpeedDisplay?: string | null;
  /** @nullable */
  shutterSpeedValue?: number | null;
  /** @nullable */
  focalLength?: number | null;
  id: string;
  key: string;
  createdAt: string;
  usedInPhotoCount: number;
}
