/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * Rawfli API
 * The Rawfli API description
 * OpenAPI spec version: 1.0
 */
import type { GalleryPost } from './galleryPost';
import type { Image } from './image';
import type { PhotoReferencedInArticlesItem } from './photoReferencedInArticlesItem';
import type { User } from './user';

export interface Photo {
  id: string;
  image: Image;
  post: GalleryPost;
  author: User;
  description?: string;
  likes: User[];
  referencedInArticles: PhotoReferencedInArticlesItem[];
}
