/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * Rawfli API
 * The Rawfli API description
 * OpenAPI spec version: 1.0
 */
import type { Camera } from './camera';
import type { Image } from './image';
import type { Lens } from './lens';
import type { PhotoCommentsItem } from './photoCommentsItem';
import type { PhotoReferencedInArticlesItem } from './photoReferencedInArticlesItem';
import type { Post } from './post';
import type { User } from './user';

export interface Photo {
  id: string;
  image: Image;
  post: Post;
  author: User;
  description?: string;
  /** @nullable */
  iso: number | null;
  /** @nullable */
  aperture: number | null;
  /** @nullable */
  shutterSpeedDisplay: string | null;
  /** @nullable */
  shutterSpeedValue: number | null;
  /** @nullable */
  focalLength: number | null;
  camera: Camera | null;
  lens: Lens | null;
  likes: User[];
  referencedInArticles: PhotoReferencedInArticlesItem[];
  comments: PhotoCommentsItem[];
  commentCount: number;
}
