/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * Rawfli API
 * The Rawfli API description
 * OpenAPI spec version: 1.0
 */
import type { PhotoCameraResponseDto } from './photoCameraResponseDto';
import type { PhotoLensResponseDto } from './photoLensResponseDto';

export interface PhotoResponseDto {
  description?: string;
  /** @nullable */
  iso?: number | null;
  /** @nullable */
  aperture?: number | null;
  /** @nullable */
  shutterSpeedDisplay?: string | null;
  /** @nullable */
  shutterSpeedValue?: number | null;
  /** @nullable */
  focalLength?: number | null;
  camera?: PhotoCameraResponseDto | null;
  lens?: PhotoLensResponseDto | null;
  id: string;
  imageKey: string;
}
