/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * Rawfli API
 * The Rawfli API description
 * OpenAPI spec version: 1.0
 */
import type { PhotoResponseDto } from './photoResponseDto';
import type { UserResponseDto } from './userResponseDto';

export interface PostResponseDto {
  photos?: PhotoResponseDto[];
  id: number;
  title: string;
  content: string;
  author: UserResponseDto;
  createdAt: string;
}
