/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * Rawfli API
 * The Rawfli API description
 * OpenAPI spec version: 1.0
 */
import type { Board } from './board';
import type { Comment } from './comment';
import type { User } from './user';

export interface Post {
  id: number;
  board: Board;
  author: User;
  title: string;
  content: string;
  likes: User[];
  views: number;
  comments: Comment[];
}
