/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * Rawfli API
 * The Rawfli API description
 * OpenAPI spec version: 1.0
 */
import type { CommentResponseDto } from './commentResponseDto';
import type { UserResponseDto } from './userResponseDto';

export interface PostResponseDto {
  id: number;
  title: string;
  content: string;
  author: UserResponseDto;
  views: number;
  likesCount: number;
  comments: CommentResponseDto[];
  createdAt: string;
  updatedAt: string;
}
