/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * Rawfli API
 * The Rawfli API description
 * OpenAPI spec version: 1.0
 */
import type { PostListResponseDto } from './postListResponseDto';

export interface PostListResponseDtoResponse {
  result: boolean;
  code: number;
  data: PostListResponseDto;
}
