/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * Rawfli API
 * The Rawfli API description
 * OpenAPI spec version: 1.0
 */

export type SearchResultItemResponseDtoType = typeof SearchResultItemResponseDtoType[keyof typeof SearchResultItemResponseDtoType];


export const SearchResultItemResponseDtoType = {
  post: 'post',
  article: 'article',
} as const;
