/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * Rawfli API
 * The Rawfli API description
 * OpenAPI spec version: 1.0
 */
import type { SearchAuthorResponseDto } from './searchAuthorResponseDto';
import type { SearchResultItemResponseDtoType } from './searchResultItemResponseDtoType';

export interface SearchResultItemResponseDto {
  type: SearchResultItemResponseDtoType;
  /** @nullable */
  boardId?: number | null;
  /** @nullable */
  boardName?: string | null;
  id: number;
  title: string;
  content: string;
  author: SearchAuthorResponseDto;
  views: number;
  likesCount: number;
  commentCount: number;
  createdAt: string;
}
