/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * Rawfli API
 * The Rawfli API description
 * OpenAPI spec version: 1.0
 */

export interface UpdatePasswordDto {
  /** 현재 비밀번호 */
  currentPassword: string;
  /**
   * 새 비밀번호
   * @minLength 6
   */
  newPassword: string;
}
