/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * Rawfli API
 * The Rawfli API description
 * OpenAPI spec version: 1.0
 */

export interface UpdateProfileDto {
  /** 닉네임 */
  username?: string;
  /**
   * 프로필 이미지 키
   * @nullable
   */
  profileImageKey?: string | null;
  /**
   * 자기소개
   * @maxLength 300
   * @nullable
   */
  bio?: string | null;
}
