/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * Rawfli API
 * The Rawfli API description
 * OpenAPI spec version: 1.0
 */
import type { ArticleListItemResponseDto } from './articleListItemResponseDto';

export interface UserInfoResponseDto {
  id: number;
  username: string;
  /** @nullable */
  profileImageKey?: string | null;
  articles: ArticleListItemResponseDto[];
  followerCount: number;
  followingCount: number;
  createdAt: string;
  /** @nullable */
  bio?: string | null;
}
