/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * Rawfli API
 * The Rawfli API description
 * OpenAPI spec version: 1.0
 */

export interface UserResponseDto {
  id: number;
  username: string;
  /** @nullable */
  profileImageKey: string | null;
  createdAt: string;
  email: string;
  password: string;
}
