/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * Rawfli API
 * The Rawfli API description
 * OpenAPI spec version: 1.0
 */
import type { PostResponseDto } from './postResponseDto';

export interface UserInfoResponseDto {
  id: number;
  username: string;
  /** @nullable */
  profileImageKey?: string | null;
  posts: PostResponseDto[];
  followerCount: number;
  followingCount: number;
  createdAt: string;
}
