/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * Rawfli API
 * The Rawfli API description
 * OpenAPI spec version: 1.0
 */
import type { Article } from './article';
import type { Comment } from './comment';
import type { Follow } from './follow';
import type { Image } from './image';
import type { Photo } from './photo';
import type { Post } from './post';

export interface User {
  email: string;
  username: string;
  password: string;
  /** @nullable */
  profileImageKey: string | null;
  articles: Article[];
  posts: Post[];
  comments: Comment[];
  images: Image[];
  photos: Photo[];
  likedArticles: Article[];
  likedPhotos: Photo[];
  blockedUsers: User[];
  followers: Follow[];
  followings: Follow[];
}
